/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type CreatorPending = { address: Address; amount: bigint };

export type CreatorPendingArgs = { address: Address; amount: number | bigint };

export function getCreatorPendingEncoder(): FixedSizeEncoder<CreatorPendingArgs> {
  return getStructEncoder([
    ['address', getAddressEncoder()],
    ['amount', getU64Encoder()],
  ]);
}

export function getCreatorPendingDecoder(): FixedSizeDecoder<CreatorPending> {
  return getStructDecoder([
    ['address', getAddressDecoder()],
    ['amount', getU64Decoder()],
  ]);
}

export function getCreatorPendingCodec(): FixedSizeCodec<
  CreatorPendingArgs,
  CreatorPending
> {
  return combineCodec(getCreatorPendingEncoder(), getCreatorPendingDecoder());
}
