/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type GameSettledPartial = {
  gameId: bigint;
  gameAccount: Address;
  creatorsLeft: number;
  winnersLeft: number;
  paidCreatorsThisTx: number;
  paidWinnersThisTx: number;
  amountPaid: bigint;
};

export type GameSettledPartialArgs = {
  gameId: number | bigint;
  gameAccount: Address;
  creatorsLeft: number;
  winnersLeft: number;
  paidCreatorsThisTx: number;
  paidWinnersThisTx: number;
  amountPaid: number | bigint;
};

export function getGameSettledPartialEncoder(): FixedSizeEncoder<GameSettledPartialArgs> {
  return getStructEncoder([
    ['gameId', getU64Encoder()],
    ['gameAccount', getAddressEncoder()],
    ['creatorsLeft', getU32Encoder()],
    ['winnersLeft', getU32Encoder()],
    ['paidCreatorsThisTx', getU32Encoder()],
    ['paidWinnersThisTx', getU32Encoder()],
    ['amountPaid', getU64Encoder()],
  ]);
}

export function getGameSettledPartialDecoder(): FixedSizeDecoder<GameSettledPartial> {
  return getStructDecoder([
    ['gameId', getU64Decoder()],
    ['gameAccount', getAddressDecoder()],
    ['creatorsLeft', getU32Decoder()],
    ['winnersLeft', getU32Decoder()],
    ['paidCreatorsThisTx', getU32Decoder()],
    ['paidWinnersThisTx', getU32Decoder()],
    ['amountPaid', getU64Decoder()],
  ]);
}

export function getGameSettledPartialCodec(): FixedSizeCodec<
  GameSettledPartialArgs,
  GameSettledPartial
> {
  return combineCodec(
    getGameSettledPartialEncoder(),
    getGameSettledPartialDecoder()
  );
}
