/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum PayoutType {
  Same,
  ExponentialDecay,
}

export type PayoutTypeArgs = PayoutType;

export function getPayoutTypeEncoder(): FixedSizeEncoder<PayoutTypeArgs> {
  return getEnumEncoder(PayoutType);
}

export function getPayoutTypeDecoder(): FixedSizeDecoder<PayoutType> {
  return getEnumDecoder(PayoutType);
}

export function getPayoutTypeCodec(): FixedSizeCodec<
  PayoutTypeArgs,
  PayoutType
> {
  return combineCodec(getPayoutTypeEncoder(), getPayoutTypeDecoder());
}
