/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum WagerType {
  SameWager,
  CustomWager,
  BetRange,
}

export type WagerTypeArgs = WagerType;

export function getWagerTypeEncoder(): FixedSizeEncoder<WagerTypeArgs> {
  return getEnumEncoder(WagerType);
}

export function getWagerTypeDecoder(): FixedSizeDecoder<WagerType> {
  return getEnumDecoder(WagerType);
}

export function getWagerTypeCodec(): FixedSizeCodec<WagerTypeArgs, WagerType> {
  return combineCodec(getWagerTypeEncoder(), getWagerTypeDecoder());
}
