/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const GAMBA_STATE_DISCRIMINATOR = new Uint8Array([
  142, 203, 14, 224, 153, 118, 52, 200,
]);

export function getGambaStateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(GAMBA_STATE_DISCRIMINATOR);
}

export type GambaState = {
  discriminator: ReadonlyUint8Array;
  rng: Address;
  authority: Address;
  gambaFeeAddress: Address;
  gambaFeeBps: number;
  initialized: boolean;
  gameId: bigint;
  bump: number;
};

export type GambaStateArgs = {
  rng: Address;
  authority: Address;
  gambaFeeAddress: Address;
  gambaFeeBps: number;
  initialized: boolean;
  gameId: number | bigint;
  bump: number;
};

export function getGambaStateEncoder(): FixedSizeEncoder<GambaStateArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['rng', getAddressEncoder()],
      ['authority', getAddressEncoder()],
      ['gambaFeeAddress', getAddressEncoder()],
      ['gambaFeeBps', getU32Encoder()],
      ['initialized', getBooleanEncoder()],
      ['gameId', getU64Encoder()],
      ['bump', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: GAMBA_STATE_DISCRIMINATOR })
  );
}

export function getGambaStateDecoder(): FixedSizeDecoder<GambaState> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['rng', getAddressDecoder()],
    ['authority', getAddressDecoder()],
    ['gambaFeeAddress', getAddressDecoder()],
    ['gambaFeeBps', getU32Decoder()],
    ['initialized', getBooleanDecoder()],
    ['gameId', getU64Decoder()],
    ['bump', getU8Decoder()],
  ]);
}

export function getGambaStateCodec(): FixedSizeCodec<
  GambaStateArgs,
  GambaState
> {
  return combineCodec(getGambaStateEncoder(), getGambaStateDecoder());
}

export function decodeGambaState<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<GambaState, TAddress>;
export function decodeGambaState<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<GambaState, TAddress>;
export function decodeGambaState<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<GambaState, TAddress> | MaybeAccount<GambaState, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getGambaStateDecoder()
  );
}

export async function fetchGambaState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<GambaState, TAddress>> {
  const maybeAccount = await fetchMaybeGambaState(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeGambaState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<GambaState, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeGambaState(maybeAccount);
}

export async function fetchAllGambaState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<GambaState>[]> {
  const maybeAccounts = await fetchAllMaybeGambaState(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeGambaState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<GambaState>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeGambaState(maybeAccount));
}

export function getGambaStateSize(): number {
  return 118;
}
