/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedDepositInstruction,
  type ParsedInitializeVaultInstruction,
  type ParsedWithdrawInstruction,
} from '../instructions';

export const STAKE_VAULT_PROGRAM_ADDRESS =
  'stkSHzr3WAVxDtzWhfBb4Sgw5e6Tbpuv5QtY3Hpi3ox' as Address<'stkSHzr3WAVxDtzWhfBb4Sgw5e6Tbpuv5QtY3Hpi3ox'>;

export enum StakeVaultAccount {
  StakeAccount,
  Vault,
}

export function identifyStakeVaultAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): StakeVaultAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([80, 158, 67, 124, 50, 189, 192, 255])
      ),
      0
    )
  ) {
    return StakeVaultAccount.StakeAccount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([211, 8, 232, 43, 2, 152, 117, 119])
      ),
      0
    )
  ) {
    return StakeVaultAccount.Vault;
  }
  throw new Error(
    'The provided account could not be identified as a stakeVault account.'
  );
}

export enum StakeVaultInstruction {
  Deposit,
  InitializeVault,
  Withdraw,
}

export function identifyStakeVaultInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): StakeVaultInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([242, 35, 198, 137, 82, 225, 242, 182])
      ),
      0
    )
  ) {
    return StakeVaultInstruction.Deposit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([48, 191, 163, 44, 71, 129, 63, 164])
      ),
      0
    )
  ) {
    return StakeVaultInstruction.InitializeVault;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([183, 18, 70, 156, 148, 109, 161, 34])
      ),
      0
    )
  ) {
    return StakeVaultInstruction.Withdraw;
  }
  throw new Error(
    'The provided instruction could not be identified as a stakeVault instruction.'
  );
}

export type ParsedStakeVaultInstruction<
  TProgram extends string = 'stkSHzr3WAVxDtzWhfBb4Sgw5e6Tbpuv5QtY3Hpi3ox',
> =
  | ({
      instructionType: StakeVaultInstruction.Deposit;
    } & ParsedDepositInstruction<TProgram>)
  | ({
      instructionType: StakeVaultInstruction.InitializeVault;
    } & ParsedInitializeVaultInstruction<TProgram>)
  | ({
      instructionType: StakeVaultInstruction.Withdraw;
    } & ParsedWithdrawInstruction<TProgram>);
