/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MULTIPLAYER_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CREATE_GAME_SPL_DISCRIMINATOR = new Uint8Array([
  80, 235, 44, 243, 14, 15, 248, 207,
]);

export function getCreateGameSplDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_GAME_SPL_DISCRIMINATOR
  );
}

export type CreateGameSplInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountGameAccount extends string | AccountMeta<string> = string,
  TAccountMetadataAccount extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountGameAccountTaAccount extends string | AccountMeta<string> = string,
  TAccountGameMaker extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends
    | string
    | AccountMeta<string> = 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGameAccount extends string
        ? WritableAccount<TAccountGameAccount>
        : TAccountGameAccount,
      TAccountMetadataAccount extends string
        ? WritableAccount<TAccountMetadataAccount>
        : TAccountMetadataAccount,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountGameAccountTaAccount extends string
        ? WritableAccount<TAccountGameAccountTaAccount>
        : TAccountGameAccountTaAccount,
      TAccountGameMaker extends string
        ? WritableSignerAccount<TAccountGameMaker> &
            AccountSignerMeta<TAccountGameMaker>
        : TAccountGameMaker,
      TAccountGambaState extends string
        ? WritableAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateGameSplInstructionData = {
  discriminator: ReadonlyUint8Array;
  preAllocPlayers: number;
  maxPlayers: number;
  numTeams: number;
  winnersTarget: number;
  wagerType: number;
  payoutType: number;
  wager: bigint;
  softDuration: bigint;
  hardDuration: bigint;
  gameSeed: bigint;
  minBet: bigint;
  maxBet: bigint;
};

export type CreateGameSplInstructionDataArgs = {
  preAllocPlayers: number;
  maxPlayers: number;
  numTeams: number;
  winnersTarget: number;
  wagerType: number;
  payoutType: number;
  wager: number | bigint;
  softDuration: number | bigint;
  hardDuration: number | bigint;
  gameSeed: number | bigint;
  minBet: number | bigint;
  maxBet: number | bigint;
};

export function getCreateGameSplInstructionDataEncoder(): FixedSizeEncoder<CreateGameSplInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['preAllocPlayers', getU16Encoder()],
      ['maxPlayers', getU16Encoder()],
      ['numTeams', getU8Encoder()],
      ['winnersTarget', getU16Encoder()],
      ['wagerType', getU8Encoder()],
      ['payoutType', getU8Encoder()],
      ['wager', getU64Encoder()],
      ['softDuration', getI64Encoder()],
      ['hardDuration', getI64Encoder()],
      ['gameSeed', getU64Encoder()],
      ['minBet', getU64Encoder()],
      ['maxBet', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_GAME_SPL_DISCRIMINATOR })
  );
}

export function getCreateGameSplInstructionDataDecoder(): FixedSizeDecoder<CreateGameSplInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['preAllocPlayers', getU16Decoder()],
    ['maxPlayers', getU16Decoder()],
    ['numTeams', getU8Decoder()],
    ['winnersTarget', getU16Decoder()],
    ['wagerType', getU8Decoder()],
    ['payoutType', getU8Decoder()],
    ['wager', getU64Decoder()],
    ['softDuration', getI64Decoder()],
    ['hardDuration', getI64Decoder()],
    ['gameSeed', getU64Decoder()],
    ['minBet', getU64Decoder()],
    ['maxBet', getU64Decoder()],
  ]);
}

export function getCreateGameSplInstructionDataCodec(): FixedSizeCodec<
  CreateGameSplInstructionDataArgs,
  CreateGameSplInstructionData
> {
  return combineCodec(
    getCreateGameSplInstructionDataEncoder(),
    getCreateGameSplInstructionDataDecoder()
  );
}

export type CreateGameSplAsyncInput<
  TAccountGameAccount extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountMint extends string = string,
  TAccountGameAccountTaAccount extends string = string,
  TAccountGameMaker extends string = string,
  TAccountGambaState extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
> = {
  /** The on-chain Game account, PDA = [b"GAME", game_seed]. */
  gameAccount?: Address<TAccountGameAccount>;
  /** Always-present metadata PDA, PDA = [b"METADATA", game_account.key()] */
  metadataAccount?: Address<TAccountMetadataAccount>;
  /** the SPL mint for wagers */
  mint: Address<TAccountMint>;
  /** escrow token account for this game */
  gameAccountTaAccount?: Address<TAccountGameAccountTaAccount>;
  gameMaker: TransactionSigner<TAccountGameMaker>;
  gambaState?: Address<TAccountGambaState>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  preAllocPlayers: CreateGameSplInstructionDataArgs['preAllocPlayers'];
  maxPlayers: CreateGameSplInstructionDataArgs['maxPlayers'];
  numTeams: CreateGameSplInstructionDataArgs['numTeams'];
  winnersTarget: CreateGameSplInstructionDataArgs['winnersTarget'];
  wagerType: CreateGameSplInstructionDataArgs['wagerType'];
  payoutType: CreateGameSplInstructionDataArgs['payoutType'];
  wager: CreateGameSplInstructionDataArgs['wager'];
  softDuration: CreateGameSplInstructionDataArgs['softDuration'];
  hardDuration: CreateGameSplInstructionDataArgs['hardDuration'];
  gameSeed: CreateGameSplInstructionDataArgs['gameSeed'];
  minBet: CreateGameSplInstructionDataArgs['minBet'];
  maxBet: CreateGameSplInstructionDataArgs['maxBet'];
};

export async function getCreateGameSplInstructionAsync<
  TAccountGameAccount extends string,
  TAccountMetadataAccount extends string,
  TAccountMint extends string,
  TAccountGameAccountTaAccount extends string,
  TAccountGameMaker extends string,
  TAccountGambaState extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: CreateGameSplAsyncInput<
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountMint,
    TAccountGameAccountTaAccount,
    TAccountGameMaker,
    TAccountGambaState,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CreateGameSplInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountMint,
    TAccountGameAccountTaAccount,
    TAccountGameMaker,
    TAccountGambaState,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    gameAccountTaAccount: {
      value: input.gameAccountTaAccount ?? null,
      isWritable: true,
    },
    gameMaker: { value: input.gameMaker ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.gameAccount.value) {
    accounts.gameAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([71, 65, 77, 69])),
        getU64Encoder().encode(expectSome(args.gameSeed)),
      ],
    });
  }
  if (!accounts.metadataAccount.value) {
    accounts.metadataAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([77, 69, 84, 65, 68, 65, 84, 65])
        ),
        getAddressEncoder().encode(expectAddress(accounts.gameAccount.value)),
      ],
    });
  }
  if (!accounts.gameAccountTaAccount.value) {
    accounts.gameAccountTaAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.gameAccount.value)),
      ],
    });
  }
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69])
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.gameAccountTaAccount),
      getAccountMeta(accounts.gameMaker),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
    ],
    programAddress,
    data: getCreateGameSplInstructionDataEncoder().encode(
      args as CreateGameSplInstructionDataArgs
    ),
  } as CreateGameSplInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountMint,
    TAccountGameAccountTaAccount,
    TAccountGameMaker,
    TAccountGambaState,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >;

  return instruction;
}

export type CreateGameSplInput<
  TAccountGameAccount extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountMint extends string = string,
  TAccountGameAccountTaAccount extends string = string,
  TAccountGameMaker extends string = string,
  TAccountGambaState extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
> = {
  /** The on-chain Game account, PDA = [b"GAME", game_seed]. */
  gameAccount: Address<TAccountGameAccount>;
  /** Always-present metadata PDA, PDA = [b"METADATA", game_account.key()] */
  metadataAccount: Address<TAccountMetadataAccount>;
  /** the SPL mint for wagers */
  mint: Address<TAccountMint>;
  /** escrow token account for this game */
  gameAccountTaAccount: Address<TAccountGameAccountTaAccount>;
  gameMaker: TransactionSigner<TAccountGameMaker>;
  gambaState: Address<TAccountGambaState>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  preAllocPlayers: CreateGameSplInstructionDataArgs['preAllocPlayers'];
  maxPlayers: CreateGameSplInstructionDataArgs['maxPlayers'];
  numTeams: CreateGameSplInstructionDataArgs['numTeams'];
  winnersTarget: CreateGameSplInstructionDataArgs['winnersTarget'];
  wagerType: CreateGameSplInstructionDataArgs['wagerType'];
  payoutType: CreateGameSplInstructionDataArgs['payoutType'];
  wager: CreateGameSplInstructionDataArgs['wager'];
  softDuration: CreateGameSplInstructionDataArgs['softDuration'];
  hardDuration: CreateGameSplInstructionDataArgs['hardDuration'];
  gameSeed: CreateGameSplInstructionDataArgs['gameSeed'];
  minBet: CreateGameSplInstructionDataArgs['minBet'];
  maxBet: CreateGameSplInstructionDataArgs['maxBet'];
};

export function getCreateGameSplInstruction<
  TAccountGameAccount extends string,
  TAccountMetadataAccount extends string,
  TAccountMint extends string,
  TAccountGameAccountTaAccount extends string,
  TAccountGameMaker extends string,
  TAccountGambaState extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: CreateGameSplInput<
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountMint,
    TAccountGameAccountTaAccount,
    TAccountGameMaker,
    TAccountGambaState,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CreateGameSplInstruction<
  TProgramAddress,
  TAccountGameAccount,
  TAccountMetadataAccount,
  TAccountMint,
  TAccountGameAccountTaAccount,
  TAccountGameMaker,
  TAccountGambaState,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    gameAccountTaAccount: {
      value: input.gameAccountTaAccount ?? null,
      isWritable: true,
    },
    gameMaker: { value: input.gameMaker ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.gameAccountTaAccount),
      getAccountMeta(accounts.gameMaker),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
    ],
    programAddress,
    data: getCreateGameSplInstructionDataEncoder().encode(
      args as CreateGameSplInstructionDataArgs
    ),
  } as CreateGameSplInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountMint,
    TAccountGameAccountTaAccount,
    TAccountGameMaker,
    TAccountGambaState,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >;

  return instruction;
}

export type ParsedCreateGameSplInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The on-chain Game account, PDA = [b"GAME", game_seed]. */
    gameAccount: TAccountMetas[0];
    /** Always-present metadata PDA, PDA = [b"METADATA", game_account.key()] */
    metadataAccount: TAccountMetas[1];
    /** the SPL mint for wagers */
    mint: TAccountMetas[2];
    /** escrow token account for this game */
    gameAccountTaAccount: TAccountMetas[3];
    gameMaker: TAccountMetas[4];
    gambaState: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
    associatedTokenProgram: TAccountMetas[8];
  };
  data: CreateGameSplInstructionData;
};

export function parseCreateGameSplInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreateGameSplInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      gameAccount: getNextAccount(),
      metadataAccount: getNextAccount(),
      mint: getNextAccount(),
      gameAccountTaAccount: getNextAccount(),
      gameMaker: getNextAccount(),
      gambaState: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
    },
    data: getCreateGameSplInstructionDataDecoder().decode(instruction.data),
  };
}
