/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MULTIPLAYER_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const CREATE_GAME_NATIVE_DISCRIMINATOR = new Uint8Array([
  14, 237, 122, 202, 102, 88, 48, 75,
]);

export function getCreateGameNativeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_GAME_NATIVE_DISCRIMINATOR
  );
}

export type CreateGameNativeInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountGameAccount extends string | AccountMeta<string> = string,
  TAccountMetadataAccount extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountGameMaker extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGameAccount extends string
        ? WritableAccount<TAccountGameAccount>
        : TAccountGameAccount,
      TAccountMetadataAccount extends string
        ? WritableAccount<TAccountMetadataAccount>
        : TAccountMetadataAccount,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountGameMaker extends string
        ? WritableSignerAccount<TAccountGameMaker> &
            AccountSignerMeta<TAccountGameMaker>
        : TAccountGameMaker,
      TAccountGambaState extends string
        ? WritableAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateGameNativeInstructionData = {
  discriminator: ReadonlyUint8Array;
  preAllocPlayers: number;
  maxPlayers: number;
  numTeams: number;
  winnersTarget: number;
  wagerType: number;
  payoutType: number;
  wager: bigint;
  softDuration: bigint;
  hardDuration: bigint;
  gameSeed: bigint;
  minBet: bigint;
  maxBet: bigint;
};

export type CreateGameNativeInstructionDataArgs = {
  preAllocPlayers: number;
  maxPlayers: number;
  numTeams: number;
  winnersTarget: number;
  wagerType: number;
  payoutType: number;
  wager: number | bigint;
  softDuration: number | bigint;
  hardDuration: number | bigint;
  gameSeed: number | bigint;
  minBet: number | bigint;
  maxBet: number | bigint;
};

export function getCreateGameNativeInstructionDataEncoder(): FixedSizeEncoder<CreateGameNativeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['preAllocPlayers', getU16Encoder()],
      ['maxPlayers', getU16Encoder()],
      ['numTeams', getU8Encoder()],
      ['winnersTarget', getU16Encoder()],
      ['wagerType', getU8Encoder()],
      ['payoutType', getU8Encoder()],
      ['wager', getU64Encoder()],
      ['softDuration', getI64Encoder()],
      ['hardDuration', getI64Encoder()],
      ['gameSeed', getU64Encoder()],
      ['minBet', getU64Encoder()],
      ['maxBet', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_GAME_NATIVE_DISCRIMINATOR })
  );
}

export function getCreateGameNativeInstructionDataDecoder(): FixedSizeDecoder<CreateGameNativeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['preAllocPlayers', getU16Decoder()],
    ['maxPlayers', getU16Decoder()],
    ['numTeams', getU8Decoder()],
    ['winnersTarget', getU16Decoder()],
    ['wagerType', getU8Decoder()],
    ['payoutType', getU8Decoder()],
    ['wager', getU64Decoder()],
    ['softDuration', getI64Decoder()],
    ['hardDuration', getI64Decoder()],
    ['gameSeed', getU64Decoder()],
    ['minBet', getU64Decoder()],
    ['maxBet', getU64Decoder()],
  ]);
}

export function getCreateGameNativeInstructionDataCodec(): FixedSizeCodec<
  CreateGameNativeInstructionDataArgs,
  CreateGameNativeInstructionData
> {
  return combineCodec(
    getCreateGameNativeInstructionDataEncoder(),
    getCreateGameNativeInstructionDataDecoder()
  );
}

export type CreateGameNativeAsyncInput<
  TAccountGameAccount extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountMint extends string = string,
  TAccountGameMaker extends string = string,
  TAccountGambaState extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The on‐chain Game account, PDA = [b"GAME", game_seed]. */
  gameAccount?: Address<TAccountGameAccount>;
  /** Always-present metadata PDA, PDA = [b"METADATA", game_account.key()] */
  metadataAccount?: Address<TAccountMetadataAccount>;
  /** always SOL (placeholder mint) */
  mint: Address<TAccountMint>;
  /** creator of the game, pays rent on init */
  gameMaker: TransactionSigner<TAccountGameMaker>;
  /** global config PDA */
  gambaState?: Address<TAccountGambaState>;
  systemProgram?: Address<TAccountSystemProgram>;
  preAllocPlayers: CreateGameNativeInstructionDataArgs['preAllocPlayers'];
  maxPlayers: CreateGameNativeInstructionDataArgs['maxPlayers'];
  numTeams: CreateGameNativeInstructionDataArgs['numTeams'];
  winnersTarget: CreateGameNativeInstructionDataArgs['winnersTarget'];
  wagerType: CreateGameNativeInstructionDataArgs['wagerType'];
  payoutType: CreateGameNativeInstructionDataArgs['payoutType'];
  wager: CreateGameNativeInstructionDataArgs['wager'];
  softDuration: CreateGameNativeInstructionDataArgs['softDuration'];
  hardDuration: CreateGameNativeInstructionDataArgs['hardDuration'];
  gameSeed: CreateGameNativeInstructionDataArgs['gameSeed'];
  minBet: CreateGameNativeInstructionDataArgs['minBet'];
  maxBet: CreateGameNativeInstructionDataArgs['maxBet'];
};

export async function getCreateGameNativeInstructionAsync<
  TAccountGameAccount extends string,
  TAccountMetadataAccount extends string,
  TAccountMint extends string,
  TAccountGameMaker extends string,
  TAccountGambaState extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: CreateGameNativeAsyncInput<
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountMint,
    TAccountGameMaker,
    TAccountGambaState,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CreateGameNativeInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountMint,
    TAccountGameMaker,
    TAccountGambaState,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    gameMaker: { value: input.gameMaker ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.gameAccount.value) {
    accounts.gameAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([71, 65, 77, 69])),
        getU64Encoder().encode(expectSome(args.gameSeed)),
      ],
    });
  }
  if (!accounts.metadataAccount.value) {
    accounts.metadataAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([77, 69, 84, 65, 68, 65, 84, 65])
        ),
        getAddressEncoder().encode(expectAddress(accounts.gameAccount.value)),
      ],
    });
  }
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69])
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.gameMaker),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getCreateGameNativeInstructionDataEncoder().encode(
      args as CreateGameNativeInstructionDataArgs
    ),
  } as CreateGameNativeInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountMint,
    TAccountGameMaker,
    TAccountGambaState,
    TAccountSystemProgram
  >;

  return instruction;
}

export type CreateGameNativeInput<
  TAccountGameAccount extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountMint extends string = string,
  TAccountGameMaker extends string = string,
  TAccountGambaState extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** The on‐chain Game account, PDA = [b"GAME", game_seed]. */
  gameAccount: Address<TAccountGameAccount>;
  /** Always-present metadata PDA, PDA = [b"METADATA", game_account.key()] */
  metadataAccount: Address<TAccountMetadataAccount>;
  /** always SOL (placeholder mint) */
  mint: Address<TAccountMint>;
  /** creator of the game, pays rent on init */
  gameMaker: TransactionSigner<TAccountGameMaker>;
  /** global config PDA */
  gambaState: Address<TAccountGambaState>;
  systemProgram?: Address<TAccountSystemProgram>;
  preAllocPlayers: CreateGameNativeInstructionDataArgs['preAllocPlayers'];
  maxPlayers: CreateGameNativeInstructionDataArgs['maxPlayers'];
  numTeams: CreateGameNativeInstructionDataArgs['numTeams'];
  winnersTarget: CreateGameNativeInstructionDataArgs['winnersTarget'];
  wagerType: CreateGameNativeInstructionDataArgs['wagerType'];
  payoutType: CreateGameNativeInstructionDataArgs['payoutType'];
  wager: CreateGameNativeInstructionDataArgs['wager'];
  softDuration: CreateGameNativeInstructionDataArgs['softDuration'];
  hardDuration: CreateGameNativeInstructionDataArgs['hardDuration'];
  gameSeed: CreateGameNativeInstructionDataArgs['gameSeed'];
  minBet: CreateGameNativeInstructionDataArgs['minBet'];
  maxBet: CreateGameNativeInstructionDataArgs['maxBet'];
};

export function getCreateGameNativeInstruction<
  TAccountGameAccount extends string,
  TAccountMetadataAccount extends string,
  TAccountMint extends string,
  TAccountGameMaker extends string,
  TAccountGambaState extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: CreateGameNativeInput<
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountMint,
    TAccountGameMaker,
    TAccountGambaState,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CreateGameNativeInstruction<
  TProgramAddress,
  TAccountGameAccount,
  TAccountMetadataAccount,
  TAccountMint,
  TAccountGameMaker,
  TAccountGambaState,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    gameMaker: { value: input.gameMaker ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.gameMaker),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getCreateGameNativeInstructionDataEncoder().encode(
      args as CreateGameNativeInstructionDataArgs
    ),
  } as CreateGameNativeInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountMint,
    TAccountGameMaker,
    TAccountGambaState,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedCreateGameNativeInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The on‐chain Game account, PDA = [b"GAME", game_seed]. */
    gameAccount: TAccountMetas[0];
    /** Always-present metadata PDA, PDA = [b"METADATA", game_account.key()] */
    metadataAccount: TAccountMetas[1];
    /** always SOL (placeholder mint) */
    mint: TAccountMetas[2];
    /** creator of the game, pays rent on init */
    gameMaker: TAccountMetas[3];
    /** global config PDA */
    gambaState: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: CreateGameNativeInstructionData;
};

export function parseCreateGameNativeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreateGameNativeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      gameAccount: getNextAccount(),
      metadataAccount: getNextAccount(),
      mint: getNextAccount(),
      gameMaker: getNextAccount(),
      gambaState: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateGameNativeInstructionDataDecoder().decode(instruction.data),
  };
}
