/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MULTIPLAYER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const GAMBA_CONFIG_DISCRIMINATOR = new Uint8Array([
  232, 208, 249, 92, 159, 187, 21, 254,
]);

export function getGambaConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GAMBA_CONFIG_DISCRIMINATOR
  );
}

export type GambaConfigInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGambaState extends string
        ? WritableAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type GambaConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  feeVault: Address;
  feeBps: number;
  rng: Address;
  authority: Address;
};

export type GambaConfigInstructionDataArgs = {
  feeVault: Address;
  feeBps: number;
  rng: Address;
  authority: Address;
};

export function getGambaConfigInstructionDataEncoder(): FixedSizeEncoder<GambaConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['feeVault', getAddressEncoder()],
      ['feeBps', getU32Encoder()],
      ['rng', getAddressEncoder()],
      ['authority', getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: GAMBA_CONFIG_DISCRIMINATOR })
  );
}

export function getGambaConfigInstructionDataDecoder(): FixedSizeDecoder<GambaConfigInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['feeVault', getAddressDecoder()],
    ['feeBps', getU32Decoder()],
    ['rng', getAddressDecoder()],
    ['authority', getAddressDecoder()],
  ]);
}

export function getGambaConfigInstructionDataCodec(): FixedSizeCodec<
  GambaConfigInstructionDataArgs,
  GambaConfigInstructionData
> {
  return combineCodec(
    getGambaConfigInstructionDataEncoder(),
    getGambaConfigInstructionDataDecoder()
  );
}

export type GambaConfigAsyncInput<
  TAccountGambaState extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  gambaState?: Address<TAccountGambaState>;
  authority: TransactionSigner<TAccountAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  feeVault: GambaConfigInstructionDataArgs['feeVault'];
  feeBps: GambaConfigInstructionDataArgs['feeBps'];
  rng: GambaConfigInstructionDataArgs['rng'];
  authorityArg: GambaConfigInstructionDataArgs['authority'];
};

export async function getGambaConfigInstructionAsync<
  TAccountGambaState extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: GambaConfigAsyncInput<
    TAccountGambaState,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  GambaConfigInstruction<
    TProgramAddress,
    TAccountGambaState,
    TAccountAuthority,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input, authority: input.authorityArg };

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69])
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getGambaConfigInstructionDataEncoder().encode(
      args as GambaConfigInstructionDataArgs
    ),
  } as GambaConfigInstruction<
    TProgramAddress,
    TAccountGambaState,
    TAccountAuthority,
    TAccountSystemProgram
  >;

  return instruction;
}

export type GambaConfigInput<
  TAccountGambaState extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  gambaState: Address<TAccountGambaState>;
  authority: TransactionSigner<TAccountAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  feeVault: GambaConfigInstructionDataArgs['feeVault'];
  feeBps: GambaConfigInstructionDataArgs['feeBps'];
  rng: GambaConfigInstructionDataArgs['rng'];
  authorityArg: GambaConfigInstructionDataArgs['authority'];
};

export function getGambaConfigInstruction<
  TAccountGambaState extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: GambaConfigInput<
    TAccountGambaState,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): GambaConfigInstruction<
  TProgramAddress,
  TAccountGambaState,
  TAccountAuthority,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input, authority: input.authorityArg };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getGambaConfigInstructionDataEncoder().encode(
      args as GambaConfigInstructionDataArgs
    ),
  } as GambaConfigInstruction<
    TProgramAddress,
    TAccountGambaState,
    TAccountAuthority,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedGambaConfigInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    gambaState: TAccountMetas[0];
    authority: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: GambaConfigInstructionData;
};

export function parseGambaConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedGambaConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      gambaState: getNextAccount(),
      authority: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getGambaConfigInstructionDataDecoder().decode(instruction.data),
  };
}
