/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

export * from './createGameNative';
export * from './createGameSpl';
export * from './distributeNative';
export * from './distributeSpl';
export * from './gambaConfig';
export * from './joinGame';
export * from './leaveGame';
export * from './selectWinners';
