/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  getCreatorPendingDecoder,
  getCreatorPendingEncoder,
  getGameStateDecoder,
  getGameStateEncoder,
  getGameTypeDecoder,
  getGameTypeEncoder,
  getPayoutTypeDecoder,
  getPayoutTypeEncoder,
  getPlayerDecoder,
  getPlayerEncoder,
  getWagerTypeDecoder,
  getWagerTypeEncoder,
  type CreatorPending,
  type CreatorPendingArgs,
  type GameState,
  type GameStateArgs,
  type GameType,
  type GameTypeArgs,
  type PayoutType,
  type PayoutTypeArgs,
  type Player,
  type PlayerArgs,
  type WagerType,
  type WagerTypeArgs,
} from '../types';

export const GAME_DISCRIMINATOR = new Uint8Array([
  27, 90, 166, 125, 74, 100, 121, 18,
]);

export function getGameDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(GAME_DISCRIMINATOR);
}

export type Game = {
  discriminator: ReadonlyUint8Array;
  gameMaker: Address;
  mint: Address;
  gameType: GameType;
  wagerType: WagerType;
  payoutType: PayoutType;
  maxPlayers: number;
  preAlloc: number;
  numTeams: number;
  winnersTarget: number;
  wager: bigint;
  softExpirationTimestamp: bigint;
  hardExpirationTimestamp: bigint;
  /** New field: when the game was created (unix timestamp) */
  creationTimestamp: bigint;
  state: GameState;
  pendingGambaFee: bigint;
  gameId: bigint;
  /** Seeds randomness for select_winners */
  gameSeed: bigint;
  minBet: bigint;
  maxBet: bigint;
  bump: number;
  players: Array<Player>;
  winnerIndexes: Array<number>;
  creatorsPending: Array<CreatorPending>;
};

export type GameArgs = {
  gameMaker: Address;
  mint: Address;
  gameType: GameTypeArgs;
  wagerType: WagerTypeArgs;
  payoutType: PayoutTypeArgs;
  maxPlayers: number;
  preAlloc: number;
  numTeams: number;
  winnersTarget: number;
  wager: number | bigint;
  softExpirationTimestamp: number | bigint;
  hardExpirationTimestamp: number | bigint;
  /** New field: when the game was created (unix timestamp) */
  creationTimestamp: number | bigint;
  state: GameStateArgs;
  pendingGambaFee: number | bigint;
  gameId: number | bigint;
  /** Seeds randomness for select_winners */
  gameSeed: number | bigint;
  minBet: number | bigint;
  maxBet: number | bigint;
  bump: number;
  players: Array<PlayerArgs>;
  winnerIndexes: Array<number>;
  creatorsPending: Array<CreatorPendingArgs>;
};

export function getGameEncoder(): Encoder<GameArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['gameMaker', getAddressEncoder()],
      ['mint', getAddressEncoder()],
      ['gameType', getGameTypeEncoder()],
      ['wagerType', getWagerTypeEncoder()],
      ['payoutType', getPayoutTypeEncoder()],
      ['maxPlayers', getU16Encoder()],
      ['preAlloc', getU16Encoder()],
      ['numTeams', getU8Encoder()],
      ['winnersTarget', getU16Encoder()],
      ['wager', getU64Encoder()],
      ['softExpirationTimestamp', getI64Encoder()],
      ['hardExpirationTimestamp', getI64Encoder()],
      ['creationTimestamp', getI64Encoder()],
      ['state', getGameStateEncoder()],
      ['pendingGambaFee', getU64Encoder()],
      ['gameId', getU64Encoder()],
      ['gameSeed', getU64Encoder()],
      ['minBet', getU64Encoder()],
      ['maxBet', getU64Encoder()],
      ['bump', getU8Encoder()],
      ['players', getArrayEncoder(getPlayerEncoder())],
      ['winnerIndexes', getArrayEncoder(getU16Encoder())],
      ['creatorsPending', getArrayEncoder(getCreatorPendingEncoder())],
    ]),
    (value) => ({ ...value, discriminator: GAME_DISCRIMINATOR })
  );
}

export function getGameDecoder(): Decoder<Game> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['gameMaker', getAddressDecoder()],
    ['mint', getAddressDecoder()],
    ['gameType', getGameTypeDecoder()],
    ['wagerType', getWagerTypeDecoder()],
    ['payoutType', getPayoutTypeDecoder()],
    ['maxPlayers', getU16Decoder()],
    ['preAlloc', getU16Decoder()],
    ['numTeams', getU8Decoder()],
    ['winnersTarget', getU16Decoder()],
    ['wager', getU64Decoder()],
    ['softExpirationTimestamp', getI64Decoder()],
    ['hardExpirationTimestamp', getI64Decoder()],
    ['creationTimestamp', getI64Decoder()],
    ['state', getGameStateDecoder()],
    ['pendingGambaFee', getU64Decoder()],
    ['gameId', getU64Decoder()],
    ['gameSeed', getU64Decoder()],
    ['minBet', getU64Decoder()],
    ['maxBet', getU64Decoder()],
    ['bump', getU8Decoder()],
    ['players', getArrayDecoder(getPlayerDecoder())],
    ['winnerIndexes', getArrayDecoder(getU16Decoder())],
    ['creatorsPending', getArrayDecoder(getCreatorPendingDecoder())],
  ]);
}

export function getGameCodec(): Codec<GameArgs, Game> {
  return combineCodec(getGameEncoder(), getGameDecoder());
}

export function decodeGame<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Game, TAddress>;
export function decodeGame<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Game, TAddress>;
export function decodeGame<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Game, TAddress> | MaybeAccount<Game, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getGameDecoder()
  );
}

export async function fetchGame<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Game, TAddress>> {
  const maybeAccount = await fetchMaybeGame(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeGame<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Game, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeGame(maybeAccount);
}

export async function fetchAllGame(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Game>[]> {
  const maybeAccounts = await fetchAllMaybeGame(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeGame(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Game>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeGame(maybeAccount));
}
