/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MULTIPLAYER_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const DISTRIBUTE_SPL_DISCRIMINATOR = new Uint8Array([
  93, 24, 158, 238, 198, 173, 215, 228,
]);

export function getDistributeSplDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DISTRIBUTE_SPL_DISCRIMINATOR
  );
}

export type DistributeSplInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountGameAccount extends string | AccountMeta<string> = string,
  TAccountMetadataAccount extends string | AccountMeta<string> = string,
  TAccountGameAccountTa extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountGambaFeeAta extends string | AccountMeta<string> = string,
  TAccountGambaFeeAddress extends string | AccountMeta<string> = string,
  TAccountGameMaker extends string | AccountMeta<string> = string,
  TAccountCreatorAta0 extends string | AccountMeta<string> = string,
  TAccountCreatorAta1 extends string | AccountMeta<string> = string,
  TAccountCreatorAta2 extends string | AccountMeta<string> = string,
  TAccountCreatorAta3 extends string | AccountMeta<string> = string,
  TAccountCreatorAta4 extends string | AccountMeta<string> = string,
  TAccountWinnerAta0 extends string | AccountMeta<string> = string,
  TAccountWinnerAta1 extends string | AccountMeta<string> = string,
  TAccountWinnerAta2 extends string | AccountMeta<string> = string,
  TAccountWinnerAta3 extends string | AccountMeta<string> = string,
  TAccountWinnerAta4 extends string | AccountMeta<string> = string,
  TAccountWinnerAta5 extends string | AccountMeta<string> = string,
  TAccountWinnerAta6 extends string | AccountMeta<string> = string,
  TAccountWinnerAta7 extends string | AccountMeta<string> = string,
  TAccountWinnerAta8 extends string | AccountMeta<string> = string,
  TAccountWinnerAta9 extends string | AccountMeta<string> = string,
  TAccountWinnerAta10 extends string | AccountMeta<string> = string,
  TAccountWinnerAta11 extends string | AccountMeta<string> = string,
  TAccountWinnerAta12 extends string | AccountMeta<string> = string,
  TAccountWinnerAta13 extends string | AccountMeta<string> = string,
  TAccountWinnerAta14 extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends
    | string
    | AccountMeta<string> = 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountGambaState extends string
        ? ReadonlyAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountGameAccount extends string
        ? WritableAccount<TAccountGameAccount>
        : TAccountGameAccount,
      TAccountMetadataAccount extends string
        ? WritableAccount<TAccountMetadataAccount>
        : TAccountMetadataAccount,
      TAccountGameAccountTa extends string
        ? WritableAccount<TAccountGameAccountTa>
        : TAccountGameAccountTa,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountGambaFeeAta extends string
        ? WritableAccount<TAccountGambaFeeAta>
        : TAccountGambaFeeAta,
      TAccountGambaFeeAddress extends string
        ? WritableAccount<TAccountGambaFeeAddress>
        : TAccountGambaFeeAddress,
      TAccountGameMaker extends string
        ? WritableAccount<TAccountGameMaker>
        : TAccountGameMaker,
      TAccountCreatorAta0 extends string
        ? WritableAccount<TAccountCreatorAta0>
        : TAccountCreatorAta0,
      TAccountCreatorAta1 extends string
        ? WritableAccount<TAccountCreatorAta1>
        : TAccountCreatorAta1,
      TAccountCreatorAta2 extends string
        ? WritableAccount<TAccountCreatorAta2>
        : TAccountCreatorAta2,
      TAccountCreatorAta3 extends string
        ? WritableAccount<TAccountCreatorAta3>
        : TAccountCreatorAta3,
      TAccountCreatorAta4 extends string
        ? WritableAccount<TAccountCreatorAta4>
        : TAccountCreatorAta4,
      TAccountWinnerAta0 extends string
        ? WritableAccount<TAccountWinnerAta0>
        : TAccountWinnerAta0,
      TAccountWinnerAta1 extends string
        ? WritableAccount<TAccountWinnerAta1>
        : TAccountWinnerAta1,
      TAccountWinnerAta2 extends string
        ? WritableAccount<TAccountWinnerAta2>
        : TAccountWinnerAta2,
      TAccountWinnerAta3 extends string
        ? WritableAccount<TAccountWinnerAta3>
        : TAccountWinnerAta3,
      TAccountWinnerAta4 extends string
        ? WritableAccount<TAccountWinnerAta4>
        : TAccountWinnerAta4,
      TAccountWinnerAta5 extends string
        ? WritableAccount<TAccountWinnerAta5>
        : TAccountWinnerAta5,
      TAccountWinnerAta6 extends string
        ? WritableAccount<TAccountWinnerAta6>
        : TAccountWinnerAta6,
      TAccountWinnerAta7 extends string
        ? WritableAccount<TAccountWinnerAta7>
        : TAccountWinnerAta7,
      TAccountWinnerAta8 extends string
        ? WritableAccount<TAccountWinnerAta8>
        : TAccountWinnerAta8,
      TAccountWinnerAta9 extends string
        ? WritableAccount<TAccountWinnerAta9>
        : TAccountWinnerAta9,
      TAccountWinnerAta10 extends string
        ? WritableAccount<TAccountWinnerAta10>
        : TAccountWinnerAta10,
      TAccountWinnerAta11 extends string
        ? WritableAccount<TAccountWinnerAta11>
        : TAccountWinnerAta11,
      TAccountWinnerAta12 extends string
        ? WritableAccount<TAccountWinnerAta12>
        : TAccountWinnerAta12,
      TAccountWinnerAta13 extends string
        ? WritableAccount<TAccountWinnerAta13>
        : TAccountWinnerAta13,
      TAccountWinnerAta14 extends string
        ? WritableAccount<TAccountWinnerAta14>
        : TAccountWinnerAta14,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DistributeSplInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type DistributeSplInstructionDataArgs = {};

export function getDistributeSplInstructionDataEncoder(): FixedSizeEncoder<DistributeSplInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: DISTRIBUTE_SPL_DISCRIMINATOR })
  );
}

export function getDistributeSplInstructionDataDecoder(): FixedSizeDecoder<DistributeSplInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getDistributeSplInstructionDataCodec(): FixedSizeCodec<
  DistributeSplInstructionDataArgs,
  DistributeSplInstructionData
> {
  return combineCodec(
    getDistributeSplInstructionDataEncoder(),
    getDistributeSplInstructionDataDecoder()
  );
}

export type DistributeSplAsyncInput<
  TAccountPayer extends string = string,
  TAccountGambaState extends string = string,
  TAccountGameAccount extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountGameAccountTa extends string = string,
  TAccountMint extends string = string,
  TAccountGambaFeeAta extends string = string,
  TAccountGambaFeeAddress extends string = string,
  TAccountGameMaker extends string = string,
  TAccountCreatorAta0 extends string = string,
  TAccountCreatorAta1 extends string = string,
  TAccountCreatorAta2 extends string = string,
  TAccountCreatorAta3 extends string = string,
  TAccountCreatorAta4 extends string = string,
  TAccountWinnerAta0 extends string = string,
  TAccountWinnerAta1 extends string = string,
  TAccountWinnerAta2 extends string = string,
  TAccountWinnerAta3 extends string = string,
  TAccountWinnerAta4 extends string = string,
  TAccountWinnerAta5 extends string = string,
  TAccountWinnerAta6 extends string = string,
  TAccountWinnerAta7 extends string = string,
  TAccountWinnerAta8 extends string = string,
  TAccountWinnerAta9 extends string = string,
  TAccountWinnerAta10 extends string = string,
  TAccountWinnerAta11 extends string = string,
  TAccountWinnerAta12 extends string = string,
  TAccountWinnerAta13 extends string = string,
  TAccountWinnerAta14 extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  gambaState?: Address<TAccountGambaState>;
  /** Raw Game PDA (parsed by offsets) */
  gameAccount: Address<TAccountGameAccount>;
  /** Always-present metadata PDA (to be closed on final settlement) */
  metadataAccount?: Address<TAccountMetadataAccount>;
  /** Game escrow ATA (PDA = [game_account]) */
  gameAccountTa: Address<TAccountGameAccountTa>;
  mint: Address<TAccountMint>;
  /** Protocol fee vault ATA for this mint */
  gambaFeeAta?: Address<TAccountGambaFeeAta>;
  /** Protocol fee vault (owner of `gamba_fee_ata`) */
  gambaFeeAddress: Address<TAccountGambaFeeAddress>;
  /** Game‑maker (receives escrow close lamports) */
  gameMaker: Address<TAccountGameMaker>;
  creatorAta0?: Address<TAccountCreatorAta0>;
  creatorAta1?: Address<TAccountCreatorAta1>;
  creatorAta2?: Address<TAccountCreatorAta2>;
  creatorAta3?: Address<TAccountCreatorAta3>;
  creatorAta4?: Address<TAccountCreatorAta4>;
  winnerAta0?: Address<TAccountWinnerAta0>;
  winnerAta1?: Address<TAccountWinnerAta1>;
  winnerAta2?: Address<TAccountWinnerAta2>;
  winnerAta3?: Address<TAccountWinnerAta3>;
  winnerAta4?: Address<TAccountWinnerAta4>;
  winnerAta5?: Address<TAccountWinnerAta5>;
  winnerAta6?: Address<TAccountWinnerAta6>;
  winnerAta7?: Address<TAccountWinnerAta7>;
  winnerAta8?: Address<TAccountWinnerAta8>;
  winnerAta9?: Address<TAccountWinnerAta9>;
  winnerAta10?: Address<TAccountWinnerAta10>;
  winnerAta11?: Address<TAccountWinnerAta11>;
  winnerAta12?: Address<TAccountWinnerAta12>;
  winnerAta13?: Address<TAccountWinnerAta13>;
  winnerAta14?: Address<TAccountWinnerAta14>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getDistributeSplInstructionAsync<
  TAccountPayer extends string,
  TAccountGambaState extends string,
  TAccountGameAccount extends string,
  TAccountMetadataAccount extends string,
  TAccountGameAccountTa extends string,
  TAccountMint extends string,
  TAccountGambaFeeAta extends string,
  TAccountGambaFeeAddress extends string,
  TAccountGameMaker extends string,
  TAccountCreatorAta0 extends string,
  TAccountCreatorAta1 extends string,
  TAccountCreatorAta2 extends string,
  TAccountCreatorAta3 extends string,
  TAccountCreatorAta4 extends string,
  TAccountWinnerAta0 extends string,
  TAccountWinnerAta1 extends string,
  TAccountWinnerAta2 extends string,
  TAccountWinnerAta3 extends string,
  TAccountWinnerAta4 extends string,
  TAccountWinnerAta5 extends string,
  TAccountWinnerAta6 extends string,
  TAccountWinnerAta7 extends string,
  TAccountWinnerAta8 extends string,
  TAccountWinnerAta9 extends string,
  TAccountWinnerAta10 extends string,
  TAccountWinnerAta11 extends string,
  TAccountWinnerAta12 extends string,
  TAccountWinnerAta13 extends string,
  TAccountWinnerAta14 extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: DistributeSplAsyncInput<
    TAccountPayer,
    TAccountGambaState,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountGameAccountTa,
    TAccountMint,
    TAccountGambaFeeAta,
    TAccountGambaFeeAddress,
    TAccountGameMaker,
    TAccountCreatorAta0,
    TAccountCreatorAta1,
    TAccountCreatorAta2,
    TAccountCreatorAta3,
    TAccountCreatorAta4,
    TAccountWinnerAta0,
    TAccountWinnerAta1,
    TAccountWinnerAta2,
    TAccountWinnerAta3,
    TAccountWinnerAta4,
    TAccountWinnerAta5,
    TAccountWinnerAta6,
    TAccountWinnerAta7,
    TAccountWinnerAta8,
    TAccountWinnerAta9,
    TAccountWinnerAta10,
    TAccountWinnerAta11,
    TAccountWinnerAta12,
    TAccountWinnerAta13,
    TAccountWinnerAta14,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  DistributeSplInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountGambaState,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountGameAccountTa,
    TAccountMint,
    TAccountGambaFeeAta,
    TAccountGambaFeeAddress,
    TAccountGameMaker,
    TAccountCreatorAta0,
    TAccountCreatorAta1,
    TAccountCreatorAta2,
    TAccountCreatorAta3,
    TAccountCreatorAta4,
    TAccountWinnerAta0,
    TAccountWinnerAta1,
    TAccountWinnerAta2,
    TAccountWinnerAta3,
    TAccountWinnerAta4,
    TAccountWinnerAta5,
    TAccountWinnerAta6,
    TAccountWinnerAta7,
    TAccountWinnerAta8,
    TAccountWinnerAta9,
    TAccountWinnerAta10,
    TAccountWinnerAta11,
    TAccountWinnerAta12,
    TAccountWinnerAta13,
    TAccountWinnerAta14,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    gameAccountTa: { value: input.gameAccountTa ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    gambaFeeAta: { value: input.gambaFeeAta ?? null, isWritable: true },
    gambaFeeAddress: { value: input.gambaFeeAddress ?? null, isWritable: true },
    gameMaker: { value: input.gameMaker ?? null, isWritable: true },
    creatorAta0: { value: input.creatorAta0 ?? null, isWritable: true },
    creatorAta1: { value: input.creatorAta1 ?? null, isWritable: true },
    creatorAta2: { value: input.creatorAta2 ?? null, isWritable: true },
    creatorAta3: { value: input.creatorAta3 ?? null, isWritable: true },
    creatorAta4: { value: input.creatorAta4 ?? null, isWritable: true },
    winnerAta0: { value: input.winnerAta0 ?? null, isWritable: true },
    winnerAta1: { value: input.winnerAta1 ?? null, isWritable: true },
    winnerAta2: { value: input.winnerAta2 ?? null, isWritable: true },
    winnerAta3: { value: input.winnerAta3 ?? null, isWritable: true },
    winnerAta4: { value: input.winnerAta4 ?? null, isWritable: true },
    winnerAta5: { value: input.winnerAta5 ?? null, isWritable: true },
    winnerAta6: { value: input.winnerAta6 ?? null, isWritable: true },
    winnerAta7: { value: input.winnerAta7 ?? null, isWritable: true },
    winnerAta8: { value: input.winnerAta8 ?? null, isWritable: true },
    winnerAta9: { value: input.winnerAta9 ?? null, isWritable: true },
    winnerAta10: { value: input.winnerAta10 ?? null, isWritable: true },
    winnerAta11: { value: input.winnerAta11 ?? null, isWritable: true },
    winnerAta12: { value: input.winnerAta12 ?? null, isWritable: true },
    winnerAta13: { value: input.winnerAta13 ?? null, isWritable: true },
    winnerAta14: { value: input.winnerAta14 ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69])
        ),
      ],
    });
  }
  if (!accounts.metadataAccount.value) {
    accounts.metadataAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([77, 69, 84, 65, 68, 65, 84, 65])
        ),
        getAddressEncoder().encode(expectAddress(accounts.gameAccount.value)),
      ],
    });
  }
  if (!accounts.gambaFeeAta.value) {
    accounts.gambaFeeAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.gambaFeeAddress.value)
        ),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.gameAccountTa),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.gambaFeeAta),
      getAccountMeta(accounts.gambaFeeAddress),
      getAccountMeta(accounts.gameMaker),
      getAccountMeta(accounts.creatorAta0),
      getAccountMeta(accounts.creatorAta1),
      getAccountMeta(accounts.creatorAta2),
      getAccountMeta(accounts.creatorAta3),
      getAccountMeta(accounts.creatorAta4),
      getAccountMeta(accounts.winnerAta0),
      getAccountMeta(accounts.winnerAta1),
      getAccountMeta(accounts.winnerAta2),
      getAccountMeta(accounts.winnerAta3),
      getAccountMeta(accounts.winnerAta4),
      getAccountMeta(accounts.winnerAta5),
      getAccountMeta(accounts.winnerAta6),
      getAccountMeta(accounts.winnerAta7),
      getAccountMeta(accounts.winnerAta8),
      getAccountMeta(accounts.winnerAta9),
      getAccountMeta(accounts.winnerAta10),
      getAccountMeta(accounts.winnerAta11),
      getAccountMeta(accounts.winnerAta12),
      getAccountMeta(accounts.winnerAta13),
      getAccountMeta(accounts.winnerAta14),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getDistributeSplInstructionDataEncoder().encode({}),
  } as DistributeSplInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountGambaState,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountGameAccountTa,
    TAccountMint,
    TAccountGambaFeeAta,
    TAccountGambaFeeAddress,
    TAccountGameMaker,
    TAccountCreatorAta0,
    TAccountCreatorAta1,
    TAccountCreatorAta2,
    TAccountCreatorAta3,
    TAccountCreatorAta4,
    TAccountWinnerAta0,
    TAccountWinnerAta1,
    TAccountWinnerAta2,
    TAccountWinnerAta3,
    TAccountWinnerAta4,
    TAccountWinnerAta5,
    TAccountWinnerAta6,
    TAccountWinnerAta7,
    TAccountWinnerAta8,
    TAccountWinnerAta9,
    TAccountWinnerAta10,
    TAccountWinnerAta11,
    TAccountWinnerAta12,
    TAccountWinnerAta13,
    TAccountWinnerAta14,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >;

  return instruction;
}

export type DistributeSplInput<
  TAccountPayer extends string = string,
  TAccountGambaState extends string = string,
  TAccountGameAccount extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountGameAccountTa extends string = string,
  TAccountMint extends string = string,
  TAccountGambaFeeAta extends string = string,
  TAccountGambaFeeAddress extends string = string,
  TAccountGameMaker extends string = string,
  TAccountCreatorAta0 extends string = string,
  TAccountCreatorAta1 extends string = string,
  TAccountCreatorAta2 extends string = string,
  TAccountCreatorAta3 extends string = string,
  TAccountCreatorAta4 extends string = string,
  TAccountWinnerAta0 extends string = string,
  TAccountWinnerAta1 extends string = string,
  TAccountWinnerAta2 extends string = string,
  TAccountWinnerAta3 extends string = string,
  TAccountWinnerAta4 extends string = string,
  TAccountWinnerAta5 extends string = string,
  TAccountWinnerAta6 extends string = string,
  TAccountWinnerAta7 extends string = string,
  TAccountWinnerAta8 extends string = string,
  TAccountWinnerAta9 extends string = string,
  TAccountWinnerAta10 extends string = string,
  TAccountWinnerAta11 extends string = string,
  TAccountWinnerAta12 extends string = string,
  TAccountWinnerAta13 extends string = string,
  TAccountWinnerAta14 extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  gambaState: Address<TAccountGambaState>;
  /** Raw Game PDA (parsed by offsets) */
  gameAccount: Address<TAccountGameAccount>;
  /** Always-present metadata PDA (to be closed on final settlement) */
  metadataAccount: Address<TAccountMetadataAccount>;
  /** Game escrow ATA (PDA = [game_account]) */
  gameAccountTa: Address<TAccountGameAccountTa>;
  mint: Address<TAccountMint>;
  /** Protocol fee vault ATA for this mint */
  gambaFeeAta: Address<TAccountGambaFeeAta>;
  /** Protocol fee vault (owner of `gamba_fee_ata`) */
  gambaFeeAddress: Address<TAccountGambaFeeAddress>;
  /** Game‑maker (receives escrow close lamports) */
  gameMaker: Address<TAccountGameMaker>;
  creatorAta0?: Address<TAccountCreatorAta0>;
  creatorAta1?: Address<TAccountCreatorAta1>;
  creatorAta2?: Address<TAccountCreatorAta2>;
  creatorAta3?: Address<TAccountCreatorAta3>;
  creatorAta4?: Address<TAccountCreatorAta4>;
  winnerAta0?: Address<TAccountWinnerAta0>;
  winnerAta1?: Address<TAccountWinnerAta1>;
  winnerAta2?: Address<TAccountWinnerAta2>;
  winnerAta3?: Address<TAccountWinnerAta3>;
  winnerAta4?: Address<TAccountWinnerAta4>;
  winnerAta5?: Address<TAccountWinnerAta5>;
  winnerAta6?: Address<TAccountWinnerAta6>;
  winnerAta7?: Address<TAccountWinnerAta7>;
  winnerAta8?: Address<TAccountWinnerAta8>;
  winnerAta9?: Address<TAccountWinnerAta9>;
  winnerAta10?: Address<TAccountWinnerAta10>;
  winnerAta11?: Address<TAccountWinnerAta11>;
  winnerAta12?: Address<TAccountWinnerAta12>;
  winnerAta13?: Address<TAccountWinnerAta13>;
  winnerAta14?: Address<TAccountWinnerAta14>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getDistributeSplInstruction<
  TAccountPayer extends string,
  TAccountGambaState extends string,
  TAccountGameAccount extends string,
  TAccountMetadataAccount extends string,
  TAccountGameAccountTa extends string,
  TAccountMint extends string,
  TAccountGambaFeeAta extends string,
  TAccountGambaFeeAddress extends string,
  TAccountGameMaker extends string,
  TAccountCreatorAta0 extends string,
  TAccountCreatorAta1 extends string,
  TAccountCreatorAta2 extends string,
  TAccountCreatorAta3 extends string,
  TAccountCreatorAta4 extends string,
  TAccountWinnerAta0 extends string,
  TAccountWinnerAta1 extends string,
  TAccountWinnerAta2 extends string,
  TAccountWinnerAta3 extends string,
  TAccountWinnerAta4 extends string,
  TAccountWinnerAta5 extends string,
  TAccountWinnerAta6 extends string,
  TAccountWinnerAta7 extends string,
  TAccountWinnerAta8 extends string,
  TAccountWinnerAta9 extends string,
  TAccountWinnerAta10 extends string,
  TAccountWinnerAta11 extends string,
  TAccountWinnerAta12 extends string,
  TAccountWinnerAta13 extends string,
  TAccountWinnerAta14 extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: DistributeSplInput<
    TAccountPayer,
    TAccountGambaState,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountGameAccountTa,
    TAccountMint,
    TAccountGambaFeeAta,
    TAccountGambaFeeAddress,
    TAccountGameMaker,
    TAccountCreatorAta0,
    TAccountCreatorAta1,
    TAccountCreatorAta2,
    TAccountCreatorAta3,
    TAccountCreatorAta4,
    TAccountWinnerAta0,
    TAccountWinnerAta1,
    TAccountWinnerAta2,
    TAccountWinnerAta3,
    TAccountWinnerAta4,
    TAccountWinnerAta5,
    TAccountWinnerAta6,
    TAccountWinnerAta7,
    TAccountWinnerAta8,
    TAccountWinnerAta9,
    TAccountWinnerAta10,
    TAccountWinnerAta11,
    TAccountWinnerAta12,
    TAccountWinnerAta13,
    TAccountWinnerAta14,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): DistributeSplInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountGambaState,
  TAccountGameAccount,
  TAccountMetadataAccount,
  TAccountGameAccountTa,
  TAccountMint,
  TAccountGambaFeeAta,
  TAccountGambaFeeAddress,
  TAccountGameMaker,
  TAccountCreatorAta0,
  TAccountCreatorAta1,
  TAccountCreatorAta2,
  TAccountCreatorAta3,
  TAccountCreatorAta4,
  TAccountWinnerAta0,
  TAccountWinnerAta1,
  TAccountWinnerAta2,
  TAccountWinnerAta3,
  TAccountWinnerAta4,
  TAccountWinnerAta5,
  TAccountWinnerAta6,
  TAccountWinnerAta7,
  TAccountWinnerAta8,
  TAccountWinnerAta9,
  TAccountWinnerAta10,
  TAccountWinnerAta11,
  TAccountWinnerAta12,
  TAccountWinnerAta13,
  TAccountWinnerAta14,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    gameAccountTa: { value: input.gameAccountTa ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    gambaFeeAta: { value: input.gambaFeeAta ?? null, isWritable: true },
    gambaFeeAddress: { value: input.gambaFeeAddress ?? null, isWritable: true },
    gameMaker: { value: input.gameMaker ?? null, isWritable: true },
    creatorAta0: { value: input.creatorAta0 ?? null, isWritable: true },
    creatorAta1: { value: input.creatorAta1 ?? null, isWritable: true },
    creatorAta2: { value: input.creatorAta2 ?? null, isWritable: true },
    creatorAta3: { value: input.creatorAta3 ?? null, isWritable: true },
    creatorAta4: { value: input.creatorAta4 ?? null, isWritable: true },
    winnerAta0: { value: input.winnerAta0 ?? null, isWritable: true },
    winnerAta1: { value: input.winnerAta1 ?? null, isWritable: true },
    winnerAta2: { value: input.winnerAta2 ?? null, isWritable: true },
    winnerAta3: { value: input.winnerAta3 ?? null, isWritable: true },
    winnerAta4: { value: input.winnerAta4 ?? null, isWritable: true },
    winnerAta5: { value: input.winnerAta5 ?? null, isWritable: true },
    winnerAta6: { value: input.winnerAta6 ?? null, isWritable: true },
    winnerAta7: { value: input.winnerAta7 ?? null, isWritable: true },
    winnerAta8: { value: input.winnerAta8 ?? null, isWritable: true },
    winnerAta9: { value: input.winnerAta9 ?? null, isWritable: true },
    winnerAta10: { value: input.winnerAta10 ?? null, isWritable: true },
    winnerAta11: { value: input.winnerAta11 ?? null, isWritable: true },
    winnerAta12: { value: input.winnerAta12 ?? null, isWritable: true },
    winnerAta13: { value: input.winnerAta13 ?? null, isWritable: true },
    winnerAta14: { value: input.winnerAta14 ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.gameAccountTa),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.gambaFeeAta),
      getAccountMeta(accounts.gambaFeeAddress),
      getAccountMeta(accounts.gameMaker),
      getAccountMeta(accounts.creatorAta0),
      getAccountMeta(accounts.creatorAta1),
      getAccountMeta(accounts.creatorAta2),
      getAccountMeta(accounts.creatorAta3),
      getAccountMeta(accounts.creatorAta4),
      getAccountMeta(accounts.winnerAta0),
      getAccountMeta(accounts.winnerAta1),
      getAccountMeta(accounts.winnerAta2),
      getAccountMeta(accounts.winnerAta3),
      getAccountMeta(accounts.winnerAta4),
      getAccountMeta(accounts.winnerAta5),
      getAccountMeta(accounts.winnerAta6),
      getAccountMeta(accounts.winnerAta7),
      getAccountMeta(accounts.winnerAta8),
      getAccountMeta(accounts.winnerAta9),
      getAccountMeta(accounts.winnerAta10),
      getAccountMeta(accounts.winnerAta11),
      getAccountMeta(accounts.winnerAta12),
      getAccountMeta(accounts.winnerAta13),
      getAccountMeta(accounts.winnerAta14),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getDistributeSplInstructionDataEncoder().encode({}),
  } as DistributeSplInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountGambaState,
    TAccountGameAccount,
    TAccountMetadataAccount,
    TAccountGameAccountTa,
    TAccountMint,
    TAccountGambaFeeAta,
    TAccountGambaFeeAddress,
    TAccountGameMaker,
    TAccountCreatorAta0,
    TAccountCreatorAta1,
    TAccountCreatorAta2,
    TAccountCreatorAta3,
    TAccountCreatorAta4,
    TAccountWinnerAta0,
    TAccountWinnerAta1,
    TAccountWinnerAta2,
    TAccountWinnerAta3,
    TAccountWinnerAta4,
    TAccountWinnerAta5,
    TAccountWinnerAta6,
    TAccountWinnerAta7,
    TAccountWinnerAta8,
    TAccountWinnerAta9,
    TAccountWinnerAta10,
    TAccountWinnerAta11,
    TAccountWinnerAta12,
    TAccountWinnerAta13,
    TAccountWinnerAta14,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedDistributeSplInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    gambaState: TAccountMetas[1];
    /** Raw Game PDA (parsed by offsets) */
    gameAccount: TAccountMetas[2];
    /** Always-present metadata PDA (to be closed on final settlement) */
    metadataAccount: TAccountMetas[3];
    /** Game escrow ATA (PDA = [game_account]) */
    gameAccountTa: TAccountMetas[4];
    mint: TAccountMetas[5];
    /** Protocol fee vault ATA for this mint */
    gambaFeeAta: TAccountMetas[6];
    /** Protocol fee vault (owner of `gamba_fee_ata`) */
    gambaFeeAddress: TAccountMetas[7];
    /** Game‑maker (receives escrow close lamports) */
    gameMaker: TAccountMetas[8];
    creatorAta0?: TAccountMetas[9] | undefined;
    creatorAta1?: TAccountMetas[10] | undefined;
    creatorAta2?: TAccountMetas[11] | undefined;
    creatorAta3?: TAccountMetas[12] | undefined;
    creatorAta4?: TAccountMetas[13] | undefined;
    winnerAta0?: TAccountMetas[14] | undefined;
    winnerAta1?: TAccountMetas[15] | undefined;
    winnerAta2?: TAccountMetas[16] | undefined;
    winnerAta3?: TAccountMetas[17] | undefined;
    winnerAta4?: TAccountMetas[18] | undefined;
    winnerAta5?: TAccountMetas[19] | undefined;
    winnerAta6?: TAccountMetas[20] | undefined;
    winnerAta7?: TAccountMetas[21] | undefined;
    winnerAta8?: TAccountMetas[22] | undefined;
    winnerAta9?: TAccountMetas[23] | undefined;
    winnerAta10?: TAccountMetas[24] | undefined;
    winnerAta11?: TAccountMetas[25] | undefined;
    winnerAta12?: TAccountMetas[26] | undefined;
    winnerAta13?: TAccountMetas[27] | undefined;
    winnerAta14?: TAccountMetas[28] | undefined;
    tokenProgram: TAccountMetas[29];
    associatedTokenProgram: TAccountMetas[30];
    systemProgram: TAccountMetas[31];
  };
  data: DistributeSplInstructionData;
};

export function parseDistributeSplInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedDistributeSplInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 32) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === MULTIPLAYER_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      gambaState: getNextAccount(),
      gameAccount: getNextAccount(),
      metadataAccount: getNextAccount(),
      gameAccountTa: getNextAccount(),
      mint: getNextAccount(),
      gambaFeeAta: getNextAccount(),
      gambaFeeAddress: getNextAccount(),
      gameMaker: getNextAccount(),
      creatorAta0: getNextOptionalAccount(),
      creatorAta1: getNextOptionalAccount(),
      creatorAta2: getNextOptionalAccount(),
      creatorAta3: getNextOptionalAccount(),
      creatorAta4: getNextOptionalAccount(),
      winnerAta0: getNextOptionalAccount(),
      winnerAta1: getNextOptionalAccount(),
      winnerAta2: getNextOptionalAccount(),
      winnerAta3: getNextOptionalAccount(),
      winnerAta4: getNextOptionalAccount(),
      winnerAta5: getNextOptionalAccount(),
      winnerAta6: getNextOptionalAccount(),
      winnerAta7: getNextOptionalAccount(),
      winnerAta8: getNextOptionalAccount(),
      winnerAta9: getNextOptionalAccount(),
      winnerAta10: getNextOptionalAccount(),
      winnerAta11: getNextOptionalAccount(),
      winnerAta12: getNextOptionalAccount(),
      winnerAta13: getNextOptionalAccount(),
      winnerAta14: getNextOptionalAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getDistributeSplInstructionDataDecoder().decode(instruction.data),
  };
}
