/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { MULTIPLAYER_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const DISTRIBUTE_NATIVE_DISCRIMINATOR = new Uint8Array([
  32, 200, 172, 49, 57, 234, 137, 89,
]);

export function getDistributeNativeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DISTRIBUTE_NATIVE_DISCRIMINATOR
  );
}

export type DistributeNativeInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountGameAccount extends string | AccountMeta<string> = string,
  TAccountGameMaker extends string | AccountMeta<string> = string,
  TAccountGambaFeeAddress extends string | AccountMeta<string> = string,
  TAccountMetadataAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? ReadonlySignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountGambaState extends string
        ? ReadonlyAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountGameAccount extends string
        ? WritableAccount<TAccountGameAccount>
        : TAccountGameAccount,
      TAccountGameMaker extends string
        ? WritableAccount<TAccountGameMaker>
        : TAccountGameMaker,
      TAccountGambaFeeAddress extends string
        ? WritableAccount<TAccountGambaFeeAddress>
        : TAccountGambaFeeAddress,
      TAccountMetadataAccount extends string
        ? WritableAccount<TAccountMetadataAccount>
        : TAccountMetadataAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DistributeNativeInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type DistributeNativeInstructionDataArgs = {};

export function getDistributeNativeInstructionDataEncoder(): FixedSizeEncoder<DistributeNativeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: DISTRIBUTE_NATIVE_DISCRIMINATOR })
  );
}

export function getDistributeNativeInstructionDataDecoder(): FixedSizeDecoder<DistributeNativeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getDistributeNativeInstructionDataCodec(): FixedSizeCodec<
  DistributeNativeInstructionDataArgs,
  DistributeNativeInstructionData
> {
  return combineCodec(
    getDistributeNativeInstructionDataEncoder(),
    getDistributeNativeInstructionDataDecoder()
  );
}

export type DistributeNativeAsyncInput<
  TAccountPayer extends string = string,
  TAccountGambaState extends string = string,
  TAccountGameAccount extends string = string,
  TAccountGameMaker extends string = string,
  TAccountGambaFeeAddress extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Tx signer (fees & optional PDA‑close refund go here) */
  payer: TransactionSigner<TAccountPayer>;
  /** Global configuration – for fee vault + RNG auth */
  gambaState?: Address<TAccountGambaState>;
  /** Game account (large PDA, parsed manually) */
  gameAccount: Address<TAccountGameAccount>;
  /** Game‑maker – receives any closing lamports */
  gameMaker: Address<TAccountGameMaker>;
  /** Protocol fee vault */
  gambaFeeAddress: Address<TAccountGambaFeeAddress>;
  /** Metadata PDA – to be closed at settlement */
  metadataAccount?: Address<TAccountMetadataAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getDistributeNativeInstructionAsync<
  TAccountPayer extends string,
  TAccountGambaState extends string,
  TAccountGameAccount extends string,
  TAccountGameMaker extends string,
  TAccountGambaFeeAddress extends string,
  TAccountMetadataAccount extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: DistributeNativeAsyncInput<
    TAccountPayer,
    TAccountGambaState,
    TAccountGameAccount,
    TAccountGameMaker,
    TAccountGambaFeeAddress,
    TAccountMetadataAccount,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  DistributeNativeInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountGambaState,
    TAccountGameAccount,
    TAccountGameMaker,
    TAccountGambaFeeAddress,
    TAccountMetadataAccount,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: false },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    gameMaker: { value: input.gameMaker ?? null, isWritable: true },
    gambaFeeAddress: { value: input.gambaFeeAddress ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69])
        ),
      ],
    });
  }
  if (!accounts.metadataAccount.value) {
    accounts.metadataAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([77, 69, 84, 65, 68, 65, 84, 65])
        ),
        getAddressEncoder().encode(expectAddress(accounts.gameAccount.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.gameMaker),
      getAccountMeta(accounts.gambaFeeAddress),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getDistributeNativeInstructionDataEncoder().encode({}),
  } as DistributeNativeInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountGambaState,
    TAccountGameAccount,
    TAccountGameMaker,
    TAccountGambaFeeAddress,
    TAccountMetadataAccount,
    TAccountSystemProgram
  >;

  return instruction;
}

export type DistributeNativeInput<
  TAccountPayer extends string = string,
  TAccountGambaState extends string = string,
  TAccountGameAccount extends string = string,
  TAccountGameMaker extends string = string,
  TAccountGambaFeeAddress extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Tx signer (fees & optional PDA‑close refund go here) */
  payer: TransactionSigner<TAccountPayer>;
  /** Global configuration – for fee vault + RNG auth */
  gambaState: Address<TAccountGambaState>;
  /** Game account (large PDA, parsed manually) */
  gameAccount: Address<TAccountGameAccount>;
  /** Game‑maker – receives any closing lamports */
  gameMaker: Address<TAccountGameMaker>;
  /** Protocol fee vault */
  gambaFeeAddress: Address<TAccountGambaFeeAddress>;
  /** Metadata PDA – to be closed at settlement */
  metadataAccount: Address<TAccountMetadataAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getDistributeNativeInstruction<
  TAccountPayer extends string,
  TAccountGambaState extends string,
  TAccountGameAccount extends string,
  TAccountGameMaker extends string,
  TAccountGambaFeeAddress extends string,
  TAccountMetadataAccount extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: DistributeNativeInput<
    TAccountPayer,
    TAccountGambaState,
    TAccountGameAccount,
    TAccountGameMaker,
    TAccountGambaFeeAddress,
    TAccountMetadataAccount,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): DistributeNativeInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountGambaState,
  TAccountGameAccount,
  TAccountGameMaker,
  TAccountGambaFeeAddress,
  TAccountMetadataAccount,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: false },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    gameMaker: { value: input.gameMaker ?? null, isWritable: true },
    gambaFeeAddress: { value: input.gambaFeeAddress ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.gameMaker),
      getAccountMeta(accounts.gambaFeeAddress),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getDistributeNativeInstructionDataEncoder().encode({}),
  } as DistributeNativeInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountGambaState,
    TAccountGameAccount,
    TAccountGameMaker,
    TAccountGambaFeeAddress,
    TAccountMetadataAccount,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedDistributeNativeInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Tx signer (fees & optional PDA‑close refund go here) */
    payer: TAccountMetas[0];
    /** Global configuration – for fee vault + RNG auth */
    gambaState: TAccountMetas[1];
    /** Game account (large PDA, parsed manually) */
    gameAccount: TAccountMetas[2];
    /** Game‑maker – receives any closing lamports */
    gameMaker: TAccountMetas[3];
    /** Protocol fee vault */
    gambaFeeAddress: TAccountMetas[4];
    /** Metadata PDA – to be closed at settlement */
    metadataAccount: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: DistributeNativeInstructionData;
};

export function parseDistributeNativeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedDistributeNativeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      gambaState: getNextAccount(),
      gameAccount: getNextAccount(),
      gameMaker: getNextAccount(),
      gambaFeeAddress: getNextAccount(),
      metadataAccount: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getDistributeNativeInstructionDataDecoder().decode(instruction.data),
  };
}
