/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MULTIPLAYER_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const JOIN_GAME_DISCRIMINATOR = new Uint8Array([
  107, 112, 18, 38, 56, 173, 60, 128,
]);

export function getJoinGameDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(JOIN_GAME_DISCRIMINATOR);
}

export type JoinGameInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountGameAccount extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountGameAccountTa extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountPlayerAccount extends string | AccountMeta<string> = string,
  TAccountPlayerAta extends string | AccountMeta<string> = string,
  TAccountCreatorAddress extends string | AccountMeta<string> = string,
  TAccountCreatorAta extends string | AccountMeta<string> = string,
  TAccountMetadataAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountAssociatedTokenProgram extends
    | string
    | AccountMeta<string> = 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGameAccount extends string
        ? WritableAccount<TAccountGameAccount>
        : TAccountGameAccount,
      TAccountGambaState extends string
        ? WritableAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountGameAccountTa extends string
        ? WritableAccount<TAccountGameAccountTa>
        : TAccountGameAccountTa,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountPlayerAccount extends string
        ? WritableSignerAccount<TAccountPlayerAccount> &
            AccountSignerMeta<TAccountPlayerAccount>
        : TAccountPlayerAccount,
      TAccountPlayerAta extends string
        ? WritableAccount<TAccountPlayerAta>
        : TAccountPlayerAta,
      TAccountCreatorAddress extends string
        ? ReadonlyAccount<TAccountCreatorAddress>
        : TAccountCreatorAddress,
      TAccountCreatorAta extends string
        ? WritableAccount<TAccountCreatorAta>
        : TAccountCreatorAta,
      TAccountMetadataAccount extends string
        ? WritableAccount<TAccountMetadataAccount>
        : TAccountMetadataAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type JoinGameInstructionData = {
  discriminator: ReadonlyUint8Array;
  creatorFeeBps: number;
  wager: bigint;
  team: number;
  playerMeta: ReadonlyUint8Array;
};

export type JoinGameInstructionDataArgs = {
  creatorFeeBps: number;
  wager: number | bigint;
  team: number;
  playerMeta: ReadonlyUint8Array;
};

export function getJoinGameInstructionDataEncoder(): FixedSizeEncoder<JoinGameInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['creatorFeeBps', getU32Encoder()],
      ['wager', getU64Encoder()],
      ['team', getU8Encoder()],
      ['playerMeta', fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: JOIN_GAME_DISCRIMINATOR })
  );
}

export function getJoinGameInstructionDataDecoder(): FixedSizeDecoder<JoinGameInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['creatorFeeBps', getU32Decoder()],
    ['wager', getU64Decoder()],
    ['team', getU8Decoder()],
    ['playerMeta', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getJoinGameInstructionDataCodec(): FixedSizeCodec<
  JoinGameInstructionDataArgs,
  JoinGameInstructionData
> {
  return combineCodec(
    getJoinGameInstructionDataEncoder(),
    getJoinGameInstructionDataDecoder()
  );
}

export type JoinGameAsyncInput<
  TAccountGameAccount extends string = string,
  TAccountGambaState extends string = string,
  TAccountGameAccountTa extends string = string,
  TAccountMint extends string = string,
  TAccountPlayerAccount extends string = string,
  TAccountPlayerAta extends string = string,
  TAccountCreatorAddress extends string = string,
  TAccountCreatorAta extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Game account as raw bytes */
  gameAccount: Address<TAccountGameAccount>;
  gambaState?: Address<TAccountGambaState>;
  /** Optional escrow token account (only for SPL games) */
  gameAccountTa?: Address<TAccountGameAccountTa>;
  /** Mint used for wagers (native SOL or SPL) */
  mint: Address<TAccountMint>;
  /** Player joining (payer + signer) */
  playerAccount: TransactionSigner<TAccountPlayerAccount>;
  /** Optional player ATA if SPL wager */
  playerAta?: Address<TAccountPlayerAta>;
  /** Creator/referrer collecting a fee */
  creatorAddress: Address<TAccountCreatorAddress>;
  /** Creator’s ATA (created lazily) */
  creatorAta?: Address<TAccountCreatorAta>;
  /** Always-present metadata PDA */
  metadataAccount?: Address<TAccountMetadataAccount>;
  /** Programs */
  systemProgram?: Address<TAccountSystemProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  creatorFeeBps: JoinGameInstructionDataArgs['creatorFeeBps'];
  wager: JoinGameInstructionDataArgs['wager'];
  team: JoinGameInstructionDataArgs['team'];
  playerMeta: JoinGameInstructionDataArgs['playerMeta'];
};

export async function getJoinGameInstructionAsync<
  TAccountGameAccount extends string,
  TAccountGambaState extends string,
  TAccountGameAccountTa extends string,
  TAccountMint extends string,
  TAccountPlayerAccount extends string,
  TAccountPlayerAta extends string,
  TAccountCreatorAddress extends string,
  TAccountCreatorAta extends string,
  TAccountMetadataAccount extends string,
  TAccountSystemProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: JoinGameAsyncInput<
    TAccountGameAccount,
    TAccountGambaState,
    TAccountGameAccountTa,
    TAccountMint,
    TAccountPlayerAccount,
    TAccountPlayerAta,
    TAccountCreatorAddress,
    TAccountCreatorAta,
    TAccountMetadataAccount,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  JoinGameInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountGambaState,
    TAccountGameAccountTa,
    TAccountMint,
    TAccountPlayerAccount,
    TAccountPlayerAta,
    TAccountCreatorAddress,
    TAccountCreatorAta,
    TAccountMetadataAccount,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    gameAccountTa: { value: input.gameAccountTa ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    playerAccount: { value: input.playerAccount ?? null, isWritable: true },
    playerAta: { value: input.playerAta ?? null, isWritable: true },
    creatorAddress: { value: input.creatorAddress ?? null, isWritable: false },
    creatorAta: { value: input.creatorAta ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69])
        ),
      ],
    });
  }
  if (!accounts.gameAccountTa.value) {
    accounts.gameAccountTa.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.gameAccount.value)),
      ],
    });
  }
  if (!accounts.playerAta.value) {
    accounts.playerAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.playerAccount.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.creatorAta.value) {
    accounts.creatorAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(
          expectAddress(accounts.creatorAddress.value)
        ),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.metadataAccount.value) {
    accounts.metadataAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([77, 69, 84, 65, 68, 65, 84, 65])
        ),
        getAddressEncoder().encode(expectAddress(accounts.gameAccount.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.gameAccountTa),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.playerAccount),
      getAccountMeta(accounts.playerAta),
      getAccountMeta(accounts.creatorAddress),
      getAccountMeta(accounts.creatorAta),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getJoinGameInstructionDataEncoder().encode(
      args as JoinGameInstructionDataArgs
    ),
  } as JoinGameInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountGambaState,
    TAccountGameAccountTa,
    TAccountMint,
    TAccountPlayerAccount,
    TAccountPlayerAta,
    TAccountCreatorAddress,
    TAccountCreatorAta,
    TAccountMetadataAccount,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type JoinGameInput<
  TAccountGameAccount extends string = string,
  TAccountGambaState extends string = string,
  TAccountGameAccountTa extends string = string,
  TAccountMint extends string = string,
  TAccountPlayerAccount extends string = string,
  TAccountPlayerAta extends string = string,
  TAccountCreatorAddress extends string = string,
  TAccountCreatorAta extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Game account as raw bytes */
  gameAccount: Address<TAccountGameAccount>;
  gambaState: Address<TAccountGambaState>;
  /** Optional escrow token account (only for SPL games) */
  gameAccountTa?: Address<TAccountGameAccountTa>;
  /** Mint used for wagers (native SOL or SPL) */
  mint: Address<TAccountMint>;
  /** Player joining (payer + signer) */
  playerAccount: TransactionSigner<TAccountPlayerAccount>;
  /** Optional player ATA if SPL wager */
  playerAta?: Address<TAccountPlayerAta>;
  /** Creator/referrer collecting a fee */
  creatorAddress: Address<TAccountCreatorAddress>;
  /** Creator’s ATA (created lazily) */
  creatorAta: Address<TAccountCreatorAta>;
  /** Always-present metadata PDA */
  metadataAccount: Address<TAccountMetadataAccount>;
  /** Programs */
  systemProgram?: Address<TAccountSystemProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  creatorFeeBps: JoinGameInstructionDataArgs['creatorFeeBps'];
  wager: JoinGameInstructionDataArgs['wager'];
  team: JoinGameInstructionDataArgs['team'];
  playerMeta: JoinGameInstructionDataArgs['playerMeta'];
};

export function getJoinGameInstruction<
  TAccountGameAccount extends string,
  TAccountGambaState extends string,
  TAccountGameAccountTa extends string,
  TAccountMint extends string,
  TAccountPlayerAccount extends string,
  TAccountPlayerAta extends string,
  TAccountCreatorAddress extends string,
  TAccountCreatorAta extends string,
  TAccountMetadataAccount extends string,
  TAccountSystemProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: JoinGameInput<
    TAccountGameAccount,
    TAccountGambaState,
    TAccountGameAccountTa,
    TAccountMint,
    TAccountPlayerAccount,
    TAccountPlayerAta,
    TAccountCreatorAddress,
    TAccountCreatorAta,
    TAccountMetadataAccount,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): JoinGameInstruction<
  TProgramAddress,
  TAccountGameAccount,
  TAccountGambaState,
  TAccountGameAccountTa,
  TAccountMint,
  TAccountPlayerAccount,
  TAccountPlayerAta,
  TAccountCreatorAddress,
  TAccountCreatorAta,
  TAccountMetadataAccount,
  TAccountSystemProgram,
  TAccountAssociatedTokenProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    gameAccountTa: { value: input.gameAccountTa ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    playerAccount: { value: input.playerAccount ?? null, isWritable: true },
    playerAta: { value: input.playerAta ?? null, isWritable: true },
    creatorAddress: { value: input.creatorAddress ?? null, isWritable: false },
    creatorAta: { value: input.creatorAta ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.gameAccountTa),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.playerAccount),
      getAccountMeta(accounts.playerAta),
      getAccountMeta(accounts.creatorAddress),
      getAccountMeta(accounts.creatorAta),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getJoinGameInstructionDataEncoder().encode(
      args as JoinGameInstructionDataArgs
    ),
  } as JoinGameInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountGambaState,
    TAccountGameAccountTa,
    TAccountMint,
    TAccountPlayerAccount,
    TAccountPlayerAta,
    TAccountCreatorAddress,
    TAccountCreatorAta,
    TAccountMetadataAccount,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedJoinGameInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Game account as raw bytes */
    gameAccount: TAccountMetas[0];
    gambaState: TAccountMetas[1];
    /** Optional escrow token account (only for SPL games) */
    gameAccountTa?: TAccountMetas[2] | undefined;
    /** Mint used for wagers (native SOL or SPL) */
    mint: TAccountMetas[3];
    /** Player joining (payer + signer) */
    playerAccount: TAccountMetas[4];
    /** Optional player ATA if SPL wager */
    playerAta?: TAccountMetas[5] | undefined;
    /** Creator/referrer collecting a fee */
    creatorAddress: TAccountMetas[6];
    /** Creator’s ATA (created lazily) */
    creatorAta: TAccountMetas[7];
    /** Always-present metadata PDA */
    metadataAccount: TAccountMetas[8];
    /** Programs */
    systemProgram: TAccountMetas[9];
    associatedTokenProgram: TAccountMetas[10];
    tokenProgram: TAccountMetas[11];
  };
  data: JoinGameInstructionData;
};

export function parseJoinGameInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedJoinGameInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === MULTIPLAYER_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      gameAccount: getNextAccount(),
      gambaState: getNextAccount(),
      gameAccountTa: getNextOptionalAccount(),
      mint: getNextAccount(),
      playerAccount: getNextAccount(),
      playerAta: getNextOptionalAccount(),
      creatorAddress: getNextAccount(),
      creatorAta: getNextAccount(),
      metadataAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getJoinGameInstructionDataDecoder().decode(instruction.data),
  };
}
