/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { MULTIPLAYER_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const LEAVE_GAME_DISCRIMINATOR = new Uint8Array([
  218, 226, 6, 0, 243, 34, 125, 201,
]);

export function getLeaveGameDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(LEAVE_GAME_DISCRIMINATOR);
}

export type LeaveGameInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountGameAccount extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountPlayerAccount extends string | AccountMeta<string> = string,
  TAccountPlayerAta extends string | AccountMeta<string> = string,
  TAccountGameAccountTa extends string | AccountMeta<string> = string,
  TAccountMetadataAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountAssociatedTokenProgram extends
    | string
    | AccountMeta<string> = 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGameAccount extends string
        ? WritableAccount<TAccountGameAccount>
        : TAccountGameAccount,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountPlayerAccount extends string
        ? WritableSignerAccount<TAccountPlayerAccount> &
            AccountSignerMeta<TAccountPlayerAccount>
        : TAccountPlayerAccount,
      TAccountPlayerAta extends string
        ? WritableAccount<TAccountPlayerAta>
        : TAccountPlayerAta,
      TAccountGameAccountTa extends string
        ? WritableAccount<TAccountGameAccountTa>
        : TAccountGameAccountTa,
      TAccountMetadataAccount extends string
        ? WritableAccount<TAccountMetadataAccount>
        : TAccountMetadataAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type LeaveGameInstructionData = { discriminator: ReadonlyUint8Array };

export type LeaveGameInstructionDataArgs = {};

export function getLeaveGameInstructionDataEncoder(): FixedSizeEncoder<LeaveGameInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: LEAVE_GAME_DISCRIMINATOR })
  );
}

export function getLeaveGameInstructionDataDecoder(): FixedSizeDecoder<LeaveGameInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getLeaveGameInstructionDataCodec(): FixedSizeCodec<
  LeaveGameInstructionDataArgs,
  LeaveGameInstructionData
> {
  return combineCodec(
    getLeaveGameInstructionDataEncoder(),
    getLeaveGameInstructionDataDecoder()
  );
}

export type LeaveGameAsyncInput<
  TAccountGameAccount extends string = string,
  TAccountMint extends string = string,
  TAccountPlayerAccount extends string = string,
  TAccountPlayerAta extends string = string,
  TAccountGameAccountTa extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Game PDA – parsed manually */
  gameAccount: Address<TAccountGameAccount>;
  mint: Address<TAccountMint>;
  playerAccount: TransactionSigner<TAccountPlayerAccount>;
  playerAta?: Address<TAccountPlayerAta>;
  gameAccountTa?: Address<TAccountGameAccountTa>;
  /** Always-present metadata PDA */
  metadataAccount?: Address<TAccountMetadataAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getLeaveGameInstructionAsync<
  TAccountGameAccount extends string,
  TAccountMint extends string,
  TAccountPlayerAccount extends string,
  TAccountPlayerAta extends string,
  TAccountGameAccountTa extends string,
  TAccountMetadataAccount extends string,
  TAccountSystemProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: LeaveGameAsyncInput<
    TAccountGameAccount,
    TAccountMint,
    TAccountPlayerAccount,
    TAccountPlayerAta,
    TAccountGameAccountTa,
    TAccountMetadataAccount,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  LeaveGameInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountMint,
    TAccountPlayerAccount,
    TAccountPlayerAta,
    TAccountGameAccountTa,
    TAccountMetadataAccount,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    playerAccount: { value: input.playerAccount ?? null, isWritable: true },
    playerAta: { value: input.playerAta ?? null, isWritable: true },
    gameAccountTa: { value: input.gameAccountTa ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.playerAta.value) {
    accounts.playerAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.playerAccount.value)),
        getBytesEncoder().encode(
          new Uint8Array([
            6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235,
            121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133,
            126, 255, 0, 169,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.gameAccountTa.value) {
    accounts.gameAccountTa.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.gameAccount.value)),
      ],
    });
  }
  if (!accounts.metadataAccount.value) {
    accounts.metadataAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([77, 69, 84, 65, 68, 65, 84, 65])
        ),
        getAddressEncoder().encode(expectAddress(accounts.gameAccount.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.playerAccount),
      getAccountMeta(accounts.playerAta),
      getAccountMeta(accounts.gameAccountTa),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getLeaveGameInstructionDataEncoder().encode({}),
  } as LeaveGameInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountMint,
    TAccountPlayerAccount,
    TAccountPlayerAta,
    TAccountGameAccountTa,
    TAccountMetadataAccount,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type LeaveGameInput<
  TAccountGameAccount extends string = string,
  TAccountMint extends string = string,
  TAccountPlayerAccount extends string = string,
  TAccountPlayerAta extends string = string,
  TAccountGameAccountTa extends string = string,
  TAccountMetadataAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Game PDA – parsed manually */
  gameAccount: Address<TAccountGameAccount>;
  mint: Address<TAccountMint>;
  playerAccount: TransactionSigner<TAccountPlayerAccount>;
  playerAta?: Address<TAccountPlayerAta>;
  gameAccountTa?: Address<TAccountGameAccountTa>;
  /** Always-present metadata PDA */
  metadataAccount: Address<TAccountMetadataAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getLeaveGameInstruction<
  TAccountGameAccount extends string,
  TAccountMint extends string,
  TAccountPlayerAccount extends string,
  TAccountPlayerAta extends string,
  TAccountGameAccountTa extends string,
  TAccountMetadataAccount extends string,
  TAccountSystemProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof MULTIPLAYER_PROGRAM_ADDRESS,
>(
  input: LeaveGameInput<
    TAccountGameAccount,
    TAccountMint,
    TAccountPlayerAccount,
    TAccountPlayerAta,
    TAccountGameAccountTa,
    TAccountMetadataAccount,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): LeaveGameInstruction<
  TProgramAddress,
  TAccountGameAccount,
  TAccountMint,
  TAccountPlayerAccount,
  TAccountPlayerAta,
  TAccountGameAccountTa,
  TAccountMetadataAccount,
  TAccountSystemProgram,
  TAccountAssociatedTokenProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? MULTIPLAYER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    gameAccount: { value: input.gameAccount ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    playerAccount: { value: input.playerAccount ?? null, isWritable: true },
    playerAta: { value: input.playerAta ?? null, isWritable: true },
    gameAccountTa: { value: input.gameAccountTa ?? null, isWritable: true },
    metadataAccount: { value: input.metadataAccount ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.gameAccount),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.playerAccount),
      getAccountMeta(accounts.playerAta),
      getAccountMeta(accounts.gameAccountTa),
      getAccountMeta(accounts.metadataAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getLeaveGameInstructionDataEncoder().encode({}),
  } as LeaveGameInstruction<
    TProgramAddress,
    TAccountGameAccount,
    TAccountMint,
    TAccountPlayerAccount,
    TAccountPlayerAta,
    TAccountGameAccountTa,
    TAccountMetadataAccount,
    TAccountSystemProgram,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedLeaveGameInstruction<
  TProgram extends string = typeof MULTIPLAYER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Game PDA – parsed manually */
    gameAccount: TAccountMetas[0];
    mint: TAccountMetas[1];
    playerAccount: TAccountMetas[2];
    playerAta?: TAccountMetas[3] | undefined;
    gameAccountTa?: TAccountMetas[4] | undefined;
    /** Always-present metadata PDA */
    metadataAccount: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
    associatedTokenProgram: TAccountMetas[7];
    tokenProgram: TAccountMetas[8];
  };
  data: LeaveGameInstructionData;
};

export function parseLeaveGameInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedLeaveGameInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === MULTIPLAYER_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      gameAccount: getNextAccount(),
      mint: getNextAccount(),
      playerAccount: getNextAccount(),
      playerAta: getNextOptionalAccount(),
      gameAccountTa: getNextOptionalAccount(),
      metadataAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getLeaveGameInstructionDataDecoder().decode(instruction.data),
  };
}
