/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const PLAY_GAME_DISCRIMINATOR = new Uint8Array([
  37, 88, 207, 85, 42, 144, 122, 197,
]);

export function getPlayGameDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(PLAY_GAME_DISCRIMINATOR);
}

export type PlayGameInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountUnderlyingTokenMint extends string | AccountMeta<string> = string,
  TAccountBonusTokenMint extends string | AccountMeta<string> = string,
  TAccountUserUnderlyingAta extends string | AccountMeta<string> = string,
  TAccountCreator extends string | AccountMeta<string> = string,
  TAccountCreatorAta extends string | AccountMeta<string> = string,
  TAccountPlayerAta extends string | AccountMeta<string> = string,
  TAccountPlayerBonusAta extends string | AccountMeta<string> = string,
  TAccountUserBonusAta extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountPoolJackpotTokenAccount extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      TAccountGame extends string
        ? WritableAccount<TAccountGame>
        : TAccountGame,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountUnderlyingTokenMint extends string
        ? ReadonlyAccount<TAccountUnderlyingTokenMint>
        : TAccountUnderlyingTokenMint,
      TAccountBonusTokenMint extends string
        ? ReadonlyAccount<TAccountBonusTokenMint>
        : TAccountBonusTokenMint,
      TAccountUserUnderlyingAta extends string
        ? WritableAccount<TAccountUserUnderlyingAta>
        : TAccountUserUnderlyingAta,
      TAccountCreator extends string
        ? ReadonlyAccount<TAccountCreator>
        : TAccountCreator,
      TAccountCreatorAta extends string
        ? WritableAccount<TAccountCreatorAta>
        : TAccountCreatorAta,
      TAccountPlayerAta extends string
        ? WritableAccount<TAccountPlayerAta>
        : TAccountPlayerAta,
      TAccountPlayerBonusAta extends string
        ? WritableAccount<TAccountPlayerBonusAta>
        : TAccountPlayerBonusAta,
      TAccountUserBonusAta extends string
        ? WritableAccount<TAccountUserBonusAta>
        : TAccountUserBonusAta,
      TAccountGambaState extends string
        ? WritableAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountPoolJackpotTokenAccount extends string
        ? WritableAccount<TAccountPoolJackpotTokenAccount>
        : TAccountPoolJackpotTokenAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PlayGameInstructionData = {
  discriminator: ReadonlyUint8Array;
  wager: bigint;
  bet: Array<number>;
  clientSeed: string;
  creatorFeeBps: number;
  jackpotFeeBps: number;
  metadata: string;
};

export type PlayGameInstructionDataArgs = {
  wager: number | bigint;
  bet: Array<number>;
  clientSeed: string;
  creatorFeeBps: number;
  jackpotFeeBps: number;
  metadata: string;
};

export function getPlayGameInstructionDataEncoder(): Encoder<PlayGameInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['wager', getU64Encoder()],
      ['bet', getArrayEncoder(getU32Encoder())],
      ['clientSeed', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ['creatorFeeBps', getU32Encoder()],
      ['jackpotFeeBps', getU32Encoder()],
      ['metadata', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: PLAY_GAME_DISCRIMINATOR })
  );
}

export function getPlayGameInstructionDataDecoder(): Decoder<PlayGameInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['wager', getU64Decoder()],
    ['bet', getArrayDecoder(getU32Decoder())],
    ['clientSeed', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['creatorFeeBps', getU32Decoder()],
    ['jackpotFeeBps', getU32Decoder()],
    ['metadata', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getPlayGameInstructionDataCodec(): Codec<
  PlayGameInstructionDataArgs,
  PlayGameInstructionData
> {
  return combineCodec(
    getPlayGameInstructionDataEncoder(),
    getPlayGameInstructionDataDecoder()
  );
}

export type PlayGameAsyncInput<
  TAccountUser extends string = string,
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountPool extends string = string,
  TAccountUnderlyingTokenMint extends string = string,
  TAccountBonusTokenMint extends string = string,
  TAccountUserUnderlyingAta extends string = string,
  TAccountCreator extends string = string,
  TAccountCreatorAta extends string = string,
  TAccountPlayerAta extends string = string,
  TAccountPlayerBonusAta extends string = string,
  TAccountUserBonusAta extends string = string,
  TAccountGambaState extends string = string,
  TAccountPoolJackpotTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  player?: Address<TAccountPlayer>;
  game?: Address<TAccountGame>;
  pool: Address<TAccountPool>;
  underlyingTokenMint: Address<TAccountUnderlyingTokenMint>;
  bonusTokenMint?: Address<TAccountBonusTokenMint>;
  userUnderlyingAta: Address<TAccountUserUnderlyingAta>;
  creator: Address<TAccountCreator>;
  creatorAta: Address<TAccountCreatorAta>;
  playerAta: Address<TAccountPlayerAta>;
  playerBonusAta?: Address<TAccountPlayerBonusAta>;
  userBonusAta?: Address<TAccountUserBonusAta>;
  gambaState?: Address<TAccountGambaState>;
  poolJackpotTokenAccount?: Address<TAccountPoolJackpotTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  wager: PlayGameInstructionDataArgs['wager'];
  bet: PlayGameInstructionDataArgs['bet'];
  clientSeed: PlayGameInstructionDataArgs['clientSeed'];
  creatorFeeBps: PlayGameInstructionDataArgs['creatorFeeBps'];
  jackpotFeeBps: PlayGameInstructionDataArgs['jackpotFeeBps'];
  metadata: PlayGameInstructionDataArgs['metadata'];
};

export async function getPlayGameInstructionAsync<
  TAccountUser extends string,
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountPool extends string,
  TAccountUnderlyingTokenMint extends string,
  TAccountBonusTokenMint extends string,
  TAccountUserUnderlyingAta extends string,
  TAccountCreator extends string,
  TAccountCreatorAta extends string,
  TAccountPlayerAta extends string,
  TAccountPlayerBonusAta extends string,
  TAccountUserBonusAta extends string,
  TAccountGambaState extends string,
  TAccountPoolJackpotTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PlayGameAsyncInput<
    TAccountUser,
    TAccountPlayer,
    TAccountGame,
    TAccountPool,
    TAccountUnderlyingTokenMint,
    TAccountBonusTokenMint,
    TAccountUserUnderlyingAta,
    TAccountCreator,
    TAccountCreatorAta,
    TAccountPlayerAta,
    TAccountPlayerBonusAta,
    TAccountUserBonusAta,
    TAccountGambaState,
    TAccountPoolJackpotTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  PlayGameInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountPlayer,
    TAccountGame,
    TAccountPool,
    TAccountUnderlyingTokenMint,
    TAccountBonusTokenMint,
    TAccountUserUnderlyingAta,
    TAccountCreator,
    TAccountCreatorAta,
    TAccountPlayerAta,
    TAccountPlayerBonusAta,
    TAccountUserBonusAta,
    TAccountGambaState,
    TAccountPoolJackpotTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: true },
    pool: { value: input.pool ?? null, isWritable: true },
    underlyingTokenMint: {
      value: input.underlyingTokenMint ?? null,
      isWritable: false,
    },
    bonusTokenMint: { value: input.bonusTokenMint ?? null, isWritable: false },
    userUnderlyingAta: {
      value: input.userUnderlyingAta ?? null,
      isWritable: true,
    },
    creator: { value: input.creator ?? null, isWritable: false },
    creatorAta: { value: input.creatorAta ?? null, isWritable: true },
    playerAta: { value: input.playerAta ?? null, isWritable: true },
    playerBonusAta: { value: input.playerBonusAta ?? null, isWritable: true },
    userBonusAta: { value: input.userBonusAta ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    poolJackpotTokenAccount: {
      value: input.poolJackpotTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.player.value) {
    accounts.player.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 80, 76, 65, 89, 69, 82, 34])
        ),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }
  if (!accounts.game.value) {
    accounts.game.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([34, 71, 65, 77, 69, 34])),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }
  if (!accounts.bonusTokenMint.value) {
    accounts.bonusTokenMint.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            34, 80, 79, 79, 76, 95, 66, 79, 78, 85, 83, 95, 77, 73, 78, 84, 34,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.pool.value)),
      ],
    });
  }
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69, 34])
        ),
      ],
    });
  }
  if (!accounts.poolJackpotTokenAccount.value) {
    accounts.poolJackpotTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            34, 80, 79, 79, 76, 95, 74, 65, 67, 75, 80, 79, 84, 34,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.pool.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.underlyingTokenMint),
      getAccountMeta(accounts.bonusTokenMint),
      getAccountMeta(accounts.userUnderlyingAta),
      getAccountMeta(accounts.creator),
      getAccountMeta(accounts.creatorAta),
      getAccountMeta(accounts.playerAta),
      getAccountMeta(accounts.playerBonusAta),
      getAccountMeta(accounts.userBonusAta),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.poolJackpotTokenAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
    ],
    programAddress,
    data: getPlayGameInstructionDataEncoder().encode(
      args as PlayGameInstructionDataArgs
    ),
  } as PlayGameInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountPlayer,
    TAccountGame,
    TAccountPool,
    TAccountUnderlyingTokenMint,
    TAccountBonusTokenMint,
    TAccountUserUnderlyingAta,
    TAccountCreator,
    TAccountCreatorAta,
    TAccountPlayerAta,
    TAccountPlayerBonusAta,
    TAccountUserBonusAta,
    TAccountGambaState,
    TAccountPoolJackpotTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >;

  return instruction;
}

export type PlayGameInput<
  TAccountUser extends string = string,
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountPool extends string = string,
  TAccountUnderlyingTokenMint extends string = string,
  TAccountBonusTokenMint extends string = string,
  TAccountUserUnderlyingAta extends string = string,
  TAccountCreator extends string = string,
  TAccountCreatorAta extends string = string,
  TAccountPlayerAta extends string = string,
  TAccountPlayerBonusAta extends string = string,
  TAccountUserBonusAta extends string = string,
  TAccountGambaState extends string = string,
  TAccountPoolJackpotTokenAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  player: Address<TAccountPlayer>;
  game: Address<TAccountGame>;
  pool: Address<TAccountPool>;
  underlyingTokenMint: Address<TAccountUnderlyingTokenMint>;
  bonusTokenMint: Address<TAccountBonusTokenMint>;
  userUnderlyingAta: Address<TAccountUserUnderlyingAta>;
  creator: Address<TAccountCreator>;
  creatorAta: Address<TAccountCreatorAta>;
  playerAta: Address<TAccountPlayerAta>;
  playerBonusAta?: Address<TAccountPlayerBonusAta>;
  userBonusAta?: Address<TAccountUserBonusAta>;
  gambaState: Address<TAccountGambaState>;
  poolJackpotTokenAccount: Address<TAccountPoolJackpotTokenAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  wager: PlayGameInstructionDataArgs['wager'];
  bet: PlayGameInstructionDataArgs['bet'];
  clientSeed: PlayGameInstructionDataArgs['clientSeed'];
  creatorFeeBps: PlayGameInstructionDataArgs['creatorFeeBps'];
  jackpotFeeBps: PlayGameInstructionDataArgs['jackpotFeeBps'];
  metadata: PlayGameInstructionDataArgs['metadata'];
};

export function getPlayGameInstruction<
  TAccountUser extends string,
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountPool extends string,
  TAccountUnderlyingTokenMint extends string,
  TAccountBonusTokenMint extends string,
  TAccountUserUnderlyingAta extends string,
  TAccountCreator extends string,
  TAccountCreatorAta extends string,
  TAccountPlayerAta extends string,
  TAccountPlayerBonusAta extends string,
  TAccountUserBonusAta extends string,
  TAccountGambaState extends string,
  TAccountPoolJackpotTokenAccount extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PlayGameInput<
    TAccountUser,
    TAccountPlayer,
    TAccountGame,
    TAccountPool,
    TAccountUnderlyingTokenMint,
    TAccountBonusTokenMint,
    TAccountUserUnderlyingAta,
    TAccountCreator,
    TAccountCreatorAta,
    TAccountPlayerAta,
    TAccountPlayerBonusAta,
    TAccountUserBonusAta,
    TAccountGambaState,
    TAccountPoolJackpotTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): PlayGameInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountPlayer,
  TAccountGame,
  TAccountPool,
  TAccountUnderlyingTokenMint,
  TAccountBonusTokenMint,
  TAccountUserUnderlyingAta,
  TAccountCreator,
  TAccountCreatorAta,
  TAccountPlayerAta,
  TAccountPlayerBonusAta,
  TAccountUserBonusAta,
  TAccountGambaState,
  TAccountPoolJackpotTokenAccount,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: true },
    pool: { value: input.pool ?? null, isWritable: true },
    underlyingTokenMint: {
      value: input.underlyingTokenMint ?? null,
      isWritable: false,
    },
    bonusTokenMint: { value: input.bonusTokenMint ?? null, isWritable: false },
    userUnderlyingAta: {
      value: input.userUnderlyingAta ?? null,
      isWritable: true,
    },
    creator: { value: input.creator ?? null, isWritable: false },
    creatorAta: { value: input.creatorAta ?? null, isWritable: true },
    playerAta: { value: input.playerAta ?? null, isWritable: true },
    playerBonusAta: { value: input.playerBonusAta ?? null, isWritable: true },
    userBonusAta: { value: input.userBonusAta ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    poolJackpotTokenAccount: {
      value: input.poolJackpotTokenAccount ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.underlyingTokenMint),
      getAccountMeta(accounts.bonusTokenMint),
      getAccountMeta(accounts.userUnderlyingAta),
      getAccountMeta(accounts.creator),
      getAccountMeta(accounts.creatorAta),
      getAccountMeta(accounts.playerAta),
      getAccountMeta(accounts.playerBonusAta),
      getAccountMeta(accounts.userBonusAta),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.poolJackpotTokenAccount),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
    ],
    programAddress,
    data: getPlayGameInstructionDataEncoder().encode(
      args as PlayGameInstructionDataArgs
    ),
  } as PlayGameInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountPlayer,
    TAccountGame,
    TAccountPool,
    TAccountUnderlyingTokenMint,
    TAccountBonusTokenMint,
    TAccountUserUnderlyingAta,
    TAccountCreator,
    TAccountCreatorAta,
    TAccountPlayerAta,
    TAccountPlayerBonusAta,
    TAccountUserBonusAta,
    TAccountGambaState,
    TAccountPoolJackpotTokenAccount,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >;

  return instruction;
}

export type ParsedPlayGameInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    player: TAccountMetas[1];
    game: TAccountMetas[2];
    pool: TAccountMetas[3];
    underlyingTokenMint: TAccountMetas[4];
    bonusTokenMint: TAccountMetas[5];
    userUnderlyingAta: TAccountMetas[6];
    creator: TAccountMetas[7];
    creatorAta: TAccountMetas[8];
    playerAta: TAccountMetas[9];
    playerBonusAta?: TAccountMetas[10] | undefined;
    userBonusAta?: TAccountMetas[11] | undefined;
    gambaState: TAccountMetas[12];
    poolJackpotTokenAccount: TAccountMetas[13];
    systemProgram: TAccountMetas[14];
    tokenProgram: TAccountMetas[15];
    associatedTokenProgram: TAccountMetas[16];
  };
  data: PlayGameInstructionData;
};

export function parsePlayGameInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedPlayGameInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 17) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === GAMBA_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      player: getNextAccount(),
      game: getNextAccount(),
      pool: getNextAccount(),
      underlyingTokenMint: getNextAccount(),
      bonusTokenMint: getNextAccount(),
      userUnderlyingAta: getNextAccount(),
      creator: getNextAccount(),
      creatorAta: getNextAccount(),
      playerAta: getNextAccount(),
      playerBonusAta: getNextOptionalAccount(),
      userBonusAta: getNextOptionalAccount(),
      gambaState: getNextAccount(),
      poolJackpotTokenAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
    },
    data: getPlayGameInstructionDataDecoder().decode(instruction.data),
  };
}
