/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const POOL_GAMBA_CONFIG_DISCRIMINATOR = new Uint8Array([
  197, 177, 234, 111, 246, 248, 20, 155,
]);

export function getPoolGambaConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    POOL_GAMBA_CONFIG_DISCRIMINATOR
  );
}

export type PoolGambaConfigInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountGambaState extends string
        ? ReadonlyAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      ...TRemainingAccounts,
    ]
  >;

export type PoolGambaConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  antiSpamFeeExemption: boolean;
  customGambaFee: boolean;
  customGambaFeeBps: bigint;
};

export type PoolGambaConfigInstructionDataArgs = {
  antiSpamFeeExemption: boolean;
  customGambaFee: boolean;
  customGambaFeeBps: number | bigint;
};

export function getPoolGambaConfigInstructionDataEncoder(): FixedSizeEncoder<PoolGambaConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['antiSpamFeeExemption', getBooleanEncoder()],
      ['customGambaFee', getBooleanEncoder()],
      ['customGambaFeeBps', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: POOL_GAMBA_CONFIG_DISCRIMINATOR })
  );
}

export function getPoolGambaConfigInstructionDataDecoder(): FixedSizeDecoder<PoolGambaConfigInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['antiSpamFeeExemption', getBooleanDecoder()],
    ['customGambaFee', getBooleanDecoder()],
    ['customGambaFeeBps', getU64Decoder()],
  ]);
}

export function getPoolGambaConfigInstructionDataCodec(): FixedSizeCodec<
  PoolGambaConfigInstructionDataArgs,
  PoolGambaConfigInstructionData
> {
  return combineCodec(
    getPoolGambaConfigInstructionDataEncoder(),
    getPoolGambaConfigInstructionDataDecoder()
  );
}

export type PoolGambaConfigAsyncInput<
  TAccountUser extends string = string,
  TAccountGambaState extends string = string,
  TAccountPool extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  gambaState?: Address<TAccountGambaState>;
  pool: Address<TAccountPool>;
  antiSpamFeeExemption: PoolGambaConfigInstructionDataArgs['antiSpamFeeExemption'];
  customGambaFee: PoolGambaConfigInstructionDataArgs['customGambaFee'];
  customGambaFeeBps: PoolGambaConfigInstructionDataArgs['customGambaFeeBps'];
};

export async function getPoolGambaConfigInstructionAsync<
  TAccountUser extends string,
  TAccountGambaState extends string,
  TAccountPool extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PoolGambaConfigAsyncInput<
    TAccountUser,
    TAccountGambaState,
    TAccountPool
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  PoolGambaConfigInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountGambaState,
    TAccountPool
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69, 34])
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.pool),
    ],
    programAddress,
    data: getPoolGambaConfigInstructionDataEncoder().encode(
      args as PoolGambaConfigInstructionDataArgs
    ),
  } as PoolGambaConfigInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountGambaState,
    TAccountPool
  >;

  return instruction;
}

export type PoolGambaConfigInput<
  TAccountUser extends string = string,
  TAccountGambaState extends string = string,
  TAccountPool extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  gambaState: Address<TAccountGambaState>;
  pool: Address<TAccountPool>;
  antiSpamFeeExemption: PoolGambaConfigInstructionDataArgs['antiSpamFeeExemption'];
  customGambaFee: PoolGambaConfigInstructionDataArgs['customGambaFee'];
  customGambaFeeBps: PoolGambaConfigInstructionDataArgs['customGambaFeeBps'];
};

export function getPoolGambaConfigInstruction<
  TAccountUser extends string,
  TAccountGambaState extends string,
  TAccountPool extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PoolGambaConfigInput<TAccountUser, TAccountGambaState, TAccountPool>,
  config?: { programAddress?: TProgramAddress }
): PoolGambaConfigInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountGambaState,
  TAccountPool
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.pool),
    ],
    programAddress,
    data: getPoolGambaConfigInstructionDataEncoder().encode(
      args as PoolGambaConfigInstructionDataArgs
    ),
  } as PoolGambaConfigInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountGambaState,
    TAccountPool
  >;

  return instruction;
}

export type ParsedPoolGambaConfigInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    gambaState: TAccountMetas[1];
    pool: TAccountMetas[2];
  };
  data: PoolGambaConfigInstructionData;
};

export function parsePoolGambaConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedPoolGambaConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      gambaState: getNextAccount(),
      pool: getNextAccount(),
    },
    data: getPoolGambaConfigInstructionDataDecoder().decode(instruction.data),
  };
}
