/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const POOL_INITIALIZE_DISCRIMINATOR = new Uint8Array([
  37, 10, 195, 69, 4, 213, 88, 173,
]);

export function getPoolInitializeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    POOL_INITIALIZE_DISCRIMINATOR
  );
}

export type PoolInitializeInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountInitializer extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountUnderlyingTokenMint extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPoolUnderlyingTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountPoolBonusUnderlyingTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountPoolJackpotTokenAccount extends string | AccountMeta<string> = string,
  TAccountGambaStateAta extends string | AccountMeta<string> = string,
  TAccountLpMint extends string | AccountMeta<string> = string,
  TAccountLpMintMetadata extends string | AccountMeta<string> = string,
  TAccountBonusMint extends string | AccountMeta<string> = string,
  TAccountBonusMintMetadata extends string | AccountMeta<string> = string,
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountRent extends
    | string
    | AccountMeta<string> = 'SysvarRent111111111111111111111111111111111',
  TAccountTokenMetadataProgram extends
    | string
    | AccountMeta<string> = 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountInitializer extends string
        ? WritableSignerAccount<TAccountInitializer> &
            AccountSignerMeta<TAccountInitializer>
        : TAccountInitializer,
      TAccountGambaState extends string
        ? WritableAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountUnderlyingTokenMint extends string
        ? ReadonlyAccount<TAccountUnderlyingTokenMint>
        : TAccountUnderlyingTokenMint,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountPoolUnderlyingTokenAccount extends string
        ? WritableAccount<TAccountPoolUnderlyingTokenAccount>
        : TAccountPoolUnderlyingTokenAccount,
      TAccountPoolBonusUnderlyingTokenAccount extends string
        ? WritableAccount<TAccountPoolBonusUnderlyingTokenAccount>
        : TAccountPoolBonusUnderlyingTokenAccount,
      TAccountPoolJackpotTokenAccount extends string
        ? WritableAccount<TAccountPoolJackpotTokenAccount>
        : TAccountPoolJackpotTokenAccount,
      TAccountGambaStateAta extends string
        ? WritableAccount<TAccountGambaStateAta>
        : TAccountGambaStateAta,
      TAccountLpMint extends string
        ? WritableAccount<TAccountLpMint>
        : TAccountLpMint,
      TAccountLpMintMetadata extends string
        ? WritableAccount<TAccountLpMintMetadata>
        : TAccountLpMintMetadata,
      TAccountBonusMint extends string
        ? WritableAccount<TAccountBonusMint>
        : TAccountBonusMint,
      TAccountBonusMintMetadata extends string
        ? WritableAccount<TAccountBonusMintMetadata>
        : TAccountBonusMintMetadata,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      TAccountTokenMetadataProgram extends string
        ? ReadonlyAccount<TAccountTokenMetadataProgram>
        : TAccountTokenMetadataProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PoolInitializeInstructionData = {
  discriminator: ReadonlyUint8Array;
  poolAuthority: Address;
  lookupAddress: Address;
};

export type PoolInitializeInstructionDataArgs = {
  poolAuthority: Address;
  lookupAddress: Address;
};

export function getPoolInitializeInstructionDataEncoder(): FixedSizeEncoder<PoolInitializeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['poolAuthority', getAddressEncoder()],
      ['lookupAddress', getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: POOL_INITIALIZE_DISCRIMINATOR })
  );
}

export function getPoolInitializeInstructionDataDecoder(): FixedSizeDecoder<PoolInitializeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['poolAuthority', getAddressDecoder()],
    ['lookupAddress', getAddressDecoder()],
  ]);
}

export function getPoolInitializeInstructionDataCodec(): FixedSizeCodec<
  PoolInitializeInstructionDataArgs,
  PoolInitializeInstructionData
> {
  return combineCodec(
    getPoolInitializeInstructionDataEncoder(),
    getPoolInitializeInstructionDataDecoder()
  );
}

export type PoolInitializeAsyncInput<
  TAccountInitializer extends string = string,
  TAccountGambaState extends string = string,
  TAccountUnderlyingTokenMint extends string = string,
  TAccountPool extends string = string,
  TAccountPoolUnderlyingTokenAccount extends string = string,
  TAccountPoolBonusUnderlyingTokenAccount extends string = string,
  TAccountPoolJackpotTokenAccount extends string = string,
  TAccountGambaStateAta extends string = string,
  TAccountLpMint extends string = string,
  TAccountLpMintMetadata extends string = string,
  TAccountBonusMint extends string = string,
  TAccountBonusMintMetadata extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRent extends string = string,
  TAccountTokenMetadataProgram extends string = string,
> = {
  initializer: TransactionSigner<TAccountInitializer>;
  gambaState?: Address<TAccountGambaState>;
  underlyingTokenMint: Address<TAccountUnderlyingTokenMint>;
  pool?: Address<TAccountPool>;
  poolUnderlyingTokenAccount?: Address<TAccountPoolUnderlyingTokenAccount>;
  poolBonusUnderlyingTokenAccount?: Address<TAccountPoolBonusUnderlyingTokenAccount>;
  poolJackpotTokenAccount?: Address<TAccountPoolJackpotTokenAccount>;
  gambaStateAta: Address<TAccountGambaStateAta>;
  lpMint?: Address<TAccountLpMint>;
  lpMintMetadata: Address<TAccountLpMintMetadata>;
  bonusMint?: Address<TAccountBonusMint>;
  bonusMintMetadata: Address<TAccountBonusMintMetadata>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  rent?: Address<TAccountRent>;
  tokenMetadataProgram?: Address<TAccountTokenMetadataProgram>;
  poolAuthority: PoolInitializeInstructionDataArgs['poolAuthority'];
  lookupAddress: PoolInitializeInstructionDataArgs['lookupAddress'];
};

export async function getPoolInitializeInstructionAsync<
  TAccountInitializer extends string,
  TAccountGambaState extends string,
  TAccountUnderlyingTokenMint extends string,
  TAccountPool extends string,
  TAccountPoolUnderlyingTokenAccount extends string,
  TAccountPoolBonusUnderlyingTokenAccount extends string,
  TAccountPoolJackpotTokenAccount extends string,
  TAccountGambaStateAta extends string,
  TAccountLpMint extends string,
  TAccountLpMintMetadata extends string,
  TAccountBonusMint extends string,
  TAccountBonusMintMetadata extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TAccountRent extends string,
  TAccountTokenMetadataProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PoolInitializeAsyncInput<
    TAccountInitializer,
    TAccountGambaState,
    TAccountUnderlyingTokenMint,
    TAccountPool,
    TAccountPoolUnderlyingTokenAccount,
    TAccountPoolBonusUnderlyingTokenAccount,
    TAccountPoolJackpotTokenAccount,
    TAccountGambaStateAta,
    TAccountLpMint,
    TAccountLpMintMetadata,
    TAccountBonusMint,
    TAccountBonusMintMetadata,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountRent,
    TAccountTokenMetadataProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  PoolInitializeInstruction<
    TProgramAddress,
    TAccountInitializer,
    TAccountGambaState,
    TAccountUnderlyingTokenMint,
    TAccountPool,
    TAccountPoolUnderlyingTokenAccount,
    TAccountPoolBonusUnderlyingTokenAccount,
    TAccountPoolJackpotTokenAccount,
    TAccountGambaStateAta,
    TAccountLpMint,
    TAccountLpMintMetadata,
    TAccountBonusMint,
    TAccountBonusMintMetadata,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountRent,
    TAccountTokenMetadataProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    initializer: { value: input.initializer ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    underlyingTokenMint: {
      value: input.underlyingTokenMint ?? null,
      isWritable: false,
    },
    pool: { value: input.pool ?? null, isWritable: true },
    poolUnderlyingTokenAccount: {
      value: input.poolUnderlyingTokenAccount ?? null,
      isWritable: true,
    },
    poolBonusUnderlyingTokenAccount: {
      value: input.poolBonusUnderlyingTokenAccount ?? null,
      isWritable: true,
    },
    poolJackpotTokenAccount: {
      value: input.poolJackpotTokenAccount ?? null,
      isWritable: true,
    },
    gambaStateAta: { value: input.gambaStateAta ?? null, isWritable: true },
    lpMint: { value: input.lpMint ?? null, isWritable: true },
    lpMintMetadata: { value: input.lpMintMetadata ?? null, isWritable: true },
    bonusMint: { value: input.bonusMint ?? null, isWritable: true },
    bonusMintMetadata: {
      value: input.bonusMintMetadata ?? null,
      isWritable: true,
    },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
    tokenMetadataProgram: {
      value: input.tokenMetadataProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69, 34])
        ),
      ],
    });
  }
  if (!accounts.pool.value) {
    accounts.pool.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([34, 80, 79, 79, 76, 34])),
        getAddressEncoder().encode(
          expectAddress(accounts.underlyingTokenMint.value)
        ),
        getAddressEncoder().encode(expectSome(args.poolAuthority)),
      ],
    });
  }
  if (!accounts.poolUnderlyingTokenAccount.value) {
    accounts.poolUnderlyingTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 80, 79, 79, 76, 95, 65, 84, 65, 34])
        ),
        getAddressEncoder().encode(expectAddress(accounts.pool.value)),
      ],
    });
  }
  if (!accounts.poolBonusUnderlyingTokenAccount.value) {
    accounts.poolBonusUnderlyingTokenAccount.value =
      await getProgramDerivedAddress({
        programAddress,
        seeds: [
          getBytesEncoder().encode(
            new Uint8Array([
              34, 80, 79, 79, 76, 95, 66, 79, 78, 85, 83, 95, 85, 78, 68, 69,
              82, 76, 89, 73, 78, 71, 95, 84, 65, 34,
            ])
          ),
          getAddressEncoder().encode(expectAddress(accounts.pool.value)),
        ],
      });
  }
  if (!accounts.poolJackpotTokenAccount.value) {
    accounts.poolJackpotTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            34, 80, 79, 79, 76, 95, 74, 65, 67, 75, 80, 79, 84, 34,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.pool.value)),
      ],
    });
  }
  if (!accounts.lpMint.value) {
    accounts.lpMint.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            34, 80, 79, 79, 76, 95, 76, 80, 95, 77, 73, 78, 84, 34,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.pool.value)),
      ],
    });
  }
  if (!accounts.bonusMint.value) {
    accounts.bonusMint.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            34, 80, 79, 79, 76, 95, 66, 79, 78, 85, 83, 95, 77, 73, 78, 84, 34,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.pool.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }
  if (!accounts.tokenMetadataProgram.value) {
    accounts.tokenMetadataProgram.value =
      'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s' as Address<'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.initializer),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.underlyingTokenMint),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.poolUnderlyingTokenAccount),
      getAccountMeta(accounts.poolBonusUnderlyingTokenAccount),
      getAccountMeta(accounts.poolJackpotTokenAccount),
      getAccountMeta(accounts.gambaStateAta),
      getAccountMeta(accounts.lpMint),
      getAccountMeta(accounts.lpMintMetadata),
      getAccountMeta(accounts.bonusMint),
      getAccountMeta(accounts.bonusMintMetadata),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.rent),
      getAccountMeta(accounts.tokenMetadataProgram),
    ],
    programAddress,
    data: getPoolInitializeInstructionDataEncoder().encode(
      args as PoolInitializeInstructionDataArgs
    ),
  } as PoolInitializeInstruction<
    TProgramAddress,
    TAccountInitializer,
    TAccountGambaState,
    TAccountUnderlyingTokenMint,
    TAccountPool,
    TAccountPoolUnderlyingTokenAccount,
    TAccountPoolBonusUnderlyingTokenAccount,
    TAccountPoolJackpotTokenAccount,
    TAccountGambaStateAta,
    TAccountLpMint,
    TAccountLpMintMetadata,
    TAccountBonusMint,
    TAccountBonusMintMetadata,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountRent,
    TAccountTokenMetadataProgram
  >;

  return instruction;
}

export type PoolInitializeInput<
  TAccountInitializer extends string = string,
  TAccountGambaState extends string = string,
  TAccountUnderlyingTokenMint extends string = string,
  TAccountPool extends string = string,
  TAccountPoolUnderlyingTokenAccount extends string = string,
  TAccountPoolBonusUnderlyingTokenAccount extends string = string,
  TAccountPoolJackpotTokenAccount extends string = string,
  TAccountGambaStateAta extends string = string,
  TAccountLpMint extends string = string,
  TAccountLpMintMetadata extends string = string,
  TAccountBonusMint extends string = string,
  TAccountBonusMintMetadata extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountRent extends string = string,
  TAccountTokenMetadataProgram extends string = string,
> = {
  initializer: TransactionSigner<TAccountInitializer>;
  gambaState: Address<TAccountGambaState>;
  underlyingTokenMint: Address<TAccountUnderlyingTokenMint>;
  pool: Address<TAccountPool>;
  poolUnderlyingTokenAccount: Address<TAccountPoolUnderlyingTokenAccount>;
  poolBonusUnderlyingTokenAccount: Address<TAccountPoolBonusUnderlyingTokenAccount>;
  poolJackpotTokenAccount: Address<TAccountPoolJackpotTokenAccount>;
  gambaStateAta: Address<TAccountGambaStateAta>;
  lpMint: Address<TAccountLpMint>;
  lpMintMetadata: Address<TAccountLpMintMetadata>;
  bonusMint: Address<TAccountBonusMint>;
  bonusMintMetadata: Address<TAccountBonusMintMetadata>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  rent?: Address<TAccountRent>;
  tokenMetadataProgram?: Address<TAccountTokenMetadataProgram>;
  poolAuthority: PoolInitializeInstructionDataArgs['poolAuthority'];
  lookupAddress: PoolInitializeInstructionDataArgs['lookupAddress'];
};

export function getPoolInitializeInstruction<
  TAccountInitializer extends string,
  TAccountGambaState extends string,
  TAccountUnderlyingTokenMint extends string,
  TAccountPool extends string,
  TAccountPoolUnderlyingTokenAccount extends string,
  TAccountPoolBonusUnderlyingTokenAccount extends string,
  TAccountPoolJackpotTokenAccount extends string,
  TAccountGambaStateAta extends string,
  TAccountLpMint extends string,
  TAccountLpMintMetadata extends string,
  TAccountBonusMint extends string,
  TAccountBonusMintMetadata extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TAccountRent extends string,
  TAccountTokenMetadataProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PoolInitializeInput<
    TAccountInitializer,
    TAccountGambaState,
    TAccountUnderlyingTokenMint,
    TAccountPool,
    TAccountPoolUnderlyingTokenAccount,
    TAccountPoolBonusUnderlyingTokenAccount,
    TAccountPoolJackpotTokenAccount,
    TAccountGambaStateAta,
    TAccountLpMint,
    TAccountLpMintMetadata,
    TAccountBonusMint,
    TAccountBonusMintMetadata,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountRent,
    TAccountTokenMetadataProgram
  >,
  config?: { programAddress?: TProgramAddress }
): PoolInitializeInstruction<
  TProgramAddress,
  TAccountInitializer,
  TAccountGambaState,
  TAccountUnderlyingTokenMint,
  TAccountPool,
  TAccountPoolUnderlyingTokenAccount,
  TAccountPoolBonusUnderlyingTokenAccount,
  TAccountPoolJackpotTokenAccount,
  TAccountGambaStateAta,
  TAccountLpMint,
  TAccountLpMintMetadata,
  TAccountBonusMint,
  TAccountBonusMintMetadata,
  TAccountAssociatedTokenProgram,
  TAccountTokenProgram,
  TAccountSystemProgram,
  TAccountRent,
  TAccountTokenMetadataProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    initializer: { value: input.initializer ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    underlyingTokenMint: {
      value: input.underlyingTokenMint ?? null,
      isWritable: false,
    },
    pool: { value: input.pool ?? null, isWritable: true },
    poolUnderlyingTokenAccount: {
      value: input.poolUnderlyingTokenAccount ?? null,
      isWritable: true,
    },
    poolBonusUnderlyingTokenAccount: {
      value: input.poolBonusUnderlyingTokenAccount ?? null,
      isWritable: true,
    },
    poolJackpotTokenAccount: {
      value: input.poolJackpotTokenAccount ?? null,
      isWritable: true,
    },
    gambaStateAta: { value: input.gambaStateAta ?? null, isWritable: true },
    lpMint: { value: input.lpMint ?? null, isWritable: true },
    lpMintMetadata: { value: input.lpMintMetadata ?? null, isWritable: true },
    bonusMint: { value: input.bonusMint ?? null, isWritable: true },
    bonusMintMetadata: {
      value: input.bonusMintMetadata ?? null,
      isWritable: true,
    },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    rent: { value: input.rent ?? null, isWritable: false },
    tokenMetadataProgram: {
      value: input.tokenMetadataProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      'SysvarRent111111111111111111111111111111111' as Address<'SysvarRent111111111111111111111111111111111'>;
  }
  if (!accounts.tokenMetadataProgram.value) {
    accounts.tokenMetadataProgram.value =
      'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s' as Address<'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.initializer),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.underlyingTokenMint),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.poolUnderlyingTokenAccount),
      getAccountMeta(accounts.poolBonusUnderlyingTokenAccount),
      getAccountMeta(accounts.poolJackpotTokenAccount),
      getAccountMeta(accounts.gambaStateAta),
      getAccountMeta(accounts.lpMint),
      getAccountMeta(accounts.lpMintMetadata),
      getAccountMeta(accounts.bonusMint),
      getAccountMeta(accounts.bonusMintMetadata),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.rent),
      getAccountMeta(accounts.tokenMetadataProgram),
    ],
    programAddress,
    data: getPoolInitializeInstructionDataEncoder().encode(
      args as PoolInitializeInstructionDataArgs
    ),
  } as PoolInitializeInstruction<
    TProgramAddress,
    TAccountInitializer,
    TAccountGambaState,
    TAccountUnderlyingTokenMint,
    TAccountPool,
    TAccountPoolUnderlyingTokenAccount,
    TAccountPoolBonusUnderlyingTokenAccount,
    TAccountPoolJackpotTokenAccount,
    TAccountGambaStateAta,
    TAccountLpMint,
    TAccountLpMintMetadata,
    TAccountBonusMint,
    TAccountBonusMintMetadata,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram,
    TAccountRent,
    TAccountTokenMetadataProgram
  >;

  return instruction;
}

export type ParsedPoolInitializeInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    initializer: TAccountMetas[0];
    gambaState: TAccountMetas[1];
    underlyingTokenMint: TAccountMetas[2];
    pool: TAccountMetas[3];
    poolUnderlyingTokenAccount: TAccountMetas[4];
    poolBonusUnderlyingTokenAccount: TAccountMetas[5];
    poolJackpotTokenAccount: TAccountMetas[6];
    gambaStateAta: TAccountMetas[7];
    lpMint: TAccountMetas[8];
    lpMintMetadata: TAccountMetas[9];
    bonusMint: TAccountMetas[10];
    bonusMintMetadata: TAccountMetas[11];
    associatedTokenProgram: TAccountMetas[12];
    tokenProgram: TAccountMetas[13];
    systemProgram: TAccountMetas[14];
    rent: TAccountMetas[15];
    tokenMetadataProgram: TAccountMetas[16];
  };
  data: PoolInitializeInstructionData;
};

export function parsePoolInitializeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedPoolInitializeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 17) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      initializer: getNextAccount(),
      gambaState: getNextAccount(),
      underlyingTokenMint: getNextAccount(),
      pool: getNextAccount(),
      poolUnderlyingTokenAccount: getNextAccount(),
      poolBonusUnderlyingTokenAccount: getNextAccount(),
      poolJackpotTokenAccount: getNextAccount(),
      gambaStateAta: getNextAccount(),
      lpMint: getNextAccount(),
      lpMintMetadata: getNextAccount(),
      bonusMint: getNextAccount(),
      bonusMintMetadata: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
      rent: getNextAccount(),
      tokenMetadataProgram: getNextAccount(),
    },
    data: getPoolInitializeInstructionDataDecoder().decode(instruction.data),
  };
}
