/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const POOL_DEPOSIT_DISCRIMINATOR = new Uint8Array([
  26, 109, 164, 79, 207, 145, 204, 217,
]);

export function getPoolDepositDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    POOL_DEPOSIT_DISCRIMINATOR
  );
}

export type PoolDepositInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPoolUnderlyingTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountLpMint extends string | AccountMeta<string> = string,
  TAccountUnderlyingTokenMint extends string | AccountMeta<string> = string,
  TAccountUserUnderlyingAta extends string | AccountMeta<string> = string,
  TAccountUserLpAta extends string | AccountMeta<string> = string,
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountGambaState extends string
        ? ReadonlyAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountPoolUnderlyingTokenAccount extends string
        ? WritableAccount<TAccountPoolUnderlyingTokenAccount>
        : TAccountPoolUnderlyingTokenAccount,
      TAccountLpMint extends string
        ? WritableAccount<TAccountLpMint>
        : TAccountLpMint,
      TAccountUnderlyingTokenMint extends string
        ? ReadonlyAccount<TAccountUnderlyingTokenMint>
        : TAccountUnderlyingTokenMint,
      TAccountUserUnderlyingAta extends string
        ? WritableAccount<TAccountUserUnderlyingAta>
        : TAccountUserUnderlyingAta,
      TAccountUserLpAta extends string
        ? WritableAccount<TAccountUserLpAta>
        : TAccountUserLpAta,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PoolDepositInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type PoolDepositInstructionDataArgs = { amount: number | bigint };

export function getPoolDepositInstructionDataEncoder(): FixedSizeEncoder<PoolDepositInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['amount', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: POOL_DEPOSIT_DISCRIMINATOR })
  );
}

export function getPoolDepositInstructionDataDecoder(): FixedSizeDecoder<PoolDepositInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['amount', getU64Decoder()],
  ]);
}

export function getPoolDepositInstructionDataCodec(): FixedSizeCodec<
  PoolDepositInstructionDataArgs,
  PoolDepositInstructionData
> {
  return combineCodec(
    getPoolDepositInstructionDataEncoder(),
    getPoolDepositInstructionDataDecoder()
  );
}

export type PoolDepositAsyncInput<
  TAccountUser extends string = string,
  TAccountGambaState extends string = string,
  TAccountPool extends string = string,
  TAccountPoolUnderlyingTokenAccount extends string = string,
  TAccountLpMint extends string = string,
  TAccountUnderlyingTokenMint extends string = string,
  TAccountUserUnderlyingAta extends string = string,
  TAccountUserLpAta extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  gambaState?: Address<TAccountGambaState>;
  pool: Address<TAccountPool>;
  poolUnderlyingTokenAccount?: Address<TAccountPoolUnderlyingTokenAccount>;
  lpMint?: Address<TAccountLpMint>;
  underlyingTokenMint: Address<TAccountUnderlyingTokenMint>;
  userUnderlyingAta: Address<TAccountUserUnderlyingAta>;
  userLpAta: Address<TAccountUserLpAta>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  amount: PoolDepositInstructionDataArgs['amount'];
};

export async function getPoolDepositInstructionAsync<
  TAccountUser extends string,
  TAccountGambaState extends string,
  TAccountPool extends string,
  TAccountPoolUnderlyingTokenAccount extends string,
  TAccountLpMint extends string,
  TAccountUnderlyingTokenMint extends string,
  TAccountUserUnderlyingAta extends string,
  TAccountUserLpAta extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PoolDepositAsyncInput<
    TAccountUser,
    TAccountGambaState,
    TAccountPool,
    TAccountPoolUnderlyingTokenAccount,
    TAccountLpMint,
    TAccountUnderlyingTokenMint,
    TAccountUserUnderlyingAta,
    TAccountUserLpAta,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  PoolDepositInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountGambaState,
    TAccountPool,
    TAccountPoolUnderlyingTokenAccount,
    TAccountLpMint,
    TAccountUnderlyingTokenMint,
    TAccountUserUnderlyingAta,
    TAccountUserLpAta,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    poolUnderlyingTokenAccount: {
      value: input.poolUnderlyingTokenAccount ?? null,
      isWritable: true,
    },
    lpMint: { value: input.lpMint ?? null, isWritable: true },
    underlyingTokenMint: {
      value: input.underlyingTokenMint ?? null,
      isWritable: false,
    },
    userUnderlyingAta: {
      value: input.userUnderlyingAta ?? null,
      isWritable: true,
    },
    userLpAta: { value: input.userLpAta ?? null, isWritable: true },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69, 34])
        ),
      ],
    });
  }
  if (!accounts.poolUnderlyingTokenAccount.value) {
    accounts.poolUnderlyingTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 80, 79, 79, 76, 95, 65, 84, 65, 34])
        ),
        getAddressEncoder().encode(expectAddress(accounts.pool.value)),
      ],
    });
  }
  if (!accounts.lpMint.value) {
    accounts.lpMint.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            34, 80, 79, 79, 76, 95, 76, 80, 95, 77, 73, 78, 84, 34,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.pool.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.poolUnderlyingTokenAccount),
      getAccountMeta(accounts.lpMint),
      getAccountMeta(accounts.underlyingTokenMint),
      getAccountMeta(accounts.userUnderlyingAta),
      getAccountMeta(accounts.userLpAta),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getPoolDepositInstructionDataEncoder().encode(
      args as PoolDepositInstructionDataArgs
    ),
  } as PoolDepositInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountGambaState,
    TAccountPool,
    TAccountPoolUnderlyingTokenAccount,
    TAccountLpMint,
    TAccountUnderlyingTokenMint,
    TAccountUserUnderlyingAta,
    TAccountUserLpAta,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >;

  return instruction;
}

export type PoolDepositInput<
  TAccountUser extends string = string,
  TAccountGambaState extends string = string,
  TAccountPool extends string = string,
  TAccountPoolUnderlyingTokenAccount extends string = string,
  TAccountLpMint extends string = string,
  TAccountUnderlyingTokenMint extends string = string,
  TAccountUserUnderlyingAta extends string = string,
  TAccountUserLpAta extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  gambaState: Address<TAccountGambaState>;
  pool: Address<TAccountPool>;
  poolUnderlyingTokenAccount: Address<TAccountPoolUnderlyingTokenAccount>;
  lpMint: Address<TAccountLpMint>;
  underlyingTokenMint: Address<TAccountUnderlyingTokenMint>;
  userUnderlyingAta: Address<TAccountUserUnderlyingAta>;
  userLpAta: Address<TAccountUserLpAta>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  amount: PoolDepositInstructionDataArgs['amount'];
};

export function getPoolDepositInstruction<
  TAccountUser extends string,
  TAccountGambaState extends string,
  TAccountPool extends string,
  TAccountPoolUnderlyingTokenAccount extends string,
  TAccountLpMint extends string,
  TAccountUnderlyingTokenMint extends string,
  TAccountUserUnderlyingAta extends string,
  TAccountUserLpAta extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PoolDepositInput<
    TAccountUser,
    TAccountGambaState,
    TAccountPool,
    TAccountPoolUnderlyingTokenAccount,
    TAccountLpMint,
    TAccountUnderlyingTokenMint,
    TAccountUserUnderlyingAta,
    TAccountUserLpAta,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): PoolDepositInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountGambaState,
  TAccountPool,
  TAccountPoolUnderlyingTokenAccount,
  TAccountLpMint,
  TAccountUnderlyingTokenMint,
  TAccountUserUnderlyingAta,
  TAccountUserLpAta,
  TAccountAssociatedTokenProgram,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    poolUnderlyingTokenAccount: {
      value: input.poolUnderlyingTokenAccount ?? null,
      isWritable: true,
    },
    lpMint: { value: input.lpMint ?? null, isWritable: true },
    underlyingTokenMint: {
      value: input.underlyingTokenMint ?? null,
      isWritable: false,
    },
    userUnderlyingAta: {
      value: input.userUnderlyingAta ?? null,
      isWritable: true,
    },
    userLpAta: { value: input.userLpAta ?? null, isWritable: true },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.poolUnderlyingTokenAccount),
      getAccountMeta(accounts.lpMint),
      getAccountMeta(accounts.underlyingTokenMint),
      getAccountMeta(accounts.userUnderlyingAta),
      getAccountMeta(accounts.userLpAta),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getPoolDepositInstructionDataEncoder().encode(
      args as PoolDepositInstructionDataArgs
    ),
  } as PoolDepositInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountGambaState,
    TAccountPool,
    TAccountPoolUnderlyingTokenAccount,
    TAccountLpMint,
    TAccountUnderlyingTokenMint,
    TAccountUserUnderlyingAta,
    TAccountUserLpAta,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedPoolDepositInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    gambaState: TAccountMetas[1];
    pool: TAccountMetas[2];
    poolUnderlyingTokenAccount: TAccountMetas[3];
    lpMint: TAccountMetas[4];
    underlyingTokenMint: TAccountMetas[5];
    userUnderlyingAta: TAccountMetas[6];
    userLpAta: TAccountMetas[7];
    associatedTokenProgram: TAccountMetas[8];
    tokenProgram: TAccountMetas[9];
    systemProgram: TAccountMetas[10];
  };
  data: PoolDepositInstructionData;
};

export function parsePoolDepositInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedPoolDepositInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      gambaState: getNextAccount(),
      pool: getNextAccount(),
      poolUnderlyingTokenAccount: getNextAccount(),
      lpMint: getNextAccount(),
      underlyingTokenMint: getNextAccount(),
      userUnderlyingAta: getNextAccount(),
      userLpAta: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getPoolDepositInstructionDataDecoder().decode(instruction.data),
  };
}
