/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const POOL_AUTHORITY_CONFIG_DISCRIMINATOR = new Uint8Array([
  58, 12, 184, 118, 14, 99, 110, 17,
]);

export function getPoolAuthorityConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    POOL_AUTHORITY_CONFIG_DISCRIMINATOR
  );
}

export type PoolAuthorityConfigInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountGambaState extends string
        ? ReadonlyAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      ...TRemainingAccounts,
    ]
  >;

export type PoolAuthorityConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  minWager: bigint;
  depositLimit: boolean;
  depositLimitAmount: bigint;
  customPoolFee: boolean;
  customPoolFeeBps: bigint;
  customMexPayout: boolean;
  customMaxPayoutBps: bigint;
  depositWhitelistRequired: boolean;
  depositWhitelistAddress: Address;
};

export type PoolAuthorityConfigInstructionDataArgs = {
  minWager: number | bigint;
  depositLimit: boolean;
  depositLimitAmount: number | bigint;
  customPoolFee: boolean;
  customPoolFeeBps: number | bigint;
  customMexPayout: boolean;
  customMaxPayoutBps: number | bigint;
  depositWhitelistRequired: boolean;
  depositWhitelistAddress: Address;
};

export function getPoolAuthorityConfigInstructionDataEncoder(): FixedSizeEncoder<PoolAuthorityConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['minWager', getU64Encoder()],
      ['depositLimit', getBooleanEncoder()],
      ['depositLimitAmount', getU64Encoder()],
      ['customPoolFee', getBooleanEncoder()],
      ['customPoolFeeBps', getU64Encoder()],
      ['customMexPayout', getBooleanEncoder()],
      ['customMaxPayoutBps', getU64Encoder()],
      ['depositWhitelistRequired', getBooleanEncoder()],
      ['depositWhitelistAddress', getAddressEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: POOL_AUTHORITY_CONFIG_DISCRIMINATOR,
    })
  );
}

export function getPoolAuthorityConfigInstructionDataDecoder(): FixedSizeDecoder<PoolAuthorityConfigInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['minWager', getU64Decoder()],
    ['depositLimit', getBooleanDecoder()],
    ['depositLimitAmount', getU64Decoder()],
    ['customPoolFee', getBooleanDecoder()],
    ['customPoolFeeBps', getU64Decoder()],
    ['customMexPayout', getBooleanDecoder()],
    ['customMaxPayoutBps', getU64Decoder()],
    ['depositWhitelistRequired', getBooleanDecoder()],
    ['depositWhitelistAddress', getAddressDecoder()],
  ]);
}

export function getPoolAuthorityConfigInstructionDataCodec(): FixedSizeCodec<
  PoolAuthorityConfigInstructionDataArgs,
  PoolAuthorityConfigInstructionData
> {
  return combineCodec(
    getPoolAuthorityConfigInstructionDataEncoder(),
    getPoolAuthorityConfigInstructionDataDecoder()
  );
}

export type PoolAuthorityConfigAsyncInput<
  TAccountUser extends string = string,
  TAccountGambaState extends string = string,
  TAccountPool extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  gambaState?: Address<TAccountGambaState>;
  pool: Address<TAccountPool>;
  minWager: PoolAuthorityConfigInstructionDataArgs['minWager'];
  depositLimit: PoolAuthorityConfigInstructionDataArgs['depositLimit'];
  depositLimitAmount: PoolAuthorityConfigInstructionDataArgs['depositLimitAmount'];
  customPoolFee: PoolAuthorityConfigInstructionDataArgs['customPoolFee'];
  customPoolFeeBps: PoolAuthorityConfigInstructionDataArgs['customPoolFeeBps'];
  customMexPayout: PoolAuthorityConfigInstructionDataArgs['customMexPayout'];
  customMaxPayoutBps: PoolAuthorityConfigInstructionDataArgs['customMaxPayoutBps'];
  depositWhitelistRequired: PoolAuthorityConfigInstructionDataArgs['depositWhitelistRequired'];
  depositWhitelistAddress: PoolAuthorityConfigInstructionDataArgs['depositWhitelistAddress'];
};

export async function getPoolAuthorityConfigInstructionAsync<
  TAccountUser extends string,
  TAccountGambaState extends string,
  TAccountPool extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PoolAuthorityConfigAsyncInput<
    TAccountUser,
    TAccountGambaState,
    TAccountPool
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  PoolAuthorityConfigInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountGambaState,
    TAccountPool
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69, 34])
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.pool),
    ],
    programAddress,
    data: getPoolAuthorityConfigInstructionDataEncoder().encode(
      args as PoolAuthorityConfigInstructionDataArgs
    ),
  } as PoolAuthorityConfigInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountGambaState,
    TAccountPool
  >;

  return instruction;
}

export type PoolAuthorityConfigInput<
  TAccountUser extends string = string,
  TAccountGambaState extends string = string,
  TAccountPool extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  gambaState: Address<TAccountGambaState>;
  pool: Address<TAccountPool>;
  minWager: PoolAuthorityConfigInstructionDataArgs['minWager'];
  depositLimit: PoolAuthorityConfigInstructionDataArgs['depositLimit'];
  depositLimitAmount: PoolAuthorityConfigInstructionDataArgs['depositLimitAmount'];
  customPoolFee: PoolAuthorityConfigInstructionDataArgs['customPoolFee'];
  customPoolFeeBps: PoolAuthorityConfigInstructionDataArgs['customPoolFeeBps'];
  customMexPayout: PoolAuthorityConfigInstructionDataArgs['customMexPayout'];
  customMaxPayoutBps: PoolAuthorityConfigInstructionDataArgs['customMaxPayoutBps'];
  depositWhitelistRequired: PoolAuthorityConfigInstructionDataArgs['depositWhitelistRequired'];
  depositWhitelistAddress: PoolAuthorityConfigInstructionDataArgs['depositWhitelistAddress'];
};

export function getPoolAuthorityConfigInstruction<
  TAccountUser extends string,
  TAccountGambaState extends string,
  TAccountPool extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PoolAuthorityConfigInput<
    TAccountUser,
    TAccountGambaState,
    TAccountPool
  >,
  config?: { programAddress?: TProgramAddress }
): PoolAuthorityConfigInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountGambaState,
  TAccountPool
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.pool),
    ],
    programAddress,
    data: getPoolAuthorityConfigInstructionDataEncoder().encode(
      args as PoolAuthorityConfigInstructionDataArgs
    ),
  } as PoolAuthorityConfigInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountGambaState,
    TAccountPool
  >;

  return instruction;
}

export type ParsedPoolAuthorityConfigInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    gambaState: TAccountMetas[1];
    pool: TAccountMetas[2];
  };
  data: PoolAuthorityConfigInstructionData;
};

export function parsePoolAuthorityConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedPoolAuthorityConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      gambaState: getNextAccount(),
      pool: getNextAccount(),
    },
    data: getPoolAuthorityConfigInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
