/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';
import {
  getPoolActionDecoder,
  getPoolActionEncoder,
  type PoolAction,
  type PoolActionArgs,
} from '.';

export type PoolChange = {
  user: Address;
  pool: Address;
  tokenMint: Address;
  action: PoolAction;
  amount: bigint;
  postLiquidity: bigint;
  lpSupply: bigint;
};

export type PoolChangeArgs = {
  user: Address;
  pool: Address;
  tokenMint: Address;
  action: PoolActionArgs;
  amount: number | bigint;
  postLiquidity: number | bigint;
  lpSupply: number | bigint;
};

export function getPoolChangeEncoder(): FixedSizeEncoder<PoolChangeArgs> {
  return getStructEncoder([
    ['user', getAddressEncoder()],
    ['pool', getAddressEncoder()],
    ['tokenMint', getAddressEncoder()],
    ['action', getPoolActionEncoder()],
    ['amount', getU64Encoder()],
    ['postLiquidity', getU64Encoder()],
    ['lpSupply', getU64Encoder()],
  ]);
}

export function getPoolChangeDecoder(): FixedSizeDecoder<PoolChange> {
  return getStructDecoder([
    ['user', getAddressDecoder()],
    ['pool', getAddressDecoder()],
    ['tokenMint', getAddressDecoder()],
    ['action', getPoolActionDecoder()],
    ['amount', getU64Decoder()],
    ['postLiquidity', getU64Decoder()],
    ['lpSupply', getU64Decoder()],
  ]);
}

export function getPoolChangeCodec(): FixedSizeCodec<
  PoolChangeArgs,
  PoolChange
> {
  return combineCodec(getPoolChangeEncoder(), getPoolChangeDecoder());
}
