/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedCreateGameNativeInstruction,
  type ParsedCreateGameSplInstruction,
  type ParsedDistributeNativeInstruction,
  type ParsedDistributeSplInstruction,
  type ParsedGambaConfigInstruction,
  type ParsedJoinGameInstruction,
  type ParsedLeaveGameInstruction,
  type ParsedSelectWinnersInstruction,
} from '../instructions';

export const MULTIPLAYER_PROGRAM_ADDRESS =
  'GambaMyTW8C1NSeFrv2c3KfmX1MSDBF6YbxDeb7dBPxM' as Address<'GambaMyTW8C1NSeFrv2c3KfmX1MSDBF6YbxDeb7dBPxM'>;

export enum MultiplayerAccount {
  GambaState,
  Game,
  PlayerMetadataAccount,
}

export function identifyMultiplayerAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): MultiplayerAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([142, 203, 14, 224, 153, 118, 52, 200])
      ),
      0
    )
  ) {
    return MultiplayerAccount.GambaState;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([27, 90, 166, 125, 74, 100, 121, 18])
      ),
      0
    )
  ) {
    return MultiplayerAccount.Game;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([204, 224, 199, 121, 70, 159, 53, 55])
      ),
      0
    )
  ) {
    return MultiplayerAccount.PlayerMetadataAccount;
  }
  throw new Error(
    'The provided account could not be identified as a multiplayer account.'
  );
}

export enum MultiplayerInstruction {
  CreateGameNative,
  CreateGameSpl,
  DistributeNative,
  DistributeSpl,
  GambaConfig,
  JoinGame,
  LeaveGame,
  SelectWinners,
}

export function identifyMultiplayerInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): MultiplayerInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([14, 237, 122, 202, 102, 88, 48, 75])
      ),
      0
    )
  ) {
    return MultiplayerInstruction.CreateGameNative;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([80, 235, 44, 243, 14, 15, 248, 207])
      ),
      0
    )
  ) {
    return MultiplayerInstruction.CreateGameSpl;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([32, 200, 172, 49, 57, 234, 137, 89])
      ),
      0
    )
  ) {
    return MultiplayerInstruction.DistributeNative;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([93, 24, 158, 238, 198, 173, 215, 228])
      ),
      0
    )
  ) {
    return MultiplayerInstruction.DistributeSpl;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([232, 208, 249, 92, 159, 187, 21, 254])
      ),
      0
    )
  ) {
    return MultiplayerInstruction.GambaConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([107, 112, 18, 38, 56, 173, 60, 128])
      ),
      0
    )
  ) {
    return MultiplayerInstruction.JoinGame;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([218, 226, 6, 0, 243, 34, 125, 201])
      ),
      0
    )
  ) {
    return MultiplayerInstruction.LeaveGame;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([80, 100, 28, 131, 83, 199, 222, 80])
      ),
      0
    )
  ) {
    return MultiplayerInstruction.SelectWinners;
  }
  throw new Error(
    'The provided instruction could not be identified as a multiplayer instruction.'
  );
}

export type ParsedMultiplayerInstruction<
  TProgram extends string = 'GambaMyTW8C1NSeFrv2c3KfmX1MSDBF6YbxDeb7dBPxM',
> =
  | ({
      instructionType: MultiplayerInstruction.CreateGameNative;
    } & ParsedCreateGameNativeInstruction<TProgram>)
  | ({
      instructionType: MultiplayerInstruction.CreateGameSpl;
    } & ParsedCreateGameSplInstruction<TProgram>)
  | ({
      instructionType: MultiplayerInstruction.DistributeNative;
    } & ParsedDistributeNativeInstruction<TProgram>)
  | ({
      instructionType: MultiplayerInstruction.DistributeSpl;
    } & ParsedDistributeSplInstruction<TProgram>)
  | ({
      instructionType: MultiplayerInstruction.GambaConfig;
    } & ParsedGambaConfigInstruction<TProgram>)
  | ({
      instructionType: MultiplayerInstruction.JoinGame;
    } & ParsedJoinGameInstruction<TProgram>)
  | ({
      instructionType: MultiplayerInstruction.LeaveGame;
    } & ParsedLeaveGameInstruction<TProgram>)
  | ({
      instructionType: MultiplayerInstruction.SelectWinners;
    } & ParsedSelectWinnersInstruction<TProgram>);
