/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  getGameStatusDecoder,
  getGameStatusEncoder,
  type GameStatus,
  type GameStatusArgs,
} from '../types';

export const GAME_DISCRIMINATOR = new Uint8Array([
  27, 90, 166, 125, 74, 100, 121, 18,
]);

export function getGameDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(GAME_DISCRIMINATOR);
}

export type Game = {
  discriminator: ReadonlyUint8Array;
  bump: ReadonlyUint8Array;
  nonce: bigint;
  user: Address;
  tokenMint: Address;
  pool: Address;
  status: GameStatus;
  /** SHA256 of coming rng_seed. Available at start of the game */
  nextRngSeedHashed: string;
  /** Is revealed by the RNG after a play */
  rngSeed: string;
  timestamp: bigint;
  creator: Address;
  creatorMeta: string;
  wager: bigint;
  underlyingUsed: bigint;
  bonusUsed: bigint;
  creatorFee: bigint;
  gambaFee: bigint;
  poolFee: bigint;
  jackpotFee: bigint;
  jackpotResult: bigint;
  jackpotProbabilityUbps: bigint;
  jackpotPayout: bigint;
  clientSeed: string;
  bet: Array<number>;
  result: bigint;
  points: boolean;
  pointsAuthority: Address;
  metadata: string;
};

export type GameArgs = {
  bump: ReadonlyUint8Array;
  nonce: number | bigint;
  user: Address;
  tokenMint: Address;
  pool: Address;
  status: GameStatusArgs;
  /** SHA256 of coming rng_seed. Available at start of the game */
  nextRngSeedHashed: string;
  /** Is revealed by the RNG after a play */
  rngSeed: string;
  timestamp: number | bigint;
  creator: Address;
  creatorMeta: string;
  wager: number | bigint;
  underlyingUsed: number | bigint;
  bonusUsed: number | bigint;
  creatorFee: number | bigint;
  gambaFee: number | bigint;
  poolFee: number | bigint;
  jackpotFee: number | bigint;
  jackpotResult: number | bigint;
  jackpotProbabilityUbps: number | bigint;
  jackpotPayout: number | bigint;
  clientSeed: string;
  bet: Array<number>;
  result: number | bigint;
  points: boolean;
  pointsAuthority: Address;
  metadata: string;
};

export function getGameEncoder(): Encoder<GameArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['bump', fixEncoderSize(getBytesEncoder(), 1)],
      ['nonce', getU64Encoder()],
      ['user', getAddressEncoder()],
      ['tokenMint', getAddressEncoder()],
      ['pool', getAddressEncoder()],
      ['status', getGameStatusEncoder()],
      [
        'nextRngSeedHashed',
        addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()),
      ],
      ['rngSeed', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ['timestamp', getI64Encoder()],
      ['creator', getAddressEncoder()],
      ['creatorMeta', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ['wager', getU64Encoder()],
      ['underlyingUsed', getU64Encoder()],
      ['bonusUsed', getU64Encoder()],
      ['creatorFee', getU64Encoder()],
      ['gambaFee', getU64Encoder()],
      ['poolFee', getU64Encoder()],
      ['jackpotFee', getU64Encoder()],
      ['jackpotResult', getU64Encoder()],
      ['jackpotProbabilityUbps', getU64Encoder()],
      ['jackpotPayout', getU64Encoder()],
      ['clientSeed', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ['bet', getArrayEncoder(getU32Encoder())],
      ['result', getU64Encoder()],
      ['points', getBooleanEncoder()],
      ['pointsAuthority', getAddressEncoder()],
      ['metadata', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: GAME_DISCRIMINATOR })
  );
}

export function getGameDecoder(): Decoder<Game> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['bump', fixDecoderSize(getBytesDecoder(), 1)],
    ['nonce', getU64Decoder()],
    ['user', getAddressDecoder()],
    ['tokenMint', getAddressDecoder()],
    ['pool', getAddressDecoder()],
    ['status', getGameStatusDecoder()],
    [
      'nextRngSeedHashed',
      addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder()),
    ],
    ['rngSeed', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['timestamp', getI64Decoder()],
    ['creator', getAddressDecoder()],
    ['creatorMeta', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['wager', getU64Decoder()],
    ['underlyingUsed', getU64Decoder()],
    ['bonusUsed', getU64Decoder()],
    ['creatorFee', getU64Decoder()],
    ['gambaFee', getU64Decoder()],
    ['poolFee', getU64Decoder()],
    ['jackpotFee', getU64Decoder()],
    ['jackpotResult', getU64Decoder()],
    ['jackpotProbabilityUbps', getU64Decoder()],
    ['jackpotPayout', getU64Decoder()],
    ['clientSeed', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['bet', getArrayDecoder(getU32Decoder())],
    ['result', getU64Decoder()],
    ['points', getBooleanDecoder()],
    ['pointsAuthority', getAddressDecoder()],
    ['metadata', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getGameCodec(): Codec<GameArgs, Game> {
  return combineCodec(getGameEncoder(), getGameDecoder());
}

export function decodeGame<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Game, TAddress>;
export function decodeGame<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Game, TAddress>;
export function decodeGame<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Game, TAddress> | MaybeAccount<Game, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getGameDecoder()
  );
}

export async function fetchGame<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Game, TAddress>> {
  const maybeAccount = await fetchMaybeGame(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeGame<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Game, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeGame(maybeAccount);
}

export async function fetchAllGame(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Game>[]> {
  const maybeAccounts = await fetchAllMaybeGame(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeGame(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Game>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeGame(maybeAccount));
}
