/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const PLAYER_DISCRIMINATOR = new Uint8Array([
  205, 222, 112, 7, 165, 155, 206, 218,
]);

export function getPlayerDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(PLAYER_DISCRIMINATOR);
}

export type Player = {
  discriminator: ReadonlyUint8Array;
  bump: ReadonlyUint8Array;
  user: Address;
  nonce: bigint;
};

export type PlayerArgs = {
  bump: ReadonlyUint8Array;
  user: Address;
  nonce: number | bigint;
};

export function getPlayerEncoder(): FixedSizeEncoder<PlayerArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['bump', fixEncoderSize(getBytesEncoder(), 1)],
      ['user', getAddressEncoder()],
      ['nonce', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: PLAYER_DISCRIMINATOR })
  );
}

export function getPlayerDecoder(): FixedSizeDecoder<Player> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['bump', fixDecoderSize(getBytesDecoder(), 1)],
    ['user', getAddressDecoder()],
    ['nonce', getU64Decoder()],
  ]);
}

export function getPlayerCodec(): FixedSizeCodec<PlayerArgs, Player> {
  return combineCodec(getPlayerEncoder(), getPlayerDecoder());
}

export function decodePlayer<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Player, TAddress>;
export function decodePlayer<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Player, TAddress>;
export function decodePlayer<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Player, TAddress> | MaybeAccount<Player, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getPlayerDecoder()
  );
}

export async function fetchPlayer<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Player, TAddress>> {
  const maybeAccount = await fetchMaybePlayer(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybePlayer<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Player, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodePlayer(maybeAccount);
}

export async function fetchAllPlayer(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Player>[]> {
  const maybeAccounts = await fetchAllMaybePlayer(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybePlayer(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Player>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodePlayer(maybeAccount));
}

export function getPlayerSize(): number {
  return 49;
}
