/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedDistributeFeesInstruction,
  type ParsedGambaInitializeInstruction,
  type ParsedGambaSetAuthorityInstruction,
  type ParsedGambaSetConfigInstruction,
  type ParsedPlayGameInstruction,
  type ParsedPlayerClaimInstruction,
  type ParsedPlayerCloseInstruction,
  type ParsedPlayerInitializeInstruction,
  type ParsedPoolAuthorityConfigInstruction,
  type ParsedPoolDepositInstruction,
  type ParsedPoolGambaConfigInstruction,
  type ParsedPoolInitializeInstruction,
  type ParsedPoolMintBonusTokensInstruction,
  type ParsedPoolWithdrawInstruction,
  type ParsedRngProvideHashedSeedInstruction,
  type ParsedRngSettleInstruction,
} from '../instructions';

export const GAMBA_PROGRAM_ADDRESS =
  'Gamba2hK6KV3quKq854B3sQG1WMdq3zgQLPKqyK4qS18' as Address<'Gamba2hK6KV3quKq854B3sQG1WMdq3zgQLPKqyK4qS18'>;

export enum GambaAccount {
  Game,
  Player,
  Pool,
  GambaState,
}

export function identifyGambaAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): GambaAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([27, 90, 166, 125, 74, 100, 121, 18])
      ),
      0
    )
  ) {
    return GambaAccount.Game;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([205, 222, 112, 7, 165, 155, 206, 218])
      ),
      0
    )
  ) {
    return GambaAccount.Player;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([241, 154, 109, 4, 17, 177, 109, 188])
      ),
      0
    )
  ) {
    return GambaAccount.Pool;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([142, 203, 14, 224, 153, 118, 52, 200])
      ),
      0
    )
  ) {
    return GambaAccount.GambaState;
  }
  throw new Error(
    'The provided account could not be identified as a gamba account.'
  );
}

export enum GambaInstruction {
  GambaInitialize,
  GambaSetAuthority,
  GambaSetConfig,
  PoolInitialize,
  PoolDeposit,
  PoolWithdraw,
  PoolMintBonusTokens,
  PoolAuthorityConfig,
  PoolGambaConfig,
  PlayerInitialize,
  PlayGame,
  PlayerClose,
  PlayerClaim,
  RngSettle,
  RngProvideHashedSeed,
  DistributeFees,
}

export function identifyGambaInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): GambaInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([255, 140, 190, 102, 152, 30, 179, 112])
      ),
      0
    )
  ) {
    return GambaInstruction.GambaInitialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([60, 11, 159, 59, 150, 12, 106, 78])
      ),
      0
    )
  ) {
    return GambaInstruction.GambaSetAuthority;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([205, 11, 209, 24, 204, 47, 25, 186])
      ),
      0
    )
  ) {
    return GambaInstruction.GambaSetConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([37, 10, 195, 69, 4, 213, 88, 173])
      ),
      0
    )
  ) {
    return GambaInstruction.PoolInitialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([26, 109, 164, 79, 207, 145, 204, 217])
      ),
      0
    )
  ) {
    return GambaInstruction.PoolDeposit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([50, 1, 23, 25, 135, 221, 159, 182])
      ),
      0
    )
  ) {
    return GambaInstruction.PoolWithdraw;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([105, 130, 72, 25, 88, 185, 100, 55])
      ),
      0
    )
  ) {
    return GambaInstruction.PoolMintBonusTokens;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([58, 12, 184, 118, 14, 99, 110, 17])
      ),
      0
    )
  ) {
    return GambaInstruction.PoolAuthorityConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([197, 177, 234, 111, 246, 248, 20, 155])
      ),
      0
    )
  ) {
    return GambaInstruction.PoolGambaConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([213, 160, 145, 88, 197, 68, 63, 150])
      ),
      0
    )
  ) {
    return GambaInstruction.PlayerInitialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([37, 88, 207, 85, 42, 144, 122, 197])
      ),
      0
    )
  ) {
    return GambaInstruction.PlayGame;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([26, 155, 61, 179, 53, 157, 80, 30])
      ),
      0
    )
  ) {
    return GambaInstruction.PlayerClose;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([188, 220, 237, 31, 181, 18, 85, 45])
      ),
      0
    )
  ) {
    return GambaInstruction.PlayerClaim;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([23, 35, 236, 185, 14, 171, 26, 222])
      ),
      0
    )
  ) {
    return GambaInstruction.RngSettle;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([238, 154, 25, 143, 191, 19, 25, 224])
      ),
      0
    )
  ) {
    return GambaInstruction.RngProvideHashedSeed;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([120, 56, 27, 7, 53, 176, 113, 186])
      ),
      0
    )
  ) {
    return GambaInstruction.DistributeFees;
  }
  throw new Error(
    'The provided instruction could not be identified as a gamba instruction.'
  );
}

export type ParsedGambaInstruction<
  TProgram extends string = 'Gamba2hK6KV3quKq854B3sQG1WMdq3zgQLPKqyK4qS18',
> =
  | ({
      instructionType: GambaInstruction.GambaInitialize;
    } & ParsedGambaInitializeInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.GambaSetAuthority;
    } & ParsedGambaSetAuthorityInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.GambaSetConfig;
    } & ParsedGambaSetConfigInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.PoolInitialize;
    } & ParsedPoolInitializeInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.PoolDeposit;
    } & ParsedPoolDepositInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.PoolWithdraw;
    } & ParsedPoolWithdrawInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.PoolMintBonusTokens;
    } & ParsedPoolMintBonusTokensInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.PoolAuthorityConfig;
    } & ParsedPoolAuthorityConfigInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.PoolGambaConfig;
    } & ParsedPoolGambaConfigInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.PlayerInitialize;
    } & ParsedPlayerInitializeInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.PlayGame;
    } & ParsedPlayGameInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.PlayerClose;
    } & ParsedPlayerCloseInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.PlayerClaim;
    } & ParsedPlayerClaimInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.RngSettle;
    } & ParsedRngSettleInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.RngProvideHashedSeed;
    } & ParsedRngProvideHashedSeedInstruction<TProgram>)
  | ({
      instructionType: GambaInstruction.DistributeFees;
    } & ParsedDistributeFeesInstruction<TProgram>);
