/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from '@solana/kit';

export type MetadataEntry = { player: Address; meta: ReadonlyUint8Array };

export type MetadataEntryArgs = MetadataEntry;

export function getMetadataEntryEncoder(): FixedSizeEncoder<MetadataEntryArgs> {
  return getStructEncoder([
    ['player', getAddressEncoder()],
    ['meta', fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

export function getMetadataEntryDecoder(): FixedSizeDecoder<MetadataEntry> {
  return getStructDecoder([
    ['player', getAddressDecoder()],
    ['meta', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getMetadataEntryCodec(): FixedSizeCodec<
  MetadataEntryArgs,
  MetadataEntry
> {
  return combineCodec(getMetadataEntryEncoder(), getMetadataEntryDecoder());
}
