/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type Player = {
  creatorAddress: Address;
  user: Address;
  creatorFeeAmount: bigint;
  gambaFeeAmount: bigint;
  wager: bigint;
  pendingPayout: bigint;
  team: number;
};

export type PlayerArgs = {
  creatorAddress: Address;
  user: Address;
  creatorFeeAmount: number | bigint;
  gambaFeeAmount: number | bigint;
  wager: number | bigint;
  pendingPayout: number | bigint;
  team: number;
};

export function getPlayerEncoder(): FixedSizeEncoder<PlayerArgs> {
  return getStructEncoder([
    ['creatorAddress', getAddressEncoder()],
    ['user', getAddressEncoder()],
    ['creatorFeeAmount', getU64Encoder()],
    ['gambaFeeAmount', getU64Encoder()],
    ['wager', getU64Encoder()],
    ['pendingPayout', getU64Encoder()],
    ['team', getU8Encoder()],
  ]);
}

export function getPlayerDecoder(): FixedSizeDecoder<Player> {
  return getStructDecoder([
    ['creatorAddress', getAddressDecoder()],
    ['user', getAddressDecoder()],
    ['creatorFeeAmount', getU64Decoder()],
    ['gambaFeeAmount', getU64Decoder()],
    ['wager', getU64Decoder()],
    ['pendingPayout', getU64Decoder()],
    ['team', getU8Decoder()],
  ]);
}

export function getPlayerCodec(): FixedSizeCodec<PlayerArgs, Player> {
  return combineCodec(getPlayerEncoder(), getPlayerDecoder());
}
