/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type PlayerJoined = {
  gameId: bigint;
  gameAccount: Address;
  player: Address;
  wager: bigint;
  creatorFee: bigint;
  mint: Address;
  gameType: number;
  team: number;
};

export type PlayerJoinedArgs = {
  gameId: number | bigint;
  gameAccount: Address;
  player: Address;
  wager: number | bigint;
  creatorFee: number | bigint;
  mint: Address;
  gameType: number;
  team: number;
};

export function getPlayerJoinedEncoder(): FixedSizeEncoder<PlayerJoinedArgs> {
  return getStructEncoder([
    ['gameId', getU64Encoder()],
    ['gameAccount', getAddressEncoder()],
    ['player', getAddressEncoder()],
    ['wager', getU64Encoder()],
    ['creatorFee', getU64Encoder()],
    ['mint', getAddressEncoder()],
    ['gameType', getU8Encoder()],
    ['team', getU8Encoder()],
  ]);
}

export function getPlayerJoinedDecoder(): FixedSizeDecoder<PlayerJoined> {
  return getStructDecoder([
    ['gameId', getU64Decoder()],
    ['gameAccount', getAddressDecoder()],
    ['player', getAddressDecoder()],
    ['wager', getU64Decoder()],
    ['creatorFee', getU64Decoder()],
    ['mint', getAddressDecoder()],
    ['gameType', getU8Decoder()],
    ['team', getU8Decoder()],
  ]);
}

export function getPlayerJoinedCodec(): FixedSizeCodec<
  PlayerJoinedArgs,
  PlayerJoined
> {
  return combineCodec(getPlayerJoinedEncoder(), getPlayerJoinedDecoder());
}
