/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type PlayerLeft = {
  gameId: bigint;
  gameAccount: Address;
  player: Address;
};

export type PlayerLeftArgs = {
  gameId: number | bigint;
  gameAccount: Address;
  player: Address;
};

export function getPlayerLeftEncoder(): FixedSizeEncoder<PlayerLeftArgs> {
  return getStructEncoder([
    ['gameId', getU64Encoder()],
    ['gameAccount', getAddressEncoder()],
    ['player', getAddressEncoder()],
  ]);
}

export function getPlayerLeftDecoder(): FixedSizeDecoder<PlayerLeft> {
  return getStructDecoder([
    ['gameId', getU64Decoder()],
    ['gameAccount', getAddressDecoder()],
    ['player', getAddressDecoder()],
  ]);
}

export function getPlayerLeftCodec(): FixedSizeCodec<
  PlayerLeftArgs,
  PlayerLeft
> {
  return combineCodec(getPlayerLeftEncoder(), getPlayerLeftDecoder());
}
