/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type WinnersSelected = {
  gameId: bigint;
  gameAccount: Address;
  gameMaker: Address;
  maxPlayers: number;
  winnerIndexes: Array<number>;
  winnerWagers: Array<bigint>;
  payouts: Array<bigint>;
  totalWager: bigint;
  playersSample: Array<Address>;
};

export type WinnersSelectedArgs = {
  gameId: number | bigint;
  gameAccount: Address;
  gameMaker: Address;
  maxPlayers: number;
  winnerIndexes: Array<number>;
  winnerWagers: Array<number | bigint>;
  payouts: Array<number | bigint>;
  totalWager: number | bigint;
  playersSample: Array<Address>;
};

export function getWinnersSelectedEncoder(): Encoder<WinnersSelectedArgs> {
  return getStructEncoder([
    ['gameId', getU64Encoder()],
    ['gameAccount', getAddressEncoder()],
    ['gameMaker', getAddressEncoder()],
    ['maxPlayers', getU16Encoder()],
    ['winnerIndexes', getArrayEncoder(getU16Encoder())],
    ['winnerWagers', getArrayEncoder(getU64Encoder())],
    ['payouts', getArrayEncoder(getU64Encoder())],
    ['totalWager', getU64Encoder()],
    ['playersSample', getArrayEncoder(getAddressEncoder())],
  ]);
}

export function getWinnersSelectedDecoder(): Decoder<WinnersSelected> {
  return getStructDecoder([
    ['gameId', getU64Decoder()],
    ['gameAccount', getAddressDecoder()],
    ['gameMaker', getAddressDecoder()],
    ['maxPlayers', getU16Decoder()],
    ['winnerIndexes', getArrayDecoder(getU16Decoder())],
    ['winnerWagers', getArrayDecoder(getU64Decoder())],
    ['payouts', getArrayDecoder(getU64Decoder())],
    ['totalWager', getU64Decoder()],
    ['playersSample', getArrayDecoder(getAddressDecoder())],
  ]);
}

export function getWinnersSelectedCodec(): Codec<
  WinnersSelectedArgs,
  WinnersSelected
> {
  return combineCodec(getWinnersSelectedEncoder(), getWinnersSelectedDecoder());
}
