/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum GambaStateError {
  PlaysNotAllowed,
  DepositNotAllowed,
  WithdrawalNotAllowed,
  PoolCreationNotAllowed,
  DepositLimitExceeded,
  DepositWhitelistRequired,
}

export type GambaStateErrorArgs = GambaStateError;

export function getGambaStateErrorEncoder(): FixedSizeEncoder<GambaStateErrorArgs> {
  return getEnumEncoder(GambaStateError);
}

export function getGambaStateErrorDecoder(): FixedSizeDecoder<GambaStateError> {
  return getEnumDecoder(GambaStateError);
}

export function getGambaStateErrorCodec(): FixedSizeCodec<
  GambaStateErrorArgs,
  GambaStateError
> {
  return combineCodec(getGambaStateErrorEncoder(), getGambaStateErrorDecoder());
}
