/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum GameStatus {
  None,
  NotInitialized,
  Ready,
  ResultRequested,
}

export type GameStatusArgs = GameStatus;

export function getGameStatusEncoder(): FixedSizeEncoder<GameStatusArgs> {
  return getEnumEncoder(GameStatus);
}

export function getGameStatusDecoder(): FixedSizeDecoder<GameStatus> {
  return getEnumDecoder(GameStatus);
}

export function getGameStatusCodec(): FixedSizeCodec<
  GameStatusArgs,
  GameStatus
> {
  return combineCodec(getGameStatusEncoder(), getGameStatusDecoder());
}
