/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type GameSettled = {
  user: Address;
  pool: Address;
  tokenMint: Address;
  creator: Address;
  creatorFee: bigint;
  gambaFee: bigint;
  poolFee: bigint;
  jackpotFee: bigint;
  underlyingUsed: bigint;
  bonusUsed: bigint;
  wager: bigint;
  payout: bigint;
  multiplierBps: number;
  payoutFromBonusPool: bigint;
  payoutFromNormalPool: bigint;
  jackpotProbabilityUbps: bigint;
  jackpotResult: bigint;
  nonce: bigint;
  clientSeed: string;
  resultIndex: bigint;
  bet: Array<number>;
  jackpotPayoutToUser: bigint;
  poolLiquidity: bigint;
  rngSeed: string;
  nextRngSeedHashed: string;
  metadata: string;
};

export type GameSettledArgs = {
  user: Address;
  pool: Address;
  tokenMint: Address;
  creator: Address;
  creatorFee: number | bigint;
  gambaFee: number | bigint;
  poolFee: number | bigint;
  jackpotFee: number | bigint;
  underlyingUsed: number | bigint;
  bonusUsed: number | bigint;
  wager: number | bigint;
  payout: number | bigint;
  multiplierBps: number;
  payoutFromBonusPool: number | bigint;
  payoutFromNormalPool: number | bigint;
  jackpotProbabilityUbps: number | bigint;
  jackpotResult: number | bigint;
  nonce: number | bigint;
  clientSeed: string;
  resultIndex: number | bigint;
  bet: Array<number>;
  jackpotPayoutToUser: number | bigint;
  poolLiquidity: number | bigint;
  rngSeed: string;
  nextRngSeedHashed: string;
  metadata: string;
};

export function getGameSettledEncoder(): Encoder<GameSettledArgs> {
  return getStructEncoder([
    ['user', getAddressEncoder()],
    ['pool', getAddressEncoder()],
    ['tokenMint', getAddressEncoder()],
    ['creator', getAddressEncoder()],
    ['creatorFee', getU64Encoder()],
    ['gambaFee', getU64Encoder()],
    ['poolFee', getU64Encoder()],
    ['jackpotFee', getU64Encoder()],
    ['underlyingUsed', getU64Encoder()],
    ['bonusUsed', getU64Encoder()],
    ['wager', getU64Encoder()],
    ['payout', getU64Encoder()],
    ['multiplierBps', getU32Encoder()],
    ['payoutFromBonusPool', getU64Encoder()],
    ['payoutFromNormalPool', getU64Encoder()],
    ['jackpotProbabilityUbps', getU64Encoder()],
    ['jackpotResult', getU64Encoder()],
    ['nonce', getU64Encoder()],
    ['clientSeed', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ['resultIndex', getU64Encoder()],
    ['bet', getArrayEncoder(getU32Encoder())],
    ['jackpotPayoutToUser', getU64Encoder()],
    ['poolLiquidity', getU64Encoder()],
    ['rngSeed', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    [
      'nextRngSeedHashed',
      addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder()),
    ],
    ['metadata', addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
  ]);
}

export function getGameSettledDecoder(): Decoder<GameSettled> {
  return getStructDecoder([
    ['user', getAddressDecoder()],
    ['pool', getAddressDecoder()],
    ['tokenMint', getAddressDecoder()],
    ['creator', getAddressDecoder()],
    ['creatorFee', getU64Decoder()],
    ['gambaFee', getU64Decoder()],
    ['poolFee', getU64Decoder()],
    ['jackpotFee', getU64Decoder()],
    ['underlyingUsed', getU64Decoder()],
    ['bonusUsed', getU64Decoder()],
    ['wager', getU64Decoder()],
    ['payout', getU64Decoder()],
    ['multiplierBps', getU32Decoder()],
    ['payoutFromBonusPool', getU64Decoder()],
    ['payoutFromNormalPool', getU64Decoder()],
    ['jackpotProbabilityUbps', getU64Decoder()],
    ['jackpotResult', getU64Decoder()],
    ['nonce', getU64Decoder()],
    ['clientSeed', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ['resultIndex', getU64Decoder()],
    ['bet', getArrayDecoder(getU32Decoder())],
    ['jackpotPayoutToUser', getU64Decoder()],
    ['poolLiquidity', getU64Decoder()],
    ['rngSeed', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    [
      'nextRngSeedHashed',
      addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder()),
    ],
    ['metadata', addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getGameSettledCodec(): Codec<GameSettledArgs, GameSettled> {
  return combineCodec(getGameSettledEncoder(), getGameSettledDecoder());
}
