/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum PlayerError {
  NotReadyToPlay,
  CreatorFeeTooHigh,
  WagerTooSmall,
  TooFewBetOutcomes,
  TooManyBetOutcomes,
  PlayerAdvantage,
  HouseAdvantageTooHigh,
  MaxPayoutExceeded,
}

export type PlayerErrorArgs = PlayerError;

export function getPlayerErrorEncoder(): FixedSizeEncoder<PlayerErrorArgs> {
  return getEnumEncoder(PlayerError);
}

export function getPlayerErrorDecoder(): FixedSizeDecoder<PlayerError> {
  return getEnumDecoder(PlayerError);
}

export function getPlayerErrorCodec(): FixedSizeCodec<
  PlayerErrorArgs,
  PlayerError
> {
  return combineCodec(getPlayerErrorEncoder(), getPlayerErrorDecoder());
}
