/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type PoolCreated = {
  user: Address;
  authority: Address;
  pool: Address;
  tokenMint: Address;
};

export type PoolCreatedArgs = PoolCreated;

export function getPoolCreatedEncoder(): FixedSizeEncoder<PoolCreatedArgs> {
  return getStructEncoder([
    ['user', getAddressEncoder()],
    ['authority', getAddressEncoder()],
    ['pool', getAddressEncoder()],
    ['tokenMint', getAddressEncoder()],
  ]);
}

export function getPoolCreatedDecoder(): FixedSizeDecoder<PoolCreated> {
  return getStructDecoder([
    ['user', getAddressDecoder()],
    ['authority', getAddressDecoder()],
    ['pool', getAddressDecoder()],
    ['tokenMint', getAddressDecoder()],
  ]);
}

export function getPoolCreatedCodec(): FixedSizeCodec<
  PoolCreatedArgs,
  PoolCreated
> {
  return combineCodec(getPoolCreatedEncoder(), getPoolCreatedDecoder());
}
