/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum PoolAction {
  Deposit,
  Withdraw,
}

export type PoolActionArgs = PoolAction;

export function getPoolActionEncoder(): FixedSizeEncoder<PoolActionArgs> {
  return getEnumEncoder(PoolAction);
}

export function getPoolActionDecoder(): FixedSizeDecoder<PoolAction> {
  return getEnumDecoder(PoolAction);
}

export function getPoolActionCodec(): FixedSizeCodec<
  PoolActionArgs,
  PoolAction
> {
  return combineCodec(getPoolActionEncoder(), getPoolActionDecoder());
}
