/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export enum RngError {
  Generic,
  InitialHashedSeedAlreadyProvided,
  IncorrectRngSeed,
  ResultNotRequested,
}

export type RngErrorArgs = RngError;

export function getRngErrorEncoder(): FixedSizeEncoder<RngErrorArgs> {
  return getEnumEncoder(RngError);
}

export function getRngErrorDecoder(): FixedSizeDecoder<RngError> {
  return getEnumDecoder(RngError);
}

export function getRngErrorCodec(): FixedSizeCodec<RngErrorArgs, RngError> {
  return combineCodec(getRngErrorEncoder(), getRngErrorDecoder());
}
