/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { MULTIPLAYER_PROGRAM_ADDRESS } from '../programs';

/** PlayerAlreadyInGame: Player is already in the game */
export const MULTIPLAYER_ERROR__PLAYER_ALREADY_IN_GAME = 0x1770; // 6000
/** PlayerNotInGame: Player is not in the game */
export const MULTIPLAYER_ERROR__PLAYER_NOT_IN_GAME = 0x1771; // 6001
/** GameInProgress: Game is already in progress */
export const MULTIPLAYER_ERROR__GAME_IN_PROGRESS = 0x1772; // 6002
/** InvalidGameAccount: Invalid game account */
export const MULTIPLAYER_ERROR__INVALID_GAME_ACCOUNT = 0x1773; // 6003
/** CannotSettleYet: Cannot settle yet */
export const MULTIPLAYER_ERROR__CANNOT_SETTLE_YET = 0x1774; // 6004
/** AuthorityMismatch: Signer / authority mismatch */
export const MULTIPLAYER_ERROR__AUTHORITY_MISMATCH = 0x1775; // 6005
/** InvalidInput: Invalid input */
export const MULTIPLAYER_ERROR__INVALID_INPUT = 0x1776; // 6006
/** AlreadySettled: Game already settled */
export const MULTIPLAYER_ERROR__ALREADY_SETTLED = 0x1777; // 6007
/** NumericalOverflow: numerical overflow */
export const MULTIPLAYER_ERROR__NUMERICAL_OVERFLOW = 0x1778; // 6008
/** CreatorMismatch: Creator Missmatch */
export const MULTIPLAYER_ERROR__CREATOR_MISMATCH = 0x1779; // 6009
/** PlayerMismatch: player rmismatch */
export const MULTIPLAYER_ERROR__PLAYER_MISMATCH = 0x177a; // 6010
/** GameFull: Game is Full */
export const MULTIPLAYER_ERROR__GAME_FULL = 0x177b; // 6011

export type MultiplayerError =
  | typeof MULTIPLAYER_ERROR__ALREADY_SETTLED
  | typeof MULTIPLAYER_ERROR__AUTHORITY_MISMATCH
  | typeof MULTIPLAYER_ERROR__CANNOT_SETTLE_YET
  | typeof MULTIPLAYER_ERROR__CREATOR_MISMATCH
  | typeof MULTIPLAYER_ERROR__GAME_FULL
  | typeof MULTIPLAYER_ERROR__GAME_IN_PROGRESS
  | typeof MULTIPLAYER_ERROR__INVALID_GAME_ACCOUNT
  | typeof MULTIPLAYER_ERROR__INVALID_INPUT
  | typeof MULTIPLAYER_ERROR__NUMERICAL_OVERFLOW
  | typeof MULTIPLAYER_ERROR__PLAYER_ALREADY_IN_GAME
  | typeof MULTIPLAYER_ERROR__PLAYER_MISMATCH
  | typeof MULTIPLAYER_ERROR__PLAYER_NOT_IN_GAME;

let multiplayerErrorMessages: Record<MultiplayerError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  multiplayerErrorMessages = {
    [MULTIPLAYER_ERROR__ALREADY_SETTLED]: `Game already settled`,
    [MULTIPLAYER_ERROR__AUTHORITY_MISMATCH]: `Signer / authority mismatch`,
    [MULTIPLAYER_ERROR__CANNOT_SETTLE_YET]: `Cannot settle yet`,
    [MULTIPLAYER_ERROR__CREATOR_MISMATCH]: `Creator Missmatch`,
    [MULTIPLAYER_ERROR__GAME_FULL]: `Game is Full`,
    [MULTIPLAYER_ERROR__GAME_IN_PROGRESS]: `Game is already in progress`,
    [MULTIPLAYER_ERROR__INVALID_GAME_ACCOUNT]: `Invalid game account`,
    [MULTIPLAYER_ERROR__INVALID_INPUT]: `Invalid input`,
    [MULTIPLAYER_ERROR__NUMERICAL_OVERFLOW]: `numerical overflow`,
    [MULTIPLAYER_ERROR__PLAYER_ALREADY_IN_GAME]: `Player is already in the game`,
    [MULTIPLAYER_ERROR__PLAYER_MISMATCH]: `player rmismatch`,
    [MULTIPLAYER_ERROR__PLAYER_NOT_IN_GAME]: `Player is not in the game`,
  };
}

export function getMultiplayerErrorMessage(code: MultiplayerError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (multiplayerErrorMessages as Record<MultiplayerError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isMultiplayerError<TProgramErrorCode extends MultiplayerError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    MULTIPLAYER_PROGRAM_ADDRESS,
    code
  );
}
