/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const POOL_DISCRIMINATOR = new Uint8Array([
  241, 154, 109, 4, 17, 177, 109, 188,
]);

export function getPoolDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(POOL_DISCRIMINATOR);
}

export type Pool = {
  discriminator: ReadonlyUint8Array;
  bump: ReadonlyUint8Array;
  lookupAddress: Address;
  poolAuthority: Address;
  underlyingTokenMint: Address;
  antiSpamFeeExempt: boolean;
  minWager: bigint;
  plays: bigint;
  liquidityCheckpoint: bigint;
  depositLimit: boolean;
  depositLimitAmount: bigint;
  customPoolFee: boolean;
  customPoolFeeBps: bigint;
  customGambaFee: boolean;
  customGambaFeeBps: bigint;
  customMaxPayout: boolean;
  customMaxPayoutBps: bigint;
  customBonusTokenMint: Address;
  customBonusToken: boolean;
  customMaxCreatorFee: boolean;
  customMaxCreatorFeeBps: bigint;
  depositWhitelistRequired: boolean;
  depositWhitelistAddress: Address;
};

export type PoolArgs = {
  bump: ReadonlyUint8Array;
  lookupAddress: Address;
  poolAuthority: Address;
  underlyingTokenMint: Address;
  antiSpamFeeExempt: boolean;
  minWager: number | bigint;
  plays: number | bigint;
  liquidityCheckpoint: number | bigint;
  depositLimit: boolean;
  depositLimitAmount: number | bigint;
  customPoolFee: boolean;
  customPoolFeeBps: number | bigint;
  customGambaFee: boolean;
  customGambaFeeBps: number | bigint;
  customMaxPayout: boolean;
  customMaxPayoutBps: number | bigint;
  customBonusTokenMint: Address;
  customBonusToken: boolean;
  customMaxCreatorFee: boolean;
  customMaxCreatorFeeBps: number | bigint;
  depositWhitelistRequired: boolean;
  depositWhitelistAddress: Address;
};

export function getPoolEncoder(): FixedSizeEncoder<PoolArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['bump', fixEncoderSize(getBytesEncoder(), 1)],
      ['lookupAddress', getAddressEncoder()],
      ['poolAuthority', getAddressEncoder()],
      ['underlyingTokenMint', getAddressEncoder()],
      ['antiSpamFeeExempt', getBooleanEncoder()],
      ['minWager', getU64Encoder()],
      ['plays', getU64Encoder()],
      ['liquidityCheckpoint', getU64Encoder()],
      ['depositLimit', getBooleanEncoder()],
      ['depositLimitAmount', getU64Encoder()],
      ['customPoolFee', getBooleanEncoder()],
      ['customPoolFeeBps', getU64Encoder()],
      ['customGambaFee', getBooleanEncoder()],
      ['customGambaFeeBps', getU64Encoder()],
      ['customMaxPayout', getBooleanEncoder()],
      ['customMaxPayoutBps', getU64Encoder()],
      ['customBonusTokenMint', getAddressEncoder()],
      ['customBonusToken', getBooleanEncoder()],
      ['customMaxCreatorFee', getBooleanEncoder()],
      ['customMaxCreatorFeeBps', getU64Encoder()],
      ['depositWhitelistRequired', getBooleanEncoder()],
      ['depositWhitelistAddress', getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: POOL_DISCRIMINATOR })
  );
}

export function getPoolDecoder(): FixedSizeDecoder<Pool> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['bump', fixDecoderSize(getBytesDecoder(), 1)],
    ['lookupAddress', getAddressDecoder()],
    ['poolAuthority', getAddressDecoder()],
    ['underlyingTokenMint', getAddressDecoder()],
    ['antiSpamFeeExempt', getBooleanDecoder()],
    ['minWager', getU64Decoder()],
    ['plays', getU64Decoder()],
    ['liquidityCheckpoint', getU64Decoder()],
    ['depositLimit', getBooleanDecoder()],
    ['depositLimitAmount', getU64Decoder()],
    ['customPoolFee', getBooleanDecoder()],
    ['customPoolFeeBps', getU64Decoder()],
    ['customGambaFee', getBooleanDecoder()],
    ['customGambaFeeBps', getU64Decoder()],
    ['customMaxPayout', getBooleanDecoder()],
    ['customMaxPayoutBps', getU64Decoder()],
    ['customBonusTokenMint', getAddressDecoder()],
    ['customBonusToken', getBooleanDecoder()],
    ['customMaxCreatorFee', getBooleanDecoder()],
    ['customMaxCreatorFeeBps', getU64Decoder()],
    ['depositWhitelistRequired', getBooleanDecoder()],
    ['depositWhitelistAddress', getAddressDecoder()],
  ]);
}

export function getPoolCodec(): FixedSizeCodec<PoolArgs, Pool> {
  return combineCodec(getPoolEncoder(), getPoolDecoder());
}

export function decodePool<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<Pool, TAddress>;
export function decodePool<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<Pool, TAddress>;
export function decodePool<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<Pool, TAddress> | MaybeAccount<Pool, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getPoolDecoder()
  );
}

export async function fetchPool<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<Pool, TAddress>> {
  const maybeAccount = await fetchMaybePool(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybePool<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<Pool, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodePool(maybeAccount);
}

export async function fetchAllPool(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<Pool>[]> {
  const maybeAccounts = await fetchAllMaybePool(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybePool(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<Pool>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodePool(maybeAccount));
}

export function getPoolSize(): number {
  return 241;
}
