/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const GAMBA_SET_CONFIG_DISCRIMINATOR = new Uint8Array([
  205, 11, 209, 24, 204, 47, 25, 186,
]);

export function getGambaSetConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GAMBA_SET_CONFIG_DISCRIMINATOR
  );
}

export type GambaSetConfigInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountGambaState extends string
        ? WritableAccount<TAccountGambaState>
        : TAccountGambaState,
      ...TRemainingAccounts,
    ]
  >;

export type GambaSetConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  rngAddress: Address;
  gambaFee: bigint;
  maxCreatorFee: bigint;
  poolCreationFee: bigint;
  antiSpamFee: bigint;
  maxHouseEdge: bigint;
  defaultPoolFee: bigint;
  jackpotPayoutToUserBps: bigint;
  jackpotPayoutToCreatorBps: bigint;
  jackpotPayoutToPoolBps: bigint;
  jackpotPayoutToGambaBps: bigint;
  bonusToJackpotRatioBps: bigint;
  maxPayoutBps: bigint;
  poolWithdrawFeeBps: bigint;
  poolCreationAllowed: boolean;
  poolDepositAllowed: boolean;
  poolWithdrawAllowed: boolean;
  playingAllowed: boolean;
  distributionRecipient: Address;
};

export type GambaSetConfigInstructionDataArgs = {
  rngAddress: Address;
  gambaFee: number | bigint;
  maxCreatorFee: number | bigint;
  poolCreationFee: number | bigint;
  antiSpamFee: number | bigint;
  maxHouseEdge: number | bigint;
  defaultPoolFee: number | bigint;
  jackpotPayoutToUserBps: number | bigint;
  jackpotPayoutToCreatorBps: number | bigint;
  jackpotPayoutToPoolBps: number | bigint;
  jackpotPayoutToGambaBps: number | bigint;
  bonusToJackpotRatioBps: number | bigint;
  maxPayoutBps: number | bigint;
  poolWithdrawFeeBps: number | bigint;
  poolCreationAllowed: boolean;
  poolDepositAllowed: boolean;
  poolWithdrawAllowed: boolean;
  playingAllowed: boolean;
  distributionRecipient: Address;
};

export function getGambaSetConfigInstructionDataEncoder(): FixedSizeEncoder<GambaSetConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['rngAddress', getAddressEncoder()],
      ['gambaFee', getU64Encoder()],
      ['maxCreatorFee', getU64Encoder()],
      ['poolCreationFee', getU64Encoder()],
      ['antiSpamFee', getU64Encoder()],
      ['maxHouseEdge', getU64Encoder()],
      ['defaultPoolFee', getU64Encoder()],
      ['jackpotPayoutToUserBps', getU64Encoder()],
      ['jackpotPayoutToCreatorBps', getU64Encoder()],
      ['jackpotPayoutToPoolBps', getU64Encoder()],
      ['jackpotPayoutToGambaBps', getU64Encoder()],
      ['bonusToJackpotRatioBps', getU64Encoder()],
      ['maxPayoutBps', getU64Encoder()],
      ['poolWithdrawFeeBps', getU64Encoder()],
      ['poolCreationAllowed', getBooleanEncoder()],
      ['poolDepositAllowed', getBooleanEncoder()],
      ['poolWithdrawAllowed', getBooleanEncoder()],
      ['playingAllowed', getBooleanEncoder()],
      ['distributionRecipient', getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: GAMBA_SET_CONFIG_DISCRIMINATOR })
  );
}

export function getGambaSetConfigInstructionDataDecoder(): FixedSizeDecoder<GambaSetConfigInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['rngAddress', getAddressDecoder()],
    ['gambaFee', getU64Decoder()],
    ['maxCreatorFee', getU64Decoder()],
    ['poolCreationFee', getU64Decoder()],
    ['antiSpamFee', getU64Decoder()],
    ['maxHouseEdge', getU64Decoder()],
    ['defaultPoolFee', getU64Decoder()],
    ['jackpotPayoutToUserBps', getU64Decoder()],
    ['jackpotPayoutToCreatorBps', getU64Decoder()],
    ['jackpotPayoutToPoolBps', getU64Decoder()],
    ['jackpotPayoutToGambaBps', getU64Decoder()],
    ['bonusToJackpotRatioBps', getU64Decoder()],
    ['maxPayoutBps', getU64Decoder()],
    ['poolWithdrawFeeBps', getU64Decoder()],
    ['poolCreationAllowed', getBooleanDecoder()],
    ['poolDepositAllowed', getBooleanDecoder()],
    ['poolWithdrawAllowed', getBooleanDecoder()],
    ['playingAllowed', getBooleanDecoder()],
    ['distributionRecipient', getAddressDecoder()],
  ]);
}

export function getGambaSetConfigInstructionDataCodec(): FixedSizeCodec<
  GambaSetConfigInstructionDataArgs,
  GambaSetConfigInstructionData
> {
  return combineCodec(
    getGambaSetConfigInstructionDataEncoder(),
    getGambaSetConfigInstructionDataDecoder()
  );
}

export type GambaSetConfigAsyncInput<
  TAccountAuthority extends string = string,
  TAccountGambaState extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  gambaState?: Address<TAccountGambaState>;
  rngAddress: GambaSetConfigInstructionDataArgs['rngAddress'];
  gambaFee: GambaSetConfigInstructionDataArgs['gambaFee'];
  maxCreatorFee: GambaSetConfigInstructionDataArgs['maxCreatorFee'];
  poolCreationFee: GambaSetConfigInstructionDataArgs['poolCreationFee'];
  antiSpamFee: GambaSetConfigInstructionDataArgs['antiSpamFee'];
  maxHouseEdge: GambaSetConfigInstructionDataArgs['maxHouseEdge'];
  defaultPoolFee: GambaSetConfigInstructionDataArgs['defaultPoolFee'];
  jackpotPayoutToUserBps: GambaSetConfigInstructionDataArgs['jackpotPayoutToUserBps'];
  jackpotPayoutToCreatorBps: GambaSetConfigInstructionDataArgs['jackpotPayoutToCreatorBps'];
  jackpotPayoutToPoolBps: GambaSetConfigInstructionDataArgs['jackpotPayoutToPoolBps'];
  jackpotPayoutToGambaBps: GambaSetConfigInstructionDataArgs['jackpotPayoutToGambaBps'];
  bonusToJackpotRatioBps: GambaSetConfigInstructionDataArgs['bonusToJackpotRatioBps'];
  maxPayoutBps: GambaSetConfigInstructionDataArgs['maxPayoutBps'];
  poolWithdrawFeeBps: GambaSetConfigInstructionDataArgs['poolWithdrawFeeBps'];
  poolCreationAllowed: GambaSetConfigInstructionDataArgs['poolCreationAllowed'];
  poolDepositAllowed: GambaSetConfigInstructionDataArgs['poolDepositAllowed'];
  poolWithdrawAllowed: GambaSetConfigInstructionDataArgs['poolWithdrawAllowed'];
  playingAllowed: GambaSetConfigInstructionDataArgs['playingAllowed'];
  distributionRecipient: GambaSetConfigInstructionDataArgs['distributionRecipient'];
};

export async function getGambaSetConfigInstructionAsync<
  TAccountAuthority extends string,
  TAccountGambaState extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: GambaSetConfigAsyncInput<TAccountAuthority, TAccountGambaState>,
  config?: { programAddress?: TProgramAddress }
): Promise<
  GambaSetConfigInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountGambaState
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69, 34])
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.gambaState),
    ],
    programAddress,
    data: getGambaSetConfigInstructionDataEncoder().encode(
      args as GambaSetConfigInstructionDataArgs
    ),
  } as GambaSetConfigInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountGambaState
  >;

  return instruction;
}

export type GambaSetConfigInput<
  TAccountAuthority extends string = string,
  TAccountGambaState extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  gambaState: Address<TAccountGambaState>;
  rngAddress: GambaSetConfigInstructionDataArgs['rngAddress'];
  gambaFee: GambaSetConfigInstructionDataArgs['gambaFee'];
  maxCreatorFee: GambaSetConfigInstructionDataArgs['maxCreatorFee'];
  poolCreationFee: GambaSetConfigInstructionDataArgs['poolCreationFee'];
  antiSpamFee: GambaSetConfigInstructionDataArgs['antiSpamFee'];
  maxHouseEdge: GambaSetConfigInstructionDataArgs['maxHouseEdge'];
  defaultPoolFee: GambaSetConfigInstructionDataArgs['defaultPoolFee'];
  jackpotPayoutToUserBps: GambaSetConfigInstructionDataArgs['jackpotPayoutToUserBps'];
  jackpotPayoutToCreatorBps: GambaSetConfigInstructionDataArgs['jackpotPayoutToCreatorBps'];
  jackpotPayoutToPoolBps: GambaSetConfigInstructionDataArgs['jackpotPayoutToPoolBps'];
  jackpotPayoutToGambaBps: GambaSetConfigInstructionDataArgs['jackpotPayoutToGambaBps'];
  bonusToJackpotRatioBps: GambaSetConfigInstructionDataArgs['bonusToJackpotRatioBps'];
  maxPayoutBps: GambaSetConfigInstructionDataArgs['maxPayoutBps'];
  poolWithdrawFeeBps: GambaSetConfigInstructionDataArgs['poolWithdrawFeeBps'];
  poolCreationAllowed: GambaSetConfigInstructionDataArgs['poolCreationAllowed'];
  poolDepositAllowed: GambaSetConfigInstructionDataArgs['poolDepositAllowed'];
  poolWithdrawAllowed: GambaSetConfigInstructionDataArgs['poolWithdrawAllowed'];
  playingAllowed: GambaSetConfigInstructionDataArgs['playingAllowed'];
  distributionRecipient: GambaSetConfigInstructionDataArgs['distributionRecipient'];
};

export function getGambaSetConfigInstruction<
  TAccountAuthority extends string,
  TAccountGambaState extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: GambaSetConfigInput<TAccountAuthority, TAccountGambaState>,
  config?: { programAddress?: TProgramAddress }
): GambaSetConfigInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountGambaState
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.gambaState),
    ],
    programAddress,
    data: getGambaSetConfigInstructionDataEncoder().encode(
      args as GambaSetConfigInstructionDataArgs
    ),
  } as GambaSetConfigInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountGambaState
  >;

  return instruction;
}

export type ParsedGambaSetConfigInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    gambaState: TAccountMetas[1];
  };
  data: GambaSetConfigInstructionData;
};

export function parseGambaSetConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedGambaSetConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      gambaState: getNextAccount(),
    },
    data: getGambaSetConfigInstructionDataDecoder().decode(instruction.data),
  };
}
