/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const GAMBA_INITIALIZE_DISCRIMINATOR = new Uint8Array([
  255, 140, 190, 102, 152, 30, 179, 112,
]);

export function getGambaInitializeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GAMBA_INITIALIZE_DISCRIMINATOR
  );
}

export type GambaInitializeInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountInitializer extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountInitializer extends string
        ? WritableSignerAccount<TAccountInitializer> &
            AccountSignerMeta<TAccountInitializer>
        : TAccountInitializer,
      TAccountGambaState extends string
        ? WritableAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type GambaInitializeInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type GambaInitializeInstructionDataArgs = {};

export function getGambaInitializeInstructionDataEncoder(): FixedSizeEncoder<GambaInitializeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: GAMBA_INITIALIZE_DISCRIMINATOR })
  );
}

export function getGambaInitializeInstructionDataDecoder(): FixedSizeDecoder<GambaInitializeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getGambaInitializeInstructionDataCodec(): FixedSizeCodec<
  GambaInitializeInstructionDataArgs,
  GambaInitializeInstructionData
> {
  return combineCodec(
    getGambaInitializeInstructionDataEncoder(),
    getGambaInitializeInstructionDataDecoder()
  );
}

export type GambaInitializeAsyncInput<
  TAccountInitializer extends string = string,
  TAccountGambaState extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  initializer: TransactionSigner<TAccountInitializer>;
  gambaState?: Address<TAccountGambaState>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getGambaInitializeInstructionAsync<
  TAccountInitializer extends string,
  TAccountGambaState extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: GambaInitializeAsyncInput<
    TAccountInitializer,
    TAccountGambaState,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  GambaInitializeInstruction<
    TProgramAddress,
    TAccountInitializer,
    TAccountGambaState,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    initializer: { value: input.initializer ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69, 34])
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.initializer),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getGambaInitializeInstructionDataEncoder().encode({}),
  } as GambaInitializeInstruction<
    TProgramAddress,
    TAccountInitializer,
    TAccountGambaState,
    TAccountSystemProgram
  >;

  return instruction;
}

export type GambaInitializeInput<
  TAccountInitializer extends string = string,
  TAccountGambaState extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  initializer: TransactionSigner<TAccountInitializer>;
  gambaState: Address<TAccountGambaState>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getGambaInitializeInstruction<
  TAccountInitializer extends string,
  TAccountGambaState extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: GambaInitializeInput<
    TAccountInitializer,
    TAccountGambaState,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): GambaInitializeInstruction<
  TProgramAddress,
  TAccountInitializer,
  TAccountGambaState,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    initializer: { value: input.initializer ?? null, isWritable: true },
    gambaState: { value: input.gambaState ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.initializer),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getGambaInitializeInstructionDataEncoder().encode({}),
  } as GambaInitializeInstruction<
    TProgramAddress,
    TAccountInitializer,
    TAccountGambaState,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedGambaInitializeInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    initializer: TAccountMetas[0];
    gambaState: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: GambaInitializeInstructionData;
};

export function parseGambaInitializeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedGambaInitializeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      initializer: getNextAccount(),
      gambaState: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getGambaInitializeInstructionDataDecoder().decode(instruction.data),
  };
}
