/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const PLAYER_INITIALIZE_DISCRIMINATOR = new Uint8Array([
  213, 160, 145, 88, 197, 68, 63, 150,
]);

export function getPlayerInitializeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PLAYER_INITIALIZE_DISCRIMINATOR
  );
}

export type PlayerInitializeInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      TAccountGame extends string
        ? WritableAccount<TAccountGame>
        : TAccountGame,
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PlayerInitializeInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type PlayerInitializeInstructionDataArgs = {};

export function getPlayerInitializeInstructionDataEncoder(): FixedSizeEncoder<PlayerInitializeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: PLAYER_INITIALIZE_DISCRIMINATOR })
  );
}

export function getPlayerInitializeInstructionDataDecoder(): FixedSizeDecoder<PlayerInitializeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getPlayerInitializeInstructionDataCodec(): FixedSizeCodec<
  PlayerInitializeInstructionDataArgs,
  PlayerInitializeInstructionData
> {
  return combineCodec(
    getPlayerInitializeInstructionDataEncoder(),
    getPlayerInitializeInstructionDataDecoder()
  );
}

export type PlayerInitializeAsyncInput<
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountUser extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  player?: Address<TAccountPlayer>;
  game?: Address<TAccountGame>;
  user: TransactionSigner<TAccountUser>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getPlayerInitializeInstructionAsync<
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountUser extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PlayerInitializeAsyncInput<
    TAccountPlayer,
    TAccountGame,
    TAccountUser,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  PlayerInitializeInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountGame,
    TAccountUser,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: true },
    user: { value: input.user ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.player.value) {
    accounts.player.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 80, 76, 65, 89, 69, 82, 34])
        ),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }
  if (!accounts.game.value) {
    accounts.game.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([34, 71, 65, 77, 69, 34])),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getPlayerInitializeInstructionDataEncoder().encode({}),
  } as PlayerInitializeInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountGame,
    TAccountUser,
    TAccountSystemProgram
  >;

  return instruction;
}

export type PlayerInitializeInput<
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountUser extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  player: Address<TAccountPlayer>;
  game: Address<TAccountGame>;
  user: TransactionSigner<TAccountUser>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getPlayerInitializeInstruction<
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountUser extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PlayerInitializeInput<
    TAccountPlayer,
    TAccountGame,
    TAccountUser,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): PlayerInitializeInstruction<
  TProgramAddress,
  TAccountPlayer,
  TAccountGame,
  TAccountUser,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: true },
    user: { value: input.user ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getPlayerInitializeInstructionDataEncoder().encode({}),
  } as PlayerInitializeInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountGame,
    TAccountUser,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedPlayerInitializeInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    player: TAccountMetas[0];
    game: TAccountMetas[1];
    user: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: PlayerInitializeInstructionData;
};

export function parsePlayerInitializeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedPlayerInitializeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      player: getNextAccount(),
      game: getNextAccount(),
      user: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getPlayerInitializeInstructionDataDecoder().decode(instruction.data),
  };
}
