/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const PLAYER_CLOSE_DISCRIMINATOR = new Uint8Array([
  26, 155, 61, 179, 53, 157, 80, 30,
]);

export function getPlayerCloseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PLAYER_CLOSE_DISCRIMINATOR
  );
}

export type PlayerCloseInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      TAccountGame extends string
        ? WritableAccount<TAccountGame>
        : TAccountGame,
      ...TRemainingAccounts,
    ]
  >;

export type PlayerCloseInstructionData = { discriminator: ReadonlyUint8Array };

export type PlayerCloseInstructionDataArgs = {};

export function getPlayerCloseInstructionDataEncoder(): FixedSizeEncoder<PlayerCloseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: PLAYER_CLOSE_DISCRIMINATOR })
  );
}

export function getPlayerCloseInstructionDataDecoder(): FixedSizeDecoder<PlayerCloseInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getPlayerCloseInstructionDataCodec(): FixedSizeCodec<
  PlayerCloseInstructionDataArgs,
  PlayerCloseInstructionData
> {
  return combineCodec(
    getPlayerCloseInstructionDataEncoder(),
    getPlayerCloseInstructionDataDecoder()
  );
}

export type PlayerCloseAsyncInput<
  TAccountUser extends string = string,
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  player?: Address<TAccountPlayer>;
  game?: Address<TAccountGame>;
};

export async function getPlayerCloseInstructionAsync<
  TAccountUser extends string,
  TAccountPlayer extends string,
  TAccountGame extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PlayerCloseAsyncInput<TAccountUser, TAccountPlayer, TAccountGame>,
  config?: { programAddress?: TProgramAddress }
): Promise<
  PlayerCloseInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountPlayer,
    TAccountGame
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.player.value) {
    accounts.player.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 80, 76, 65, 89, 69, 82, 34])
        ),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }
  if (!accounts.game.value) {
    accounts.game.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([34, 71, 65, 77, 69, 34])),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
    ],
    programAddress,
    data: getPlayerCloseInstructionDataEncoder().encode({}),
  } as PlayerCloseInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountPlayer,
    TAccountGame
  >;

  return instruction;
}

export type PlayerCloseInput<
  TAccountUser extends string = string,
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  player: Address<TAccountPlayer>;
  game: Address<TAccountGame>;
};

export function getPlayerCloseInstruction<
  TAccountUser extends string,
  TAccountPlayer extends string,
  TAccountGame extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PlayerCloseInput<TAccountUser, TAccountPlayer, TAccountGame>,
  config?: { programAddress?: TProgramAddress }
): PlayerCloseInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountPlayer,
  TAccountGame
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
    ],
    programAddress,
    data: getPlayerCloseInstructionDataEncoder().encode({}),
  } as PlayerCloseInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountPlayer,
    TAccountGame
  >;

  return instruction;
}

export type ParsedPlayerCloseInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    player: TAccountMetas[1];
    game: TAccountMetas[2];
  };
  data: PlayerCloseInstructionData;
};

export function parsePlayerCloseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedPlayerCloseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      player: getNextAccount(),
      game: getNextAccount(),
    },
    data: getPlayerCloseInstructionDataDecoder().decode(instruction.data),
  };
}
