/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const PLAYER_CLAIM_DISCRIMINATOR = new Uint8Array([
  188, 220, 237, 31, 181, 18, 85, 45,
]);

export function getPlayerClaimDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PLAYER_CLAIM_DISCRIMINATOR
  );
}

export type PlayerClaimInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountUnderlyingTokenMint extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPlayerAta extends string | AccountMeta<string> = string,
  TAccountUserUnderlyingAta extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountUnderlyingTokenMint extends string
        ? ReadonlyAccount<TAccountUnderlyingTokenMint>
        : TAccountUnderlyingTokenMint,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      TAccountGame extends string
        ? WritableAccount<TAccountGame>
        : TAccountGame,
      TAccountPlayerAta extends string
        ? WritableAccount<TAccountPlayerAta>
        : TAccountPlayerAta,
      TAccountUserUnderlyingAta extends string
        ? WritableAccount<TAccountUserUnderlyingAta>
        : TAccountUserUnderlyingAta,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PlayerClaimInstructionData = { discriminator: ReadonlyUint8Array };

export type PlayerClaimInstructionDataArgs = {};

export function getPlayerClaimInstructionDataEncoder(): FixedSizeEncoder<PlayerClaimInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: PLAYER_CLAIM_DISCRIMINATOR })
  );
}

export function getPlayerClaimInstructionDataDecoder(): FixedSizeDecoder<PlayerClaimInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getPlayerClaimInstructionDataCodec(): FixedSizeCodec<
  PlayerClaimInstructionDataArgs,
  PlayerClaimInstructionData
> {
  return combineCodec(
    getPlayerClaimInstructionDataEncoder(),
    getPlayerClaimInstructionDataDecoder()
  );
}

export type PlayerClaimAsyncInput<
  TAccountUser extends string = string,
  TAccountUnderlyingTokenMint extends string = string,
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountPlayerAta extends string = string,
  TAccountUserUnderlyingAta extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  underlyingTokenMint: Address<TAccountUnderlyingTokenMint>;
  player?: Address<TAccountPlayer>;
  game?: Address<TAccountGame>;
  playerAta: Address<TAccountPlayerAta>;
  userUnderlyingAta: Address<TAccountUserUnderlyingAta>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
};

export async function getPlayerClaimInstructionAsync<
  TAccountUser extends string,
  TAccountUnderlyingTokenMint extends string,
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountPlayerAta extends string,
  TAccountUserUnderlyingAta extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PlayerClaimAsyncInput<
    TAccountUser,
    TAccountUnderlyingTokenMint,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerAta,
    TAccountUserUnderlyingAta,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  PlayerClaimInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUnderlyingTokenMint,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerAta,
    TAccountUserUnderlyingAta,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    underlyingTokenMint: {
      value: input.underlyingTokenMint ?? null,
      isWritable: false,
    },
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: true },
    playerAta: { value: input.playerAta ?? null, isWritable: true },
    userUnderlyingAta: {
      value: input.userUnderlyingAta ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.player.value) {
    accounts.player.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 80, 76, 65, 89, 69, 82, 34])
        ),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }
  if (!accounts.game.value) {
    accounts.game.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([34, 71, 65, 77, 69, 34])),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.underlyingTokenMint),
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.playerAta),
      getAccountMeta(accounts.userUnderlyingAta),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
    ],
    programAddress,
    data: getPlayerClaimInstructionDataEncoder().encode({}),
  } as PlayerClaimInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUnderlyingTokenMint,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerAta,
    TAccountUserUnderlyingAta,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >;

  return instruction;
}

export type PlayerClaimInput<
  TAccountUser extends string = string,
  TAccountUnderlyingTokenMint extends string = string,
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountPlayerAta extends string = string,
  TAccountUserUnderlyingAta extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  underlyingTokenMint: Address<TAccountUnderlyingTokenMint>;
  player: Address<TAccountPlayer>;
  game: Address<TAccountGame>;
  playerAta: Address<TAccountPlayerAta>;
  userUnderlyingAta: Address<TAccountUserUnderlyingAta>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
};

export function getPlayerClaimInstruction<
  TAccountUser extends string,
  TAccountUnderlyingTokenMint extends string,
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountPlayerAta extends string,
  TAccountUserUnderlyingAta extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PlayerClaimInput<
    TAccountUser,
    TAccountUnderlyingTokenMint,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerAta,
    TAccountUserUnderlyingAta,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): PlayerClaimInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountUnderlyingTokenMint,
  TAccountPlayer,
  TAccountGame,
  TAccountPlayerAta,
  TAccountUserUnderlyingAta,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    underlyingTokenMint: {
      value: input.underlyingTokenMint ?? null,
      isWritable: false,
    },
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: true },
    playerAta: { value: input.playerAta ?? null, isWritable: true },
    userUnderlyingAta: {
      value: input.userUnderlyingAta ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.underlyingTokenMint),
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.playerAta),
      getAccountMeta(accounts.userUnderlyingAta),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
    ],
    programAddress,
    data: getPlayerClaimInstructionDataEncoder().encode({}),
  } as PlayerClaimInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUnderlyingTokenMint,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerAta,
    TAccountUserUnderlyingAta,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >;

  return instruction;
}

export type ParsedPlayerClaimInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    underlyingTokenMint: TAccountMetas[1];
    player: TAccountMetas[2];
    game: TAccountMetas[3];
    playerAta: TAccountMetas[4];
    userUnderlyingAta: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
    tokenProgram: TAccountMetas[7];
    associatedTokenProgram: TAccountMetas[8];
  };
  data: PlayerClaimInstructionData;
};

export function parsePlayerClaimInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedPlayerClaimInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      underlyingTokenMint: getNextAccount(),
      player: getNextAccount(),
      game: getNextAccount(),
      playerAta: getNextAccount(),
      userUnderlyingAta: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
    },
    data: getPlayerClaimInstructionDataDecoder().decode(instruction.data),
  };
}
