/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { GAMBA_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const POOL_MINT_BONUS_TOKENS_DISCRIMINATOR = new Uint8Array([
  105, 130, 72, 25, 88, 185, 100, 55,
]);

export function getPoolMintBonusTokensDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    POOL_MINT_BONUS_TOKENS_DISCRIMINATOR
  );
}

export type PoolMintBonusTokensInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountGambaState extends string | AccountMeta<string> = string,
  TAccountUnderlyingTokenMint extends string | AccountMeta<string> = string,
  TAccountPoolBonusUnderlyingTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountBonusMint extends string | AccountMeta<string> = string,
  TAccountPoolJackpotTokenAccount extends string | AccountMeta<string> = string,
  TAccountUserUnderlyingAta extends string | AccountMeta<string> = string,
  TAccountUserBonusAta extends string | AccountMeta<string> = string,
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountGambaState extends string
        ? ReadonlyAccount<TAccountGambaState>
        : TAccountGambaState,
      TAccountUnderlyingTokenMint extends string
        ? ReadonlyAccount<TAccountUnderlyingTokenMint>
        : TAccountUnderlyingTokenMint,
      TAccountPoolBonusUnderlyingTokenAccount extends string
        ? WritableAccount<TAccountPoolBonusUnderlyingTokenAccount>
        : TAccountPoolBonusUnderlyingTokenAccount,
      TAccountBonusMint extends string
        ? WritableAccount<TAccountBonusMint>
        : TAccountBonusMint,
      TAccountPoolJackpotTokenAccount extends string
        ? WritableAccount<TAccountPoolJackpotTokenAccount>
        : TAccountPoolJackpotTokenAccount,
      TAccountUserUnderlyingAta extends string
        ? WritableAccount<TAccountUserUnderlyingAta>
        : TAccountUserUnderlyingAta,
      TAccountUserBonusAta extends string
        ? WritableAccount<TAccountUserBonusAta>
        : TAccountUserBonusAta,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PoolMintBonusTokensInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type PoolMintBonusTokensInstructionDataArgs = {
  amount: number | bigint;
};

export function getPoolMintBonusTokensInstructionDataEncoder(): FixedSizeEncoder<PoolMintBonusTokensInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['amount', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: POOL_MINT_BONUS_TOKENS_DISCRIMINATOR,
    })
  );
}

export function getPoolMintBonusTokensInstructionDataDecoder(): FixedSizeDecoder<PoolMintBonusTokensInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['amount', getU64Decoder()],
  ]);
}

export function getPoolMintBonusTokensInstructionDataCodec(): FixedSizeCodec<
  PoolMintBonusTokensInstructionDataArgs,
  PoolMintBonusTokensInstructionData
> {
  return combineCodec(
    getPoolMintBonusTokensInstructionDataEncoder(),
    getPoolMintBonusTokensInstructionDataDecoder()
  );
}

export type PoolMintBonusTokensAsyncInput<
  TAccountUser extends string = string,
  TAccountPool extends string = string,
  TAccountGambaState extends string = string,
  TAccountUnderlyingTokenMint extends string = string,
  TAccountPoolBonusUnderlyingTokenAccount extends string = string,
  TAccountBonusMint extends string = string,
  TAccountPoolJackpotTokenAccount extends string = string,
  TAccountUserUnderlyingAta extends string = string,
  TAccountUserBonusAta extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  pool: Address<TAccountPool>;
  gambaState?: Address<TAccountGambaState>;
  underlyingTokenMint: Address<TAccountUnderlyingTokenMint>;
  poolBonusUnderlyingTokenAccount?: Address<TAccountPoolBonusUnderlyingTokenAccount>;
  bonusMint?: Address<TAccountBonusMint>;
  poolJackpotTokenAccount?: Address<TAccountPoolJackpotTokenAccount>;
  userUnderlyingAta: Address<TAccountUserUnderlyingAta>;
  userBonusAta: Address<TAccountUserBonusAta>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  amount: PoolMintBonusTokensInstructionDataArgs['amount'];
};

export async function getPoolMintBonusTokensInstructionAsync<
  TAccountUser extends string,
  TAccountPool extends string,
  TAccountGambaState extends string,
  TAccountUnderlyingTokenMint extends string,
  TAccountPoolBonusUnderlyingTokenAccount extends string,
  TAccountBonusMint extends string,
  TAccountPoolJackpotTokenAccount extends string,
  TAccountUserUnderlyingAta extends string,
  TAccountUserBonusAta extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PoolMintBonusTokensAsyncInput<
    TAccountUser,
    TAccountPool,
    TAccountGambaState,
    TAccountUnderlyingTokenMint,
    TAccountPoolBonusUnderlyingTokenAccount,
    TAccountBonusMint,
    TAccountPoolJackpotTokenAccount,
    TAccountUserUnderlyingAta,
    TAccountUserBonusAta,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  PoolMintBonusTokensInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountPool,
    TAccountGambaState,
    TAccountUnderlyingTokenMint,
    TAccountPoolBonusUnderlyingTokenAccount,
    TAccountBonusMint,
    TAccountPoolJackpotTokenAccount,
    TAccountUserUnderlyingAta,
    TAccountUserBonusAta,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    pool: { value: input.pool ?? null, isWritable: false },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    underlyingTokenMint: {
      value: input.underlyingTokenMint ?? null,
      isWritable: false,
    },
    poolBonusUnderlyingTokenAccount: {
      value: input.poolBonusUnderlyingTokenAccount ?? null,
      isWritable: true,
    },
    bonusMint: { value: input.bonusMint ?? null, isWritable: true },
    poolJackpotTokenAccount: {
      value: input.poolJackpotTokenAccount ?? null,
      isWritable: true,
    },
    userUnderlyingAta: {
      value: input.userUnderlyingAta ?? null,
      isWritable: true,
    },
    userBonusAta: { value: input.userBonusAta ?? null, isWritable: true },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.gambaState.value) {
    accounts.gambaState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([34, 71, 65, 77, 66, 65, 95, 83, 84, 65, 84, 69, 34])
        ),
      ],
    });
  }
  if (!accounts.poolBonusUnderlyingTokenAccount.value) {
    accounts.poolBonusUnderlyingTokenAccount.value =
      await getProgramDerivedAddress({
        programAddress,
        seeds: [
          getBytesEncoder().encode(
            new Uint8Array([
              34, 80, 79, 79, 76, 95, 66, 79, 78, 85, 83, 95, 85, 78, 68, 69,
              82, 76, 89, 73, 78, 71, 95, 84, 65, 34,
            ])
          ),
          getAddressEncoder().encode(expectAddress(accounts.pool.value)),
        ],
      });
  }
  if (!accounts.bonusMint.value) {
    accounts.bonusMint.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            34, 80, 79, 79, 76, 95, 66, 79, 78, 85, 83, 95, 77, 73, 78, 84, 34,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.pool.value)),
      ],
    });
  }
  if (!accounts.poolJackpotTokenAccount.value) {
    accounts.poolJackpotTokenAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            34, 80, 79, 79, 76, 95, 74, 65, 67, 75, 80, 79, 84, 34,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.pool.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.underlyingTokenMint),
      getAccountMeta(accounts.poolBonusUnderlyingTokenAccount),
      getAccountMeta(accounts.bonusMint),
      getAccountMeta(accounts.poolJackpotTokenAccount),
      getAccountMeta(accounts.userUnderlyingAta),
      getAccountMeta(accounts.userBonusAta),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getPoolMintBonusTokensInstructionDataEncoder().encode(
      args as PoolMintBonusTokensInstructionDataArgs
    ),
  } as PoolMintBonusTokensInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountPool,
    TAccountGambaState,
    TAccountUnderlyingTokenMint,
    TAccountPoolBonusUnderlyingTokenAccount,
    TAccountBonusMint,
    TAccountPoolJackpotTokenAccount,
    TAccountUserUnderlyingAta,
    TAccountUserBonusAta,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >;

  return instruction;
}

export type PoolMintBonusTokensInput<
  TAccountUser extends string = string,
  TAccountPool extends string = string,
  TAccountGambaState extends string = string,
  TAccountUnderlyingTokenMint extends string = string,
  TAccountPoolBonusUnderlyingTokenAccount extends string = string,
  TAccountBonusMint extends string = string,
  TAccountPoolJackpotTokenAccount extends string = string,
  TAccountUserUnderlyingAta extends string = string,
  TAccountUserBonusAta extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  pool: Address<TAccountPool>;
  gambaState: Address<TAccountGambaState>;
  underlyingTokenMint: Address<TAccountUnderlyingTokenMint>;
  poolBonusUnderlyingTokenAccount: Address<TAccountPoolBonusUnderlyingTokenAccount>;
  bonusMint: Address<TAccountBonusMint>;
  poolJackpotTokenAccount: Address<TAccountPoolJackpotTokenAccount>;
  userUnderlyingAta: Address<TAccountUserUnderlyingAta>;
  userBonusAta: Address<TAccountUserBonusAta>;
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  amount: PoolMintBonusTokensInstructionDataArgs['amount'];
};

export function getPoolMintBonusTokensInstruction<
  TAccountUser extends string,
  TAccountPool extends string,
  TAccountGambaState extends string,
  TAccountUnderlyingTokenMint extends string,
  TAccountPoolBonusUnderlyingTokenAccount extends string,
  TAccountBonusMint extends string,
  TAccountPoolJackpotTokenAccount extends string,
  TAccountUserUnderlyingAta extends string,
  TAccountUserBonusAta extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof GAMBA_PROGRAM_ADDRESS,
>(
  input: PoolMintBonusTokensInput<
    TAccountUser,
    TAccountPool,
    TAccountGambaState,
    TAccountUnderlyingTokenMint,
    TAccountPoolBonusUnderlyingTokenAccount,
    TAccountBonusMint,
    TAccountPoolJackpotTokenAccount,
    TAccountUserUnderlyingAta,
    TAccountUserBonusAta,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): PoolMintBonusTokensInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountPool,
  TAccountGambaState,
  TAccountUnderlyingTokenMint,
  TAccountPoolBonusUnderlyingTokenAccount,
  TAccountBonusMint,
  TAccountPoolJackpotTokenAccount,
  TAccountUserUnderlyingAta,
  TAccountUserBonusAta,
  TAccountAssociatedTokenProgram,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? GAMBA_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    pool: { value: input.pool ?? null, isWritable: false },
    gambaState: { value: input.gambaState ?? null, isWritable: false },
    underlyingTokenMint: {
      value: input.underlyingTokenMint ?? null,
      isWritable: false,
    },
    poolBonusUnderlyingTokenAccount: {
      value: input.poolBonusUnderlyingTokenAccount ?? null,
      isWritable: true,
    },
    bonusMint: { value: input.bonusMint ?? null, isWritable: true },
    poolJackpotTokenAccount: {
      value: input.poolJackpotTokenAccount ?? null,
      isWritable: true,
    },
    userUnderlyingAta: {
      value: input.userUnderlyingAta ?? null,
      isWritable: true,
    },
    userBonusAta: { value: input.userBonusAta ?? null, isWritable: true },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.gambaState),
      getAccountMeta(accounts.underlyingTokenMint),
      getAccountMeta(accounts.poolBonusUnderlyingTokenAccount),
      getAccountMeta(accounts.bonusMint),
      getAccountMeta(accounts.poolJackpotTokenAccount),
      getAccountMeta(accounts.userUnderlyingAta),
      getAccountMeta(accounts.userBonusAta),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getPoolMintBonusTokensInstructionDataEncoder().encode(
      args as PoolMintBonusTokensInstructionDataArgs
    ),
  } as PoolMintBonusTokensInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountPool,
    TAccountGambaState,
    TAccountUnderlyingTokenMint,
    TAccountPoolBonusUnderlyingTokenAccount,
    TAccountBonusMint,
    TAccountPoolJackpotTokenAccount,
    TAccountUserUnderlyingAta,
    TAccountUserBonusAta,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedPoolMintBonusTokensInstruction<
  TProgram extends string = typeof GAMBA_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    pool: TAccountMetas[1];
    gambaState: TAccountMetas[2];
    underlyingTokenMint: TAccountMetas[3];
    poolBonusUnderlyingTokenAccount: TAccountMetas[4];
    bonusMint: TAccountMetas[5];
    poolJackpotTokenAccount: TAccountMetas[6];
    userUnderlyingAta: TAccountMetas[7];
    userBonusAta: TAccountMetas[8];
    associatedTokenProgram: TAccountMetas[9];
    tokenProgram: TAccountMetas[10];
    systemProgram: TAccountMetas[11];
  };
  data: PoolMintBonusTokensInstructionData;
};

export function parsePoolMintBonusTokensInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedPoolMintBonusTokensInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      pool: getNextAccount(),
      gambaState: getNextAccount(),
      underlyingTokenMint: getNextAccount(),
      poolBonusUnderlyingTokenAccount: getNextAccount(),
      bonusMint: getNextAccount(),
      poolJackpotTokenAccount: getNextAccount(),
      userUnderlyingAta: getNextAccount(),
      userBonusAta: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getPoolMintBonusTokensInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
