/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { STAKE_VAULT_PROGRAM_ADDRESS } from '../programs';

/** InsufficientStake: Insufficient staked amount. */
export const STAKE_VAULT_ERROR__INSUFFICIENT_STAKE = 0x1770; // 6000
/** InsufficientShares: Insufficient shares for withdraw request. */
export const STAKE_VAULT_ERROR__INSUFFICIENT_SHARES = 0x1771; // 6001
/** NoSharesInVault: No shares minted in the vault. */
export const STAKE_VAULT_ERROR__NO_SHARES_IN_VAULT = 0x1772; // 6002
/** VaultEmpty: Vault token account is empty. */
export const STAKE_VAULT_ERROR__VAULT_EMPTY = 0x1773; // 6003
/** MathOverflow: Math overflow */
export const STAKE_VAULT_ERROR__MATH_OVERFLOW = 0x1774; // 6004
/** DepositTooSmall: Deposit amount too small to mint shares. */
export const STAKE_VAULT_ERROR__DEPOSIT_TOO_SMALL = 0x1775; // 6005
/** InvalidFeeBps: Invalid withdraw fee basis points. */
export const STAKE_VAULT_ERROR__INVALID_FEE_BPS = 0x1776; // 6006

export type StakeVaultError =
  | typeof STAKE_VAULT_ERROR__DEPOSIT_TOO_SMALL
  | typeof STAKE_VAULT_ERROR__INSUFFICIENT_SHARES
  | typeof STAKE_VAULT_ERROR__INSUFFICIENT_STAKE
  | typeof STAKE_VAULT_ERROR__INVALID_FEE_BPS
  | typeof STAKE_VAULT_ERROR__MATH_OVERFLOW
  | typeof STAKE_VAULT_ERROR__NO_SHARES_IN_VAULT
  | typeof STAKE_VAULT_ERROR__VAULT_EMPTY;

let stakeVaultErrorMessages: Record<StakeVaultError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  stakeVaultErrorMessages = {
    [STAKE_VAULT_ERROR__DEPOSIT_TOO_SMALL]: `Deposit amount too small to mint shares.`,
    [STAKE_VAULT_ERROR__INSUFFICIENT_SHARES]: `Insufficient shares for withdraw request.`,
    [STAKE_VAULT_ERROR__INSUFFICIENT_STAKE]: `Insufficient staked amount.`,
    [STAKE_VAULT_ERROR__INVALID_FEE_BPS]: `Invalid withdraw fee basis points.`,
    [STAKE_VAULT_ERROR__MATH_OVERFLOW]: `Math overflow`,
    [STAKE_VAULT_ERROR__NO_SHARES_IN_VAULT]: `No shares minted in the vault.`,
    [STAKE_VAULT_ERROR__VAULT_EMPTY]: `Vault token account is empty.`,
  };
}

export function getStakeVaultErrorMessage(code: StakeVaultError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (stakeVaultErrorMessages as Record<StakeVaultError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isStakeVaultError<TProgramErrorCode extends StakeVaultError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    STAKE_VAULT_PROGRAM_ADDRESS,
    code
  );
}
