/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit';

export const REFER_ACCOUNT_DISCRIMINATOR = new Uint8Array([
  60, 125, 244, 175, 131, 109, 101, 246,
]);

export function getReferAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REFER_ACCOUNT_DISCRIMINATOR
  );
}

export type ReferAccount = {
  discriminator: ReadonlyUint8Array;
  referrer: Address;
};

export type ReferAccountArgs = { referrer: Address };

export function getReferAccountEncoder(): FixedSizeEncoder<ReferAccountArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['referrer', getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: REFER_ACCOUNT_DISCRIMINATOR })
  );
}

export function getReferAccountDecoder(): FixedSizeDecoder<ReferAccount> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['referrer', getAddressDecoder()],
  ]);
}

export function getReferAccountCodec(): FixedSizeCodec<
  ReferAccountArgs,
  ReferAccount
> {
  return combineCodec(getReferAccountEncoder(), getReferAccountDecoder());
}

export function decodeReferAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<ReferAccount, TAddress>;
export function decodeReferAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<ReferAccount, TAddress>;
export function decodeReferAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<ReferAccount, TAddress> | MaybeAccount<ReferAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getReferAccountDecoder()
  );
}

export async function fetchReferAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<ReferAccount, TAddress>> {
  const maybeAccount = await fetchMaybeReferAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeReferAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<ReferAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeReferAccount(maybeAccount);
}

export async function fetchAllReferAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<ReferAccount>[]> {
  const maybeAccounts = await fetchAllMaybeReferAccount(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeReferAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<ReferAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeReferAccount(maybeAccount));
}

export function getReferAccountSize(): number {
  return 40;
}
