/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { REFER_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_REFER_ACCOUNT_DISCRIMINATOR = new Uint8Array([
  63, 205, 62, 118, 16, 139, 150, 134,
]);

export function getCloseReferAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_REFER_ACCOUNT_DISCRIMINATOR
  );
}

export type CloseReferAccountInstruction<
  TProgram extends string = typeof REFER_PROGRAM_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountReferAccount extends string | AccountMeta<string> = string,
  TAccountCreator extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountReferAccount extends string
        ? WritableAccount<TAccountReferAccount>
        : TAccountReferAccount,
      TAccountCreator extends string
        ? ReadonlyAccount<TAccountCreator>
        : TAccountCreator,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CloseReferAccountInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type CloseReferAccountInstructionDataArgs = {};

export function getCloseReferAccountInstructionDataEncoder(): FixedSizeEncoder<CloseReferAccountInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_REFER_ACCOUNT_DISCRIMINATOR })
  );
}

export function getCloseReferAccountInstructionDataDecoder(): FixedSizeDecoder<CloseReferAccountInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseReferAccountInstructionDataCodec(): FixedSizeCodec<
  CloseReferAccountInstructionDataArgs,
  CloseReferAccountInstructionData
> {
  return combineCodec(
    getCloseReferAccountInstructionDataEncoder(),
    getCloseReferAccountInstructionDataDecoder()
  );
}

export type CloseReferAccountInput<
  TAccountAuthority extends string = string,
  TAccountReferAccount extends string = string,
  TAccountCreator extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  referAccount: Address<TAccountReferAccount>;
  creator: Address<TAccountCreator>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getCloseReferAccountInstruction<
  TAccountAuthority extends string,
  TAccountReferAccount extends string,
  TAccountCreator extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof REFER_PROGRAM_PROGRAM_ADDRESS,
>(
  input: CloseReferAccountInput<
    TAccountAuthority,
    TAccountReferAccount,
    TAccountCreator,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CloseReferAccountInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountReferAccount,
  TAccountCreator,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? REFER_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    referAccount: { value: input.referAccount ?? null, isWritable: true },
    creator: { value: input.creator ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.referAccount),
      getAccountMeta(accounts.creator),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getCloseReferAccountInstructionDataEncoder().encode({}),
  } as CloseReferAccountInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountReferAccount,
    TAccountCreator,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedCloseReferAccountInstruction<
  TProgram extends string = typeof REFER_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    referAccount: TAccountMetas[1];
    creator: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: CloseReferAccountInstructionData;
};

export function parseCloseReferAccountInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCloseReferAccountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      referAccount: getNextAccount(),
      creator: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCloseReferAccountInstructionDataDecoder().decode(instruction.data),
  };
}
