/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedCloseReferAccountInstruction,
  type ParsedConfigReferAccountInstruction,
} from '../instructions';

export const REFER_PROGRAM_PROGRAM_ADDRESS =
  'RefwFk2PPNd9bPehSyAkrkrehSHkvz6mTAHTNe8v9vH' as Address<'RefwFk2PPNd9bPehSyAkrkrehSHkvz6mTAHTNe8v9vH'>;

export enum ReferProgramAccount {
  ReferAccount,
}

export function identifyReferProgramAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): ReferProgramAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([60, 125, 244, 175, 131, 109, 101, 246])
      ),
      0
    )
  ) {
    return ReferProgramAccount.ReferAccount;
  }
  throw new Error(
    'The provided account could not be identified as a referProgram account.'
  );
}

export enum ReferProgramInstruction {
  ConfigReferAccount,
  CloseReferAccount,
}

export function identifyReferProgramInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): ReferProgramInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([239, 224, 113, 115, 108, 177, 31, 129])
      ),
      0
    )
  ) {
    return ReferProgramInstruction.ConfigReferAccount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([63, 205, 62, 118, 16, 139, 150, 134])
      ),
      0
    )
  ) {
    return ReferProgramInstruction.CloseReferAccount;
  }
  throw new Error(
    'The provided instruction could not be identified as a referProgram instruction.'
  );
}

export type ParsedReferProgramInstruction<
  TProgram extends string = 'RefwFk2PPNd9bPehSyAkrkrehSHkvz6mTAHTNe8v9vH',
> =
  | ({
      instructionType: ReferProgramInstruction.ConfigReferAccount;
    } & ParsedConfigReferAccountInstruction<TProgram>)
  | ({
      instructionType: ReferProgramInstruction.CloseReferAccount;
    } & ParsedCloseReferAccountInstruction<TProgram>);
